/*
 * AlterarPrecoPanel.java
 *
 * Created on 27 de Dezembro de 2007, 15:06
 */

package vendas.swing.app.produto;

import java.text.DecimalFormat;
import ritual.swing.NumericPlainDocument;
import ritual.util.NumberUtils;
import vendas.beans.AlteraPreco;
import vendas.swing.core.EditPanel;

/**
 *
 * @author  p993702
 */
public class AlterarPrecoEditPanel extends EditPanel {
    
    /** Creates new form AlterarPrecoPanel */
    public AlterarPrecoEditPanel() {
        initComponents();
                DecimalFormat df = new DecimalFormat("#0.00");
        valorField.setDocument(new NumericPlainDocument(df));
    }

    @Override
    public void field2Object(Object obj) {
        AlteraPreco preco = (AlteraPreco) obj;
        if (valorRadioButton.isSelected())
            preco.setTipo(0);
        else
            preco.setTipo(1);
        preco.setAlteraComissao(comissaoCheckBox.isSelected());
        preco.setAlteraPreco(precoCheckBox.isSelected());
        preco.setAlteraPreco2(preco2CheckBox.isSelected());
        preco.setAlteraPrecoFinal(precoFinalCheckBox.isSelected());
        preco.setAlteraFrete(freteCheckBox.isSelected());
        preco.setAlteraIPI(ipiCheckBox.isSelected());
        preco.setValor(NumberUtils.getBigDecimal(valorField.getValue()));
    }

    @Override
    public boolean entryValidate() {
        return comissaoCheckBox.isSelected() || precoCheckBox.isSelected() || preco2CheckBox.isSelected() || ipiCheckBox.isSelected() || precoFinalCheckBox.isSelected() || freteCheckBox.isSelected();
    }

    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        valorRadioButton = new javax.swing.JRadioButton();
        percRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        comissaoCheckBox = new javax.swing.JCheckBox();
        precoCheckBox = new javax.swing.JCheckBox();
        preco2CheckBox = new javax.swing.JCheckBox();
        precoFinalCheckBox = new javax.swing.JCheckBox();
        freteCheckBox = new javax.swing.JCheckBox();
        ipiCheckBox = new javax.swing.JCheckBox();
        valorField = new javax.swing.JFormattedTextField();

        setName("Form"); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("tipo"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        buttonGroup1.add(valorRadioButton);
        valorRadioButton.setText(bundle.getString("valor")); // NOI18N
        valorRadioButton.setName("valorRadioButton"); // NOI18N

        buttonGroup1.add(percRadioButton);
        percRadioButton.setSelected(true);
        percRadioButton.setText(bundle.getString("percentual")); // NOI18N
        percRadioButton.setName("percRadioButton"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(valorRadioButton)
                .addGap(18, 18, 18)
                .addComponent(percRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorRadioButton)
                    .addComponent(percRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText(bundle.getString("indice")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("campo"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        comissaoCheckBox.setText(bundle.getString("comissao")); // NOI18N
        comissaoCheckBox.setName("comissaoCheckBox"); // NOI18N

        precoCheckBox.setText(bundle.getString("preco")); // NOI18N
        precoCheckBox.setName("precoCheckBox"); // NOI18N

        preco2CheckBox.setText(bundle.getString("preco2")); // NOI18N
        preco2CheckBox.setName("preco2CheckBox"); // NOI18N

        precoFinalCheckBox.setText(bundle.getString("precoFinal")); // NOI18N
        precoFinalCheckBox.setName("precoFinalCheckBox"); // NOI18N

        freteCheckBox.setText(bundle.getString("frete")); // NOI18N
        freteCheckBox.setName("freteCheckBox"); // NOI18N

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("vendas/swing/app/produto/Bundle"); // NOI18N
        ipiCheckBox.setText(bundle1.getString("AlterarPrecoEditPanel.ipiCheckBox.text")); // NOI18N
        ipiCheckBox.setName("ipiCheckBox"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(comissaoCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precoCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preco2CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precoFinalCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(freteCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ipiCheckBox))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comissaoCheckBox)
                    .addComponent(precoCheckBox)
                    .addComponent(preco2CheckBox)
                    .addComponent(precoFinalCheckBox)
                    .addComponent(freteCheckBox)
                    .addComponent(ipiCheckBox))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        valorField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        valorField.setName("valorField"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(valorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox comissaoCheckBox;
    private javax.swing.JCheckBox freteCheckBox;
    private javax.swing.JCheckBox ipiCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton percRadioButton;
    private javax.swing.JCheckBox preco2CheckBox;
    private javax.swing.JCheckBox precoCheckBox;
    private javax.swing.JCheckBox precoFinalCheckBox;
    private javax.swing.JFormattedTextField valorField;
    private javax.swing.JRadioButton valorRadioButton;
    // End of variables declaration//GEN-END:variables
    
}
