/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendas.swing.app.produto;

import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.TableColumn;
import ritual.swing.FractionCellRenderer;
import ritual.swing.TApplication;
import ritual.swing.ViewFrame;
import vendas.beans.ProdutoFilter;
import vendas.dao.ProdutoDao;
import vendas.entity.Produto;
import vendas.swing.model.ProdutoRepresTableModel;
import vendas.util.Constants;
import vendas.util.Messages;
import vendas.util.Reports;

/**
 *
 * @author jaimeoliveira
 */
public class ImprimirProdutosFrame extends ViewFrame {
    
    ProdutoDao produtoDao;
    List<ProdutoRepres> produtos;
    ProdutoRepresTableModel model;

    /**
     * Creates new form ImprimirProdutosFrame
     */
    public ImprimirProdutosFrame() {
        super("Imprimir produtos", false,true,true,true);
        produtos = new ArrayList<>();
        model = new ProdutoRepresTableModel(produtos);
        initComponents();
        //jTable1.setModel(model);
        TableColumn col = jTable1.getColumnModel().getColumn(ProdutoRepresTableModel.DESCRICAO);
        col.setPreferredWidth(300);

        col = jTable1.getColumnModel().getColumn(ProdutoRepresTableModel.GRUPO);
        col.setPreferredWidth(160);

        jTable1.getColumnModel().getColumn(ProdutoRepresTableModel.PERC).setCellRenderer(new FractionCellRenderer(8, 2, SwingConstants.RIGHT));
        jTable1.getColumnModel().getColumn(ProdutoRepresTableModel.PRECO).setCellRenderer(new FractionCellRenderer(8, 2, SwingConstants.RIGHT));
        jTable1.getColumnModel().getColumn(ProdutoRepresTableModel.FATOR).setCellRenderer(new FractionCellRenderer(8, 4, SwingConstants.RIGHT));
        //model.fireTableStructureChanged();
        //pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        produtoFormattedTextField = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new JTable(model);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("produto")); // NOI18N

        produtoFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jButton1.setText(bundle.getString("incluir")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(bundle.getString("print")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(produtoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(produtoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)))
                .addContainerGap())
        );

        setBounds(0, 0, 801, 513);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (produtoFormattedTextField.getValue() == null)
            return;
        ProdutoFilter filtro = new ProdutoFilter();
        Produto produto;
        Long id = (Long)produtoFormattedTextField.getValue();
        List tmp;
        try {
            produto = (Produto)produtoDao.findById(Produto.class, id.intValue());
            filtro.setProduto(produto);
            tmp = produtoDao.findProdutoRepres(filtro);
            if (tmp != null && tmp.size() > 0) {
                produtos.addAll(tmp);
                model.fireTableDataChanged();
                produtoFormattedTextField.setValue(null);
                produtoFormattedTextField.invalidate();
            } else {
                Messages.errorMessage("Produto n\u00E3o encontrado.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (produtos.isEmpty()) {
            return;
        }
        URL url = getClass().getResource(Constants.JRREPRESPRODUTO);
        RepresProdutoDataSource ds = new RepresProdutoDataSource(produtos);
        try {
            Map map = TApplication.getInstance().getDefaultMap(getTitle(), null);
            map.put("groupEnabled", Boolean.FALSE);
            Reports.showReport(url, map, ds);
        } catch (Exception e) {
            getLogger().error(e.getMessage(), e);
            Messages.errorMessage(getBundle().getString("reportError"));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public ProdutoDao getProdutoDao() {
        return produtoDao;
    }

    public void setProdutoDao(ProdutoDao produtoDao) {
        this.produtoDao = produtoDao;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JFormattedTextField produtoFormattedTextField;
    // End of variables declaration//GEN-END:variables
}
