/*
 * ProdutoEditPanel.java
 *
 * Created on 30 de Julho de 2007, 19:41
 */
package vendas.swing.app.produto;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.Collection;
import java.util.List;
import ritual.swing.BoundedPlainDocument;
import ritual.swing.ListComboBoxModel;
import ritual.swing.NumericPlainDocument;
import ritual.swing.TApplication;
import ritual.util.NumberUtils;
import vendas.entity.GrupoProduto;
import vendas.entity.Produto;
import vendas.entity.UnidadeProduto;
import vendas.swing.core.EditPanel;
import vendas.dao.GrupoProdutoDao;
import vendas.dao.ProdutoDao;
import vendas.entity.SubGrupoProduto;
import vendas.util.Messages;

/**
 *
 * @author  Sam
 */
public class ProdutoEditPanel extends EditPanel {

    /** Creates new form ProdutoEditPanel */
    public ProdutoEditPanel() {
        initComponents();
                DecimalFormat df = new DecimalFormat("#0.0000");
        fatorConversaoField.setDocument(new NumericPlainDocument(df));
        pesoField.setDocument(new NumericPlainDocument(df));
        
    }

    @Override
    public void object2Field(Object obj) {
        Produto produto = (Produto) obj;
        codigoField.setValue(produto.getIdProduto());
        descricaoField.setText(produto.getDescricao());
        if (produto.getFatorConversao() != null) {
            fatorConversaoField.setValue(produto.getFatorConversao());
        }
        if (produto.getPeso() != null) {
            pesoField.setText(produto.getPeso().toString());
        }
        grupoComboBox.setSelectedItem(produto.getGrupoProduto());
        grupoComboBox.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                GrupoProduto grupo = (GrupoProduto) grupoComboBox.getSelectedItem();
                if (grupo != null) {
                    setSubGrupo(grupo.getSubGrupoProdutoList());
                }

            }
        });
        undCumulativaComboBox.setSelectedItem(produto.getUndCumulativa());
        unidadeComboBox.setSelectedItem(produto.getUnidade());
        if (produto.getGrupoProduto() != null) {
            setSubGrupo(produto.getGrupoProduto().getSubGrupoProdutoList());
        }
        subGrupoComboBox.setSelectedItem(produto.getSubGrupoProduto());
    }

    @Override
    public void field2Object(Object obj) {
        ProdutoDao produtoDao = (ProdutoDao) TApplication.getInstance().lookupService("produtoDao");
        GrupoProdutoDao grupoDao = (GrupoProdutoDao) TApplication.getInstance().lookupService("grupoProdutoDao");
        Produto produto = (Produto) obj;
        String codigo = codigoField.getText();
        if (codigo == null || codigo.length() == 0) {
            produto.setIdProduto(produtoDao.getNextValue());
        } else {
            produto.setIdProduto(Integer.decode(codigoField.getText()));
        }
        produto.setDescricao(descricaoField.getText());
        produto.setFatorConversao(NumberUtils.getBigDecimal(fatorConversaoField.getValue()));
        produto.setPeso(NumberUtils.getBigDecimal(pesoField.getText()));
        if (produto.getPeso() == null)
            produto.setPeso(BigDecimal.ONE);
        produto.setGrupoProduto((GrupoProduto) grupoComboBox.getModel().getSelectedItem());
        produto.setSubGrupoProduto((SubGrupoProduto) subGrupoComboBox.getModel().getSelectedItem());
        produto.setUnidade((UnidadeProduto) unidadeComboBox.getModel().getSelectedItem());
        produto.setUndCumulativa((UnidadeProduto) undCumulativaComboBox.getModel().getSelectedItem());

    }

    public void setUnidades(Collection lista) {
        unidadeComboBox.setModel(new ListComboBoxModel((List)lista));
        undCumulativaComboBox.setModel(new ListComboBoxModel((List)lista));
    }

    public void setGrupo(List lista) {
        grupoComboBox.setModel(new ListComboBoxModel(lista));
    }

    public void setSubGrupo(Collection lista) {
        subGrupoComboBox.setModel(new ListComboBoxModel((List)lista));
    }

    void setEnableCode(boolean b) {
        codigoField.setEditable(b);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codigoField = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        descricaoField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        unidadeComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        undCumulativaComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        fatorConversaoField = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        grupoComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        subGrupoComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        pesoField = new javax.swing.JTextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("codigo")); // NOI18N

        codigoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        codigoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoFieldFocusLost(evt);
            }
        });

        jLabel2.setText(bundle.getString("descricao")); // NOI18N

        descricaoField.setDocument(new BoundedPlainDocument(100));

        jLabel3.setText(bundle.getString("unidade")); // NOI18N

        jLabel4.setText(bundle.getString("unidadeConversao")); // NOI18N

        jLabel5.setText(bundle.getString("fatorConversao")); // NOI18N

        jLabel6.setText(bundle.getString("grupo")); // NOI18N

        jLabel7.setText(bundle.getString("subgrupo")); // NOI18N

        jLabel8.setText(bundle.getString("peso")); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ProdutoEditPanel.class);
        pesoField.setText(resourceMap.getString("pesoField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descricaoField, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(unidadeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(pesoField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fatorConversaoField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(undCumulativaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(subGrupoComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 179, Short.MAX_VALUE)
                                    .addComponent(grupoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descricaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unidadeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fatorConversaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(undCumulativaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grupoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(subGrupoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void codigoFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoFieldFocusLost
        if (!codigoField.isEditable())
            return;
        String s = codigoField.getText();

        if ((s == null) || (s.length() == 0)) {
            return;
        }
        ProdutoDao prd = new ProdutoDao();
        try {
            Produto produto = (Produto) prd.findById(Produto.class, Integer.decode(s));
            if (produto != null) {
                Messages.infoMessage("Produto já existe.");
                codigoField.setValue(null);

            } /*else {
            Messages.infoMessage("Produto n\u00E3o encontrado. O sistema irá gerar um código automático");
            codigoField.setValue(null);
            }*/
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_codigoFieldFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField codigoField;
    private javax.swing.JFormattedTextField descricaoField;
    private javax.swing.JFormattedTextField fatorConversaoField;
    private javax.swing.JComboBox grupoComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField pesoField;
    private javax.swing.JComboBox subGrupoComboBox;
    private javax.swing.JComboBox undCumulativaComboBox;
    private javax.swing.JComboBox unidadeComboBox;
    // End of variables declaration//GEN-END:variables
}
