/*
 * ProdutoEditPanel.java
 *
 * Created on 30 de Julho de 2007, 19:41
 */
package vendas.swing.app.produto;

import demo.ScrollablePicture;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.math.BigDecimal;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.table.TableColumn;
import org.jdesktop.application.Action;
import ritual.swing.BoundedPlainDocument;
import ritual.swing.FractionCellRenderer;
import ritual.swing.TApplication;
import ritual.swing.ViewFrame;
import vendas.entity.Produto;
import vendas.dao.GrupoProdutoDao;
import vendas.dao.ProdutoDao;
import vendas.dao.UnidadeProdutoDao;
import vendas.swing.model.RepresProdutoModel;
import vendas.util.EditDialog;
import vendas.util.Messages;
import vendas.util.StringUtils;

/**
 *
 * @author  Sam
 */
public class ProdutoViewFrame extends ViewFrame {

    public ProdutoViewFrame(String s) {
        super(s);
        initComponents();
        setTitle(s);
        boolean isAcesso = TApplication.getInstance().getUser().isAdmin() || TApplication.getInstance().getUser().isEscritorio();
        itensTable.setDefaultRenderer(BigDecimal.class, new FractionCellRenderer(8, 2, SwingConstants.RIGHT));
        itensTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        alterarButton.setEnabled(isAcesso);
        desbloquearButton.setEnabled(isAcesso);
    }
    Produto produto;
    @Override
    public void object2Field(Object obj) {
        produto = (Produto) obj;
        codigoField.setValue(produto.getIdProduto());
        descricaoField.setText(produto.getDescricao());
        fatorConversaoField.setValue(produto.getFatorConversao());
        pesoField.setValue(produto.getPeso());
        grupoField.setText(produto.getGrupoProduto().getNomeGrupo());
        if (produto.getSubGrupoProduto() != null)
            subGrupoField.setText(produto.getSubGrupoProduto().getNomeGrupo());
        undConversaoField.setText(produto.getUndCumulativa().getNome());
        unidadeField.setText(produto.getUnidade().getNome());
        bloqueadoCheckBox.setSelected(produto.isBloqueado());
        desbloquearButton.setEnabled(produto.isBloqueado() && TApplication.getInstance().getUser().isAdmin());
        RepresProdutoModel model = new RepresProdutoModel((List) produto.getProdutos());
        model.setReadOnly(true);
        itensTable.setModel(model);
        TableColumn col = itensTable.getColumnModel().getColumn(RepresProdutoModel.NOME);
        col.setPreferredWidth(250);
    }
    @Action
    public void produtoEdit() {
        GrupoProdutoDao grupoDao = (GrupoProdutoDao) TApplication.getInstance().lookupService("grupoProdutoDao");
        UnidadeProdutoDao unidadeDao = (UnidadeProdutoDao) TApplication.getInstance().lookupService("undProdutoDao");
        ProdutoDao produtoDao = (ProdutoDao) TApplication.getInstance().lookupService("produtoDao");
        ProdutoEditPanel editPanel = new ProdutoEditPanel();
        editPanel.setEnableCode(false);
        try {
            editPanel.setGrupo(grupoDao.findAll());
            editPanel.setUnidades(unidadeDao.findAll());
        } catch (Exception e) {
            getLogger().error(getBundle().getString("findErrorMessage"), e);
            Messages.errorMessage(getBundle().getString("findErrorMessage"));
            return;
        }
        produto = (Produto) getValueObject();
        EditDialog edtDlg = new EditDialog(getBundle().getString("editProdutoTitle"));
        edtDlg.setEditPanel(editPanel, !TApplication.getInstance().isGrant("ALTERAR_PRODUTO"));
        
        while (edtDlg.edit(produto)) {
            try {
                produtoDao.updateRow(produto);
                //produtoDao.updateRow(produto.getProduto());
                object2Field(produto);
                break;
            } catch (Exception e) {
                getLogger().error(getBundle().getString("saveErrorMessage"), e);
                Messages.errorMessage(getBundle().getString("saveErrorMessage"));
            }
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codigoField = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        descricaoField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        unidadeField = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        undConversaoField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        fatorConversaoField = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        grupoField = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        itensTable = new javax.swing.JTable();
        alterarButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        subGrupoField = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        pesoField = new javax.swing.JFormattedTextField();
        addFotoButton = new javax.swing.JButton();
        bloqueadoCheckBox = new javax.swing.JCheckBox();
        desbloquearButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("codigo")); // NOI18N

        codigoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        codigoField.setFocusable(false);

        jLabel2.setText(bundle.getString("descricao")); // NOI18N

        descricaoField.setDocument(new BoundedPlainDocument(40));
        descricaoField.setFocusable(false);

        jLabel3.setText(bundle.getString("unidade")); // NOI18N

        unidadeField.setDocument(new BoundedPlainDocument(40));
        unidadeField.setFocusable(false);

        jLabel4.setText(bundle.getString("unidadeConversao")); // NOI18N

        undConversaoField.setDocument(new BoundedPlainDocument(40));
        undConversaoField.setFocusable(false);

        jLabel5.setText(bundle.getString("fatorConversao")); // NOI18N

        fatorConversaoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.0000"))));
        fatorConversaoField.setFocusable(false);

        jLabel6.setText(bundle.getString("grupo")); // NOI18N

        grupoField.setDocument(new BoundedPlainDocument(40));
        grupoField.setFocusable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("fornecedores"))); // NOI18N

        jScrollPane2.setViewportView(itensTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(ProdutoViewFrame.class, this);
        alterarButton.setAction(actionMap.get("produtoEdit")); // NOI18N

        jLabel7.setText(bundle.getString("subgrupo")); // NOI18N

        subGrupoField.setDocument(new BoundedPlainDocument(40));
        subGrupoField.setFocusable(false);

        jLabel8.setText(bundle.getString("peso")); // NOI18N

        pesoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.0000"))));
        pesoField.setFocusable(false);

        addFotoButton.setText(bundle.getString("foto")); // NOI18N
        addFotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFotoButtonActionPerformed(evt);
            }
        });

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("vendas/resources/Main"); // NOI18N
        bloqueadoCheckBox.setText(bundle1.getString("bloqueado")); // NOI18N
        bloqueadoCheckBox.setFocusable(false);

        desbloquearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendas/resources/autorizar16.png"))); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ProdutoViewFrame.class);
        desbloquearButton.setToolTipText(resourceMap.getString("desbloquearButton.toolTipText")); // NOI18N
        desbloquearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desbloquearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addComponent(addFotoButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(unidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(undConversaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fatorConversaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(pesoField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(179, 179, 179)
                        .addComponent(jLabel7))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(grupoField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(subGrupoField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bloqueadoCheckBox)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(desbloquearButton, 0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(descricaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(alterarButton))
                                .addComponent(jLabel2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(descricaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alterarButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(36, 36, 36)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(unidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(undConversaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fatorConversaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pesoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grupoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(subGrupoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bloqueadoCheckBox))
                    .addComponent(desbloquearButton))
                .addGap(9, 9, 9)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addFotoButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addFoto() {
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            if (!("jpg").equals(StringUtils.getExtension(file))) {
                Messages.errorMessage("Arquivo deve ser jpg.");
                return;
            }
            if (file.length() > 1024 * 1024) {
                Messages.errorMessage("Arquivo muito grande.");
                return;
            }

            byte[] bFile = new byte[(int) file.length()];
            try {
                FileInputStream fileInputStream = new FileInputStream(file);
                //convert file into array of bytes
                fileInputStream.read(bFile);
                fileInputStream.close();
                produto.setFoto(bFile);
                ProdutoDao produtoDao = (ProdutoDao) TApplication.getInstance().lookupService("produtoDao");
                produtoDao.updateRow(produto);
            } catch (Exception e) {
                getLogger().error(getBundle().getString("saveErrorMessage"), e);
                Messages.errorMessage(getBundle().getString("saveErrorMessage"));
            }
        }
    }
    
    private void viewFoto() {
        if (produto.getFoto() == null) {
            Messages.errorMessage("Sem imagem definida");
            return;
        }
        Image image = null;
        try {
            InputStream is = produto.getBlob().getBinaryStream();
            image = ImageIO.read(is);
        } catch (Exception e) {
            getLogger().error(getBundle().getString("imageErrorMessage"), e);
            Messages.errorMessage(getBundle().getString("imageErrorMessage"));
        }
        JInternalFrame frame = new JInternalFrame(title, true, true, true, true);
        //frame.setSize(400, 400);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ScrollablePicture picture;
        //frame.setLayout(new BoxLayout(this, BoxLayout.LINE_AXIS));
        picture = new ScrollablePicture(new ImageIcon(image), 1);
        JScrollPane pictureScrollPane = new JScrollPane(picture);
        pictureScrollPane.setPreferredSize(new Dimension(300, 250));
        pictureScrollPane.setViewportBorder(BorderFactory.createLineBorder(Color.black));
        frame.getContentPane().add(pictureScrollPane);
        TApplication.getInstance().getDesktopPane().add(frame);
        frame.setVisible(true);
    }
    
    private void addFotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFotoButtonActionPerformed
        if (produto.getFoto() == null) {
           addFoto();
        } else {
            viewFoto();
        }
    }//GEN-LAST:event_addFotoButtonActionPerformed

private void desbloquearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desbloquearButtonActionPerformed
    ProdutoDao produtoDao = (ProdutoDao) TApplication.getInstance().lookupService("produtoDao");
    try {
        produto.setBloqueado(false);
        produtoDao.updateRow(produto);    
        desbloquearButton.setEnabled(!produto.isBloqueado());
        bloqueadoCheckBox.setSelected(!produto.isBloqueado());
        desbloquearButton.invalidate();
        bloqueadoCheckBox.invalidate();
        Messages.infoMessage("Produto desbloqueado.");
        object2Field(produto);
        if (getParentViewFrame() != null) {
            getParentViewFrame().refresh();
        }
    } catch (Exception e) {
        getLogger().error(e);
        Messages.errorMessage("Falha ao desbloquear");
    }
}//GEN-LAST:event_desbloquearButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFotoButton;
    private javax.swing.JButton alterarButton;
    private javax.swing.JCheckBox bloqueadoCheckBox;
    private javax.swing.JFormattedTextField codigoField;
    private javax.swing.JButton desbloquearButton;
    private javax.swing.JFormattedTextField descricaoField;
    private javax.swing.JFormattedTextField fatorConversaoField;
    private javax.swing.JFormattedTextField grupoField;
    private javax.swing.JTable itensTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFormattedTextField pesoField;
    private javax.swing.JFormattedTextField subGrupoField;
    private javax.swing.JFormattedTextField undConversaoField;
    private javax.swing.JFormattedTextField unidadeField;
    // End of variables declaration//GEN-END:variables
}
