/*
 * RepresProdutoEditPanel.java
 *
 * Created on 1 de Agosto de 2007, 22:12
 */

package vendas.swing.app.produto;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.List;
import ritual.swing.ListComboBoxModel;
import ritual.swing.NumericPlainDocument;
import ritual.util.NumberUtils;
import vendas.entity.Repres;
import vendas.entity.RepresProduto;
import vendas.swing.core.EditPanel;

/**
 *
 * @author  Sam
 */
public class RepresProdutoEditPanel extends EditPanel {

    /** Creates new form RepresProdutoEditPanel */
    public RepresProdutoEditPanel() {
        initComponents();
    }
    
    @Override
    public void object2Field(Object obj) {
        RepresProduto produto = (RepresProduto) obj;
        ativoCheckBox.setSelected(produto.getAtivado().booleanValue());
        DecimalFormat df = new DecimalFormat("#0.00");
        ipiField.setDocument(new NumericPlainDocument(df));
        ipiField.setValue(produto.getIpi());
        precoField.setValue(produto.getPreco());
        precoField.setDocument(new NumericPlainDocument(df));
        freteField.setValue(produto.getPreco());
        freteField.setDocument(new NumericPlainDocument(df));
        precoFinalField.setDocument(new NumericPlainDocument(df));
        precoFinalField.setValue(produto.getPrecoFinal());
        qtdUndField.setValue(produto.getQtdUnd());
        represComboBox.setSelectedItem(produto.getRepres());
        embalagemField.setValue(produto.getEmbalagem());
        df = new DecimalFormat("#0.00");
        
    }
    
    @Override
    public void field2Object(Object obj) {
        RepresProduto produto = (RepresProduto) obj;
        produto.setAtivado(ativoCheckBox.isSelected());
        produto.setIpi((BigDecimal)ipiField.getValue());
        produto.setPreco((BigDecimal)precoField.getValue());
        produto.setFrete((BigDecimal)precoField.getValue());
        produto.setPrecoFinal((BigDecimal)precoFinalField.getValue());
        produto.setQtdUnd((BigDecimal)qtdUndField.getValue());
        produto.setEmbalagem((BigDecimal)embalagemField.getValue());
        Repres repres = (Repres)represComboBox.getModel().getSelectedItem();
        produto.setRepres(repres);
        produto.getRepresProdutoPK().setIdRepres(repres.getIdRepres());
    }
        
    public void setRepres(List lista) {
        represComboBox.setModel(new ListComboBoxModel(lista));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        represComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        ipiField = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        precoField = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        precoFinalField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        qtdUndField = new javax.swing.JFormattedTextField();
        ativoCheckBox = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        embalagemField = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        freteField = new javax.swing.JFormattedTextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("representada")); // NOI18N

        jLabel2.setText(bundle.getString("ipi")); // NOI18N

        jLabel4.setText(bundle.getString("preco")); // NOI18N

        jLabel8.setText(bundle.getString("precoFinal")); // NOI18N

        jLabel5.setText(bundle.getString("qtdUnidade")); // NOI18N

        ativoCheckBox.setText(bundle.getString("ativo")); // NOI18N
        ativoCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ativoCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel13.setText(bundle.getString("embalagem")); // NOI18N

        embalagemField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0000"))));

        jLabel9.setText(bundle.getString("frete")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(represComboBox, 0, 353, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ipiField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precoField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(precoFinalField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(freteField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(qtdUndField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(embalagemField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addComponent(ativoCheckBox))
                            .addComponent(jLabel13))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(represComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ipiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precoFinalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(freteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtdUndField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(embalagemField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ativoCheckBox))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ativoCheckBox;
    private javax.swing.JFormattedTextField embalagemField;
    private javax.swing.JFormattedTextField freteField;
    private javax.swing.JFormattedTextField ipiField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField precoField;
    private javax.swing.JFormattedTextField precoFinalField;
    private javax.swing.JFormattedTextField qtdUndField;
    private javax.swing.JComboBox represComboBox;
    // End of variables declaration//GEN-END:variables
    
}
