/*
 * ClienteVisitaPanel.java
 *
 * Created on 14 de Julho de 2007, 17:09
 */

package vendas.swing.app.cliente;

import java.util.ArrayList;
import java.util.List;
import ritual.swing.ListComboBoxModel;
import vendas.entity.ClienteContato;
import vendas.entity.TipoContato;
import vendas.swing.core.EditPanel;

/**
 *
 * @author  Sam
 */
public class ClienteContatoPanel extends EditPanel {
    
    /** Creates new form ClienteVisitaPanel */
    public ClienteContatoPanel() {
        initComponents();
        List lista = new ArrayList();
        lista.add(new TipoContato("1", "E-Mail comercial"));
        lista.add(new TipoContato("2", "E-Mail"));
        lista.add(new TipoContato("3", "Skype"));
        lista.add(new TipoContato("4", "E-Mail financeiro"));
        lista.add(new TipoContato("5", "E-Mail NFE"));
        tipoComboBox.setModel(new ListComboBoxModel(lista));
    }
    
    @Override
    public void object2Field(Object obj) {
        ClienteContato visitaCliente = (ClienteContato) obj;
        enderecoField.setText(visitaCliente.getEndereco());
        tipoComboBox.setSelectedItem(visitaCliente.getClienteContatoPK().getTipo());
    }
    
    @Override
    public void field2Object(Object obj) {
        ClienteContato visitaCliente = (ClienteContato) obj;
        visitaCliente.setEndereco(enderecoField.getText());
        TipoContato tipo = (TipoContato)tipoComboBox.getModel().getSelectedItem();
        visitaCliente.getClienteContatoPK().setTipo(tipo.getTipo().charAt(0));
    }

    @Override
    public void enableControls(boolean enabled) {
        tipoComboBox.setEnabled(enabled);
    }


    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tipoComboBox = new javax.swing.JComboBox();
        enderecoField = new javax.swing.JTextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("endereco")); // NOI18N

        jLabel2.setText(bundle.getString("tipo")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enderecoField, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enderecoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField enderecoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox tipoComboBox;
    // End of variables declaration//GEN-END:variables
    
}
