/*
 * ClienteEditPanel.java
 *
 * Created on 30 de Junho de 2007, 11:24
 */

package vendas.swing.app.cliente;

import java.util.List;
import vendas.entity.Cliente;
import vendas.entity.SituacaoCliente;
import vendas.swing.core.EditPanel;
import vendas.swing.core.Formats;
import ritual.swing.BoundedPlainDocument;
import ritual.swing.ListComboBoxModel;
import ritual.util.NumberUtils;

/**
 *
 * @author  Sam
 */
public class ClienteEditPanel extends EditPanel {
    
    /** Creates new form ClienteEditPanel */
    public ClienteEditPanel() {
        initComponents();
    }
    
    @Override
    public void object2Field(Object obj) {
        Cliente cliente = (Cliente) obj;
        bairroField.setText(cliente.getBairro());
        cepField.setText(cliente.getCep());
        cidadeField.setText(cliente.getCidade());
        cnpjField.setText(cliente.getCnpj());
        dtInclusaoField.setDate(cliente.getDtInclusao());
        enderecoField.setText(cliente.getEndereco());
        limiteCreditoField.setValue(cliente.getLimiteCredito());
        fone1Field.setText(cliente.getFone1());
        fone2Field.setText(cliente.getFone2());
        fone3Field.setText(cliente.getFone3());
        inscrEstField.setText(cliente.getInscrEstadual());
        razaoField.setText(cliente.getRazao());
        situacaoComboBox.setSelectedItem(cliente.getSituacaoCliente());
        ufField.setText(cliente.getUf());
        empilhadeiraCheckBox.setSelected(cliente.isEmpilhadeira());
        entregarBoletoCheckBox.setSelected(cliente.isEntregarBoleto());
        subsTributariaCheckBox.setSelected(cliente.isSubstituicaoTributaria());
        reduzidoField.setText((cliente.getFantasia()));
        siteField.setText((cliente.getSite()));
    }

    @Override
    public void field2Object(Object obj) {
        Cliente cliente = (Cliente) obj;
        cliente.setBairro(bairroField.getText());
        cliente.setCep(cepField.getText());
        cliente.setCidade(cidadeField.getText());
        cliente.setCnpj(cnpjField.getText());
        cliente.setDtInclusao(dtInclusaoField.getDate());
        cliente.setEndereco(enderecoField.getText());
        cliente.setLimiteCredito(NumberUtils.getBigDecimal(limiteCreditoField.getValue()));
        cliente.setFone1(fone1Field.getText());
        cliente.setFone2(fone2Field.getText());
        cliente.setFone3(fone3Field.getText());
        cliente.setInscrEstadual(inscrEstField.getText());
        cliente.setRazao(razaoField.getText());
        cliente.setSituacaoCliente((SituacaoCliente)situacaoComboBox.getModel().getSelectedItem());
        cliente.setUf(ufField.getText());
        cliente.setEmpilhadeira(empilhadeiraCheckBox.isSelected());
        cliente.setSubstituicaoTributaria(subsTributariaCheckBox.isSelected());
        cliente.setEntregarBoleto(entregarBoletoCheckBox.isSelected());
        cliente.setFantasia(reduzidoField.getText());
        cliente.setSite(siteField.getText());
    }
    
    public void setSituacoes(List situacoes) {
        situacaoComboBox.setModel(new ListComboBoxModel(situacoes));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        razaoLabel = new javax.swing.JLabel();
        razaoField = new javax.swing.JFormattedTextField();
        reduzidoLabel = new javax.swing.JLabel();
        reduzidoField = new javax.swing.JFormattedTextField();
        siteLabel = new javax.swing.JLabel();
        siteField = new javax.swing.JFormattedTextField();
        cnpjLabel = new javax.swing.JLabel();
        cnpjField = new javax.swing.JFormattedTextField();
        inscrEstLabel = new javax.swing.JLabel();
        inscrEstField = new javax.swing.JFormattedTextField();
        dtInclusaoLabel = new javax.swing.JLabel();
        dtInclusaoField = new com.toedter.calendar.JDateChooser();
        enderecoLabel = new javax.swing.JLabel();
        enderecoField = new javax.swing.JFormattedTextField();
        bairroLabel = new javax.swing.JLabel();
        bairroField = new javax.swing.JFormattedTextField();
        cepLabel = new javax.swing.JLabel();
        cepField = new javax.swing.JFormattedTextField(Formats.createFormatter("########"));
        cidadeLabel = new javax.swing.JLabel();
        cidadeField = new javax.swing.JFormattedTextField();
        ufLabel = new javax.swing.JLabel();
        ufField = new javax.swing.JFormattedTextField(Formats.createFormatter("UU"));
        fone1Label = new javax.swing.JLabel();
        fone1Field = new javax.swing.JFormattedTextField();
        fone2Label = new javax.swing.JLabel();
        fone2Field = new javax.swing.JFormattedTextField();
        fone3Label = new javax.swing.JLabel();
        fone3Field = new javax.swing.JFormattedTextField();
        situacaoLabel = new javax.swing.JLabel();
        situacaoComboBox = new javax.swing.JComboBox();
        empilhadeiraCheckBox = new javax.swing.JCheckBox();
        entregarBoletoCheckBox = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        limiteCreditoField = new javax.swing.JFormattedTextField();
        subsTributariaCheckBox = new javax.swing.JCheckBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        razaoLabel.setText(bundle.getString("razaoSocial")); // NOI18N

        razaoField.setDocument(new BoundedPlainDocument(50));

        reduzidoLabel.setText(bundle.getString("nomeReduzido")); // NOI18N

        reduzidoField.setColumns(30);
        reduzidoField.setDocument(new BoundedPlainDocument(30));

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("vendas/swing/app/cliente/Bundle"); // NOI18N
        siteLabel.setText(bundle1.getString("ClienteEditPanel.siteLabel.text")); // NOI18N

        siteField.setColumns(100);

        cnpjLabel.setText(bundle.getString("cnpj")); // NOI18N

        cnpjField.setColumns(14);

        inscrEstLabel.setText(bundle.getString("inscrEstadual")); // NOI18N

        dtInclusaoLabel.setText(bundle.getString("dtInclusao")); // NOI18N

        enderecoLabel.setText(bundle.getString("endereco")); // NOI18N

        enderecoField.setColumns(60);
        enderecoField.setDocument(new BoundedPlainDocument(60));

        bairroLabel.setText(bundle.getString("bairro")); // NOI18N

        bairroField.setColumns(30);
        bairroField.setDocument(new BoundedPlainDocument(25));

        cepLabel.setText(bundle.getString("cep")); // NOI18N

        cepField.setColumns(8);

        cidadeLabel.setText(bundle.getString("cidade")); // NOI18N

        cidadeField.setColumns(30);
        cidadeField.setDocument(new BoundedPlainDocument(30));

        ufLabel.setText(bundle.getString("uf")); // NOI18N

        ufField.setColumns(2);
        ufField.setDocument(new BoundedPlainDocument(2));

        fone1Label.setText(bundle.getString("fone1")); // NOI18N

        fone1Field.setColumns(20);

        fone2Label.setText(bundle.getString("fone2")); // NOI18N

        fone2Field.setColumns(20);

        fone3Label.setText(bundle.getString("fone3")); // NOI18N

        fone3Field.setColumns(20);

        situacaoLabel.setText(bundle.getString("situacaoCliente")); // NOI18N

        empilhadeiraCheckBox.setText(bundle.getString("empilhadeira")); // NOI18N

        entregarBoletoCheckBox.setText(bundle.getString("entregarBoleto")); // NOI18N

        jLabel12.setText(bundle.getString("limiteCredito")); // NOI18N

        limiteCreditoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        subsTributariaCheckBox.setText(bundle1.getString("ClienteEditPanel.subsTributariaCheckBox.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bairroLabel)
                            .addComponent(bairroField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cepLabel)
                            .addComponent(cepField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cidadeField, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(cidadeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ufField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ufLabel))
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(razaoField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                            .addComponent(enderecoField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(limiteCreditoField, 0, 0, Short.MAX_VALUE)
                                        .addGap(87, 87, 87)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subsTributariaCheckBox)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(empilhadeiraCheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(entregarBoletoCheckBox)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecoLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fone1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fone1Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fone2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fone2Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fone3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fone3Label)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cnpjField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cnpjLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inscrEstField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inscrEstLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtInclusaoLabel)
                                    .addComponent(dtInclusaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(razaoLabel)
                            .addComponent(situacaoLabel)
                            .addComponent(situacaoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reduzidoLabel)
                                    .addComponent(reduzidoField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(siteLabel)
                                        .addGap(0, 345, Short.MAX_VALUE))
                                    .addComponent(siteField, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(razaoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(razaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(reduzidoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reduzidoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(siteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(siteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnpjLabel)
                    .addComponent(inscrEstLabel)
                    .addComponent(dtInclusaoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cnpjField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inscrEstField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtInclusaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enderecoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enderecoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bairroLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bairroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cepLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cidadeLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ufField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(ufLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fone1Label)
                    .addComponent(fone2Label)
                    .addComponent(fone3Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fone1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fone2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fone3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(situacaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(situacaoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(empilhadeiraCheckBox)
                        .addComponent(entregarBoletoCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(limiteCreditoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subsTributariaCheckBox))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField bairroField;
    private javax.swing.JLabel bairroLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField cepField;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JFormattedTextField cidadeField;
    private javax.swing.JLabel cidadeLabel;
    private javax.swing.JFormattedTextField cnpjField;
    private javax.swing.JLabel cnpjLabel;
    private com.toedter.calendar.JDateChooser dtInclusaoField;
    private javax.swing.JLabel dtInclusaoLabel;
    private javax.swing.JCheckBox empilhadeiraCheckBox;
    private javax.swing.JFormattedTextField enderecoField;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JCheckBox entregarBoletoCheckBox;
    private javax.swing.JFormattedTextField fone1Field;
    private javax.swing.JLabel fone1Label;
    private javax.swing.JFormattedTextField fone2Field;
    private javax.swing.JLabel fone2Label;
    private javax.swing.JFormattedTextField fone3Field;
    private javax.swing.JLabel fone3Label;
    private javax.swing.JFormattedTextField inscrEstField;
    private javax.swing.JLabel inscrEstLabel;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JFormattedTextField limiteCreditoField;
    private javax.swing.JFormattedTextField razaoField;
    private javax.swing.JLabel razaoLabel;
    private javax.swing.JFormattedTextField reduzidoField;
    private javax.swing.JLabel reduzidoLabel;
    private javax.swing.JFormattedTextField siteField;
    private javax.swing.JLabel siteLabel;
    private javax.swing.JComboBox situacaoComboBox;
    private javax.swing.JLabel situacaoLabel;
    private javax.swing.JCheckBox subsTributariaCheckBox;
    private javax.swing.JFormattedTextField ufField;
    private javax.swing.JLabel ufLabel;
    // End of variables declaration//GEN-END:variables
    
}
