/*
 * ClienteRepresPanel.java
 *
 * Created on 14 de Julho de 2007, 18:30
 */

package vendas.swing.app.cliente;

import java.text.DecimalFormat;
import java.util.List;
import ritual.swing.ListComboBoxModel;
import ritual.swing.NumericPlainDocument;
import ritual.util.NumberUtils;
import vendas.entity.ClienteRepres;
import vendas.entity.Repres;
import vendas.swing.core.EditPanel;

/**
 *
 * @author  Sam
 */
public class ClienteRepresPanel extends EditPanel {
    
    /** Creates new form ClienteRepresPanel */
    public ClienteRepresPanel() {
        initComponents();
        DecimalFormat df = new DecimalFormat("#0.00");
        limiteField.setDocument(new NumericPlainDocument(df));
    }
    
    public void setRepres(List repres) {
        represComboBox.setModel(new ListComboBoxModel(repres));
    }    
    
    @Override
    public void object2Field(Object obj) {
        ClienteRepres repres = (ClienteRepres) obj;
        codIdentField.setText(repres.getCodIdentificador());
        codRepresField.setText(repres.getCodRepres());
        represComboBox.setSelectedItem(repres.getRepres());
        limiteField.setValue(repres.getLimiteCredito());
    }

    @Override
    public void field2Object(Object obj) {
        ClienteRepres repres = (ClienteRepres) obj;        
        repres.setCodIdentificador(codIdentField.getText());
        repres.setCodRepres(codRepresField.getText());
        Repres value = (Repres)represComboBox.getModel().getSelectedItem();
        repres.getClienteRepresPK().setIdRepres(value.getIdRepres());
        repres.setRepres(value);
        if (limiteField.getValue() != null)
        repres.setLimiteCredito(NumberUtils.getBigDecimal(limiteField.getValue()));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        represComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        codIdentField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        codRepresField = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        limiteField = new javax.swing.JFormattedTextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("representada")); // NOI18N

        jLabel2.setText(bundle.getString("identificador")); // NOI18N

        jLabel3.setText(bundle.getString("codigo")); // NOI18N

        jLabel4.setText(bundle.getString("limite")); // NOI18N

        limiteField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(represComboBox, 0, 382, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(codIdentField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(codRepresField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(limiteField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(represComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codIdentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codRepresField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(limiteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField codIdentField;
    private javax.swing.JFormattedTextField codRepresField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JFormattedTextField limiteField;
    private javax.swing.JComboBox represComboBox;
    // End of variables declaration//GEN-END:variables
    
}
