/*
 * ClienteVisitaPanel.java
 *
 * Created on 14 de Julho de 2007, 17:09
 */
package vendas.swing.app.cliente;

import java.util.List;
import ritual.swing.ListComboBoxModel;
import ritual.swing.TApplication;
import vendas.dao.VendedorDao;
import vendas.entity.Vendedor;
import vendas.entity.VisitaCliente;
import vendas.swing.core.EditPanel;
import vendas.util.Constants;

/**
 *
 * @author  Sam
 */
public class ClienteVisitaPanel extends EditPanel {

    /** Creates new form ClienteVisitaPanel */
    public ClienteVisitaPanel() {
        initComponents();
    }

    @Override
    public void init() {
        TApplication app = TApplication.getInstance();
        if (app.getUser().isVendedor()) {
            VendedorDao dao = (VendedorDao) app.lookupService("vendedorDao");
            try {
                vendedorComboBox.setSelectedItem(dao.findById(Vendedor.class, app.getUser().getIdvendedor()));
                vendedorComboBox.setEditable(false);
                vendedorComboBox.setEnabled(false);
            } catch (Exception e) {
                getLogger().error(e);
            }
        }
        naoVisitaCheckBox.setSelected(Boolean.FALSE);
    }

    public void setVendedores(List vendedores) {
        vendedorComboBox.setModel(new ListComboBoxModel(vendedores));
    }

    @Override
    public void object2Field(Object obj) {
        VisitaCliente visitaCliente = (VisitaCliente) obj;
        dtVisitaField.setDate(visitaCliente.getDtVisita());
        obsTextArea.setText(visitaCliente.getObs());
        //dtVisitaRealField.setDate(visitaCliente.getDtVisitaRealizada());
        //gerouPedidoCheckBox.setSelected(visitaCliente.getGerouPedido().booleanValue());
        vendedorComboBox.setSelectedItem(visitaCliente.getVendedor());
        TApplication app = TApplication.getInstance();
        if (app.getUser().isVendedor()) {
            vendedorComboBox.setEditable(false);
                vendedorComboBox.setEnabled(false);
        }
        naoVisitaCheckBox.setSelected(visitaCliente.getTipoVisita().equals("N"));
    }

    @Override
    public void field2Object(Object obj) {
        VisitaCliente visitaCliente = (VisitaCliente) obj;
        visitaCliente.setDtVisita(dtVisitaField.getDate());
        Vendedor vendedor = (Vendedor) vendedorComboBox.getModel().getSelectedItem();
        visitaCliente.setVendedor(vendedor);
        visitaCliente.setTipoVisita(naoVisitaCheckBox.isSelected()  ? "N" : "V");
        visitaCliente.setObs(obsTextArea.getText());
        //visitaCliente.setDtVisitaRealizada(dtVisitaRealField.getDate());
        //visitaCliente.setGerouPedido(new Boolean(gerouPedidoCheckBox.isSelected()));

        visitaCliente.setVendedor(vendedor);
    }

    public Boolean getNaoVisita() {
        return naoVisitaCheckBox.isSelected();
    }

    public void setNaoVisita(Boolean naoVisita) {
        naoVisitaCheckBox.setSelected(naoVisita);
    }

    @Override
    public boolean entryValidate() {
        Vendedor v = (Vendedor) vendedorComboBox.getModel().getSelectedItem();
        if ((v == null) || (v.getIdVendedor() == null)) {
            return false;
        };
        
        if (naoVisitaCheckBox.isSelected() && (obsTextArea.getText() == null || obsTextArea.getText().length() == 0)) {
            return false;
        }
        
        return true;
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dtVisitaField = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        vendedorComboBox = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        obsTextArea = new javax.swing.JTextArea();
        naoVisitaCheckBox = new javax.swing.JCheckBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("dtVisita")); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ClienteVisitaPanel.class);
        dtVisitaField.setDateFormatString(resourceMap.getString("dtVisitaField.dateFormatString")); // NOI18N

        jLabel2.setText(bundle.getString("vendedor")); // NOI18N

        jLabel29.setText(bundle.getString("obs")); // NOI18N

        obsTextArea.setColumns(20);
        obsTextArea.setRows(5);
        jScrollPane1.setViewportView(obsTextArea);

        naoVisitaCheckBox.setText(bundle.getString("naoVisita")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dtVisitaField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(naoVisitaCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(vendedorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dtVisitaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(naoVisitaCheckBox))
                .addGap(6, 6, 6)
                .addComponent(vendedorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel29)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dtVisitaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox naoVisitaCheckBox;
    private javax.swing.JTextArea obsTextArea;
    private javax.swing.JComboBox vendedorComboBox;
    // End of variables declaration//GEN-END:variables
}
