/*
 * ContatoEditPanel.java
 *
 * Created on 12 de Julho de 2007, 13:49
 */

package vendas.swing.app.cliente;

import java.text.DecimalFormat;
import ritual.swing.BoundedPlainDocument;
import vendas.entity.ContatoVendedor;
import vendas.swing.core.EditPanel;

/**
 *
 * @author  p993702
 */
public class ContatoVendedorEditPanel extends EditPanel {
    
    /** Creates new form ContatoEditPanel */
    public ContatoVendedorEditPanel() {
        initComponents();
    }

    @Override
    public void object2Field(Object obj) {
        ContatoVendedor contatoVendedor = (ContatoVendedor) obj;
        nomeField.setText(contatoVendedor.getContato());
        if (contatoVendedor.getAniversario() != null) {
        jSpinner1.setValue(new Integer(contatoVendedor.getDiaAniversario()));
        jSpinner2.setValue(new Integer(contatoVendedor.getMesAniversario()));
        }
        textArea.setText((contatoVendedor.getObservacao()));
        msnField.setText(contatoVendedor.getMsn());
        if ("P".equals(contatoVendedor.getTipoContatoVendedor()))
            pessoalRadioButton.setSelected(true);
        else if ("F".equals(contatoVendedor.getTipoContatoVendedor()))
            familiaRadioButton.setSelected(true);
        else
            outrosRadioButton.setSelected(true);

    }
    
    @Override
    public void field2Object(Object obj) {
        ContatoVendedor contatoVendedor = (ContatoVendedor) obj;
        contatoVendedor.setContato(nomeField.getText());
        DecimalFormat df = new DecimalFormat("00");
        if (((Integer)jSpinner1.getValue()).intValue() == 0 || ((Integer)jSpinner2.getValue()).intValue() == 0)
            contatoVendedor.setAniversario(null);
        else
            contatoVendedor.setAniversario(df.format(jSpinner2.getValue()) + df.format(jSpinner1.getValue()));

        contatoVendedor.setMsn(msnField.getText());
        contatoVendedor.setObservacao((textArea.getText()));
        if (pessoalRadioButton.isSelected())
            contatoVendedor.setTipoContatoVendedor("P");
        else if (familiaRadioButton.isSelected())
            contatoVendedor.setTipoContatoVendedor("F");
        else
            contatoVendedor.setTipoContatoVendedor("O");
    }

    @Override
    public boolean entryValidate() {
        return nomeField.getText() != null;

    }


    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nomeField = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        msnField = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        pessoalRadioButton = new javax.swing.JRadioButton();
        familiaRadioButton = new javax.swing.JRadioButton();
        outrosRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("nome")); // NOI18N

        nomeField.setDocument(new BoundedPlainDocument(30));

        jLabel2.setText(bundle.getString("dtAniversario")); // NOI18N

        jLabel3.setText(bundle.getString("email")); // NOI18N

        jLabel4.setText(bundle.getString("tipo")); // NOI18N

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 31, 1));

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));

        buttonGroup1.add(pessoalRadioButton);
        pessoalRadioButton.setSelected(true);
        pessoalRadioButton.setLabel(bundle.getString("pessoal")); // NOI18N

        buttonGroup1.add(familiaRadioButton);
        familiaRadioButton.setLabel(bundle.getString("familia")); // NOI18N

        buttonGroup1.add(outrosRadioButton);
        outrosRadioButton.setLabel(bundle.getString("outros")); // NOI18N

        jLabel5.setText(bundle.getString("complemento")); // NOI18N

        textArea.setColumns(20);
        textArea.setLineWrap(true);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(msnField, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pessoalRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(familiaRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(outrosRadioButton))
                            .addComponent(jLabel5))
                        .addGap(0, 118, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pessoalRadioButton)
                    .addComponent(familiaRadioButton)
                    .addComponent(outrosRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton familiaRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JFormattedTextField msnField;
    private javax.swing.JFormattedTextField nomeField;
    private javax.swing.JRadioButton outrosRadioButton;
    private javax.swing.JRadioButton pessoalRadioButton;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
    
}
