/*
 * ClienteSegmentoPanel.java
 *
 * Created on 14 de Julho de 2007, 11:27
 */

package vendas.swing.app.cliente;

import java.util.List;
import ritual.swing.ListComboBoxModel;
import vendas.entity.GrupoCliente;
import vendas.swing.core.EditPanel;

/**
 *
 * @author  Sam
 */
public class GrupoClientePanel extends EditPanel {
    
    /** Creates new form ClienteSegmentoPanel */
    public GrupoClientePanel() {
        initComponents();
    }
    
    public void setGruposClientes(List segmentos) {
        grupoComboBox.setModel(new ListComboBoxModel(segmentos));
    }

    @Override
    public void field2Object(Object obj) {
        GrupoCliente segmento = (GrupoCliente)obj;
        GrupoCliente value = (GrupoCliente)grupoComboBox.getModel().getSelectedItem();
        segmento.setIdGrupoCliente(value.getIdGrupoCliente());
        segmento.setNomeGrupo(value.getNomeGrupo());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        grupoComboBox = new javax.swing.JComboBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("grupoCliente")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grupoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grupoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox grupoComboBox;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
