/*
 * NewJInternalFrame.java
 *
 * Created on 15 de Dezembro de 2007, 13:47
 */

package vendas.swing.app.cliente;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.Collection;
import java.util.List;
import javax.swing.table.TableColumn;
import ritual.swing.ListComboBoxModel;
import vendas.dao.ClienteDao;
import vendas.dao.GrupoClienteDao;
import vendas.entity.GrupoCliente;
import ritual.swing.ViewFrame;
import vendas.swing.model.ClienteGrupoModel;
import vendas.util.Constants;
import vendas.util.Messages;
import vendas.util.Reports;

/**
 *
 * @author  Sam
 */
public class GrupoClienteFrame extends ViewFrame {
    
    private ClienteDao clienteDao;
    private GrupoClienteDao grupoClienteDao;

    /** Creates new form NewJInternalFrame */
    public GrupoClienteFrame() {
        super();
        setTitle(getBundle().getString("grupoClientes"));
        initComponents();
    }
    
    public void init() {
        getLogger().info("init");
        try {
            grupoComboBox.setModel(new ListComboBoxModel(grupoClienteDao.findAll()));
        } catch(Exception e) {
            getLogger().error(getBundle().getString("findErrorMessage"), e);
            Messages.errorMessage(getBundle().getString("findErrorMessage"));
        }
        grupoComboBox.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                carregarClientes();
            }
        });
        refresh();
    }

    @Override
    public void refresh() {
        getLogger().info("refresh");
        grupoComboBox.setModel(new ListComboBoxModel(grupoClienteDao.findAll()));
        carregarClientes();
    }  
    
    private void carregarClientes() {
                GrupoCliente grupo = (GrupoCliente)grupoComboBox.getSelectedItem();
        Collection grupos = grupo.getClientes();
        ClienteGrupoModel clienteGrupoModel = new ClienteGrupoModel((List)grupos);
        clienteGrupoTable.setModel(clienteGrupoModel);
        TableColumn col = clienteGrupoTable.getColumnModel().getColumn(0);
        col.setPreferredWidth(200);
        clienteGrupoModel.fireTableDataChanged();
    }

    @Override
    public void report() {
        URL url = getClass().getResource(Constants.JRCLIENTESGRUPO);
        GrupoClienteDataSource ds = new GrupoClienteDataSource(grupoClienteDao.findAll());
        try {
            Reports.showReport(this.getTitle(), null, url, ds);
        } catch (Exception e) {
            getLogger().error(e.getMessage(), e);
            Messages.errorMessage(getBundle().getString("reportError"));
        }
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoComboBox = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        clienteGrupoTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMinimumSize(new java.awt.Dimension(668, 473));
        setName("Form"); // NOI18N

        grupoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        grupoComboBox.setName("grupoComboBox"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        clienteGrupoTable.setName("clienteGrupoTable"); // NOI18N
        jScrollPane2.setViewportView(clienteGrupoTable);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("grupoCliente")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(grupoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grupoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable clienteGrupoTable;
    private javax.swing.JComboBox grupoComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public ClienteDao getClienteDao() {
        return clienteDao;
    }

    public void setClienteDao(ClienteDao clienteDao) {
        this.clienteDao = clienteDao;
    }

    public GrupoClienteDao getGrupoClienteDao() {
        return grupoClienteDao;
    }

    public void setGrupoClienteDao(GrupoClienteDao grupoClienteDao) {
        this.grupoClienteDao = grupoClienteDao;
    }
    
}
