/*
 * ClienteVisitaPanel.java
 *
 * Created on 14 de Julho de 2007, 17:09
 */
package vendas.swing.app.cliente;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import ritual.swing.ListComboBoxModel;
import ritual.swing.TApplication;
import ritual.util.DateUtils;
import vendas.entity.Cliente;
import vendas.entity.Vendedor;
import vendas.entity.VisitaCliente;
import vendas.swing.core.EditPanel;

/**
 *
 * @author  Sam
 */
public class NaoVisitaPanel extends EditPanel {
    
    private ListComboBoxModel lista;

    /** Creates new form ClienteVisitaPanel */
    public NaoVisitaPanel() {
        initComponents();
        naoVisitaCheckBox.setSelected(Boolean.FALSE);
    }

    public Boolean getNaoVisita() {
        return naoVisitaCheckBox.isSelected();
    }

    public void setNaoVisita(Boolean naoVisita) {
        naoVisitaCheckBox.setSelected(naoVisita);
        naoVisitaCheckBox.setVisible(!naoVisita);
        clientePanel.setVisible(!naoVisita);
       dtVisitaField.setEnabled(!naoVisita);
    }

    public void disableDtVisita() {
        dtVisitaField.setEnabled(false);
    }

    public void setVendedores(List vendedores) {
        vendedorComboBox.setModel(new ListComboBoxModel(vendedores));
    }
    
    public void setClientes(List clientes) {
        clienteComboBox.setModel(new ListComboBoxModel(clientes));
    }

    @Override
    public void object2Field(Object obj) {
        VisitaCliente visitaCliente = (VisitaCliente) obj;
        dtVisitaField.setDate(DateUtils.getSimpleDate(visitaCliente.getDtVisita()));
        obsTextArea.setText(visitaCliente.getObs());
        vendedorComboBox.setSelectedItem(visitaCliente.getVendedor());
        clienteComboBox.setSelectedItem(visitaCliente.getCliente());
        
        if (visitaCliente.getListaClientes() == null) {
            lista = new ListComboBoxModel();
        } else {
            lista = new ListComboBoxModel(visitaCliente.getListaClientes());
        }
        
        clienteList.setModel(lista);
        
        if (visitaCliente.getVendedor() != null && visitaCliente.getVendedor().getIdVendedor() != null && !TApplication.getInstance().getUser().isAdmin()) {
            vendedorComboBox.setEditable(false);
            vendedorComboBox.setEnabled(false);
        }
        
        if (!naoVisitaCheckBox.isSelected()) {
            naoVisitaCheckBox.setSelected(visitaCliente.getTipoVisita().equals("N"));
        }
        
                
        clientePanel.setVisible(!naoVisitaCheckBox.isSelected());
       //dtVisitaField.setEnabled(!naoVisita);
        
    }
    
    public void habilitarCliente(boolean value) {
        clienteComboBox.setEnabled(value);
    }

    @Override
    public void field2Object(Object obj) {
        VisitaCliente visitaCliente = (VisitaCliente) obj;

        visitaCliente.setDtVisita(DateUtils.getSimpleDate(dtVisitaField.getDate()));
        Vendedor vendedor = (Vendedor) vendedorComboBox.getModel().getSelectedItem();
        visitaCliente.setVendedor(vendedor);
        visitaCliente.setObs(obsTextArea.getText());
        List<Cliente> clientes = new ArrayList<>();
        for (int i = 0; i < lista.getSize(); i++) {
            clientes.add((Cliente)lista.getElementAt(i));
        }
        visitaCliente.setListaClientes(clientes);
        visitaCliente.setVendedor(vendedor);
        visitaCliente.setTipoVisita(naoVisitaCheckBox.isSelected() ? "N" : "V");
    }

    @Override
    public boolean entryValidate() {
        Vendedor v = (Vendedor) vendedorComboBox.getModel().getSelectedItem();
        
        if (v == null || v.getIdVendedor() == null) {
            return false;
        }

        if (naoVisitaCheckBox.isSelected() && (obsTextArea.getText() == null || obsTextArea.getText().length() == 0)) {
            return false;
        } else if (!naoVisitaCheckBox.isSelected()) {
            if (lista.getSize() == 0) {
                return false;
            }
        }

        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dtVisitaField = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        vendedorComboBox = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        obsTextArea = new javax.swing.JTextArea();
        naoVisitaCheckBox = new javax.swing.JCheckBox();
        clientePanel = new javax.swing.JPanel();
        clienteComboBox = new javax.swing.JComboBox();
        addButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        clienteList = new javax.swing.JList();
        delButton = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("dtVisita")); // NOI18N

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("vendas/swing/app/cliente/Bundle"); // NOI18N
        dtVisitaField.setDateFormatString(bundle1.getString("NaoVisitaPanel.dtVisitaField.dateFormatString_1")); // NOI18N

        jLabel2.setText(bundle.getString("vendedor")); // NOI18N

        jLabel29.setText(bundle.getString("obs")); // NOI18N

        obsTextArea.setColumns(20);
        obsTextArea.setRows(5);
        jScrollPane1.setViewportView(obsTextArea);

        naoVisitaCheckBox.setText(bundle.getString("naoVisita")); // NOI18N
        naoVisitaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoVisitaCheckBoxActionPerformed(evt);
            }
        });

        clientePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle1.getString("NaoVisitaPanel.clientePanel.border.title"))); // NOI18N

        addButton.setText(bundle.getString("incluir")); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(clienteList);

        delButton.setText(bundle.getString("excluir")); // NOI18N
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clientePanelLayout = new javax.swing.GroupLayout(clientePanel);
        clientePanel.setLayout(clientePanelLayout);
        clientePanelLayout.setHorizontalGroup(
            clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(clientePanelLayout.createSequentialGroup()
                        .addComponent(clienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, clientePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        clientePanelLayout.setVerticalGroup(
            clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(clientePanelLayout.createSequentialGroup()
                        .addGroup(clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(delButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dtVisitaField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vendedorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(naoVisitaCheckBox))
                            .addComponent(jLabel29))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clientePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dtVisitaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vendedorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(naoVisitaCheckBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (clienteComboBox.getSelectedIndex() >= 0) {
            lista.addElement(clienteComboBox.getModel().getSelectedItem());
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        // TODO add your handling code here:
        int i = clienteList.getSelectedIndex();
        if (i >= 0)
        lista.removeElementAt(i);
    }//GEN-LAST:event_delButtonActionPerformed

    private void naoVisitaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoVisitaCheckBoxActionPerformed
        // TODO add your handling code here:
        JCheckBox value = (JCheckBox)evt.getSource();
        getLogger().info(value.isSelected());
        clientePanel.setVisible(!value.isSelected());
        this.invalidate();
    }//GEN-LAST:event_naoVisitaCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JComboBox clienteComboBox;
    private javax.swing.JList clienteList;
    private javax.swing.JPanel clientePanel;
    private javax.swing.JButton delButton;
    private com.toedter.calendar.JDateChooser dtVisitaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox naoVisitaCheckBox;
    private javax.swing.JTextArea obsTextArea;
    private javax.swing.JComboBox vendedorComboBox;
    // End of variables declaration//GEN-END:variables
}
