/*
 * ContatoEditPanel.java
 *
 * Created on 12 de Julho de 2007, 13:49
 */

package vendas.swing.app.cliente;

import ritual.swing.BoundedPlainDocument;
import ritual.swing.ListComboBoxModel;
import ritual.swing.TApplication;
import vendas.dao.ReferenciaDao;
import vendas.entity.Referencia;
import vendas.entity.ReferenciaCliente;
import vendas.swing.core.EditPanel;

/**
 *
 * @author  p993702
 */
public class RefComercialEditPanel extends EditPanel {
    
    /** Creates new form ContatoEditPanel */
    public RefComercialEditPanel() {
        initComponents();
        ReferenciaDao dao = (ReferenciaDao)TApplication.getInstance().lookupService("referenciaDao");
        try {
        referenciaComboBox.setModel(new ListComboBoxModel(dao.findAll()));
        } catch (Exception e) {
            e.printStackTrace();
        }    }

    @Override
    public void object2Field(Object obj) {
        ReferenciaCliente comprador = (ReferenciaCliente) obj;
        referenciaComboBox.setSelectedItem(comprador.getReferencia());
        fone1Field.setText(comprador.getFone1());
        fone2Field.setText(comprador.getFone2());
        emailField.setText(comprador.getEmail());
    }
    
    @Override
    public void field2Object(Object obj) {
        ReferenciaCliente comprador = (ReferenciaCliente) obj;
        Referencia banco = (Referencia)referenciaComboBox.getModel().getSelectedItem();
        comprador.setReferencia(banco);
        comprador.setFone1(fone1Field.getText());
        comprador.setFone2(fone2Field.getText());
        comprador.setEmail(emailField.getText());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fone1Field = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        fone2Field = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        emailField = new javax.swing.JFormattedTextField();
        referenciaComboBox = new javax.swing.JComboBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("nome")); // NOI18N

        jLabel2.setText(bundle.getString("fone1")); // NOI18N

        fone1Field.setDocument(new BoundedPlainDocument(30));

        jLabel3.setText(bundle.getString("fone2")); // NOI18N

        fone2Field.setDocument(new BoundedPlainDocument(30));

        jLabel5.setText(bundle.getString("email")); // NOI18N

        emailField.setColumns(30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(fone1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(fone2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel5))
                            .addGap(161, 161, 161))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(referenciaComboBox, 0, 407, Short.MAX_VALUE)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(referenciaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fone1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fone2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField emailField;
    private javax.swing.JFormattedTextField fone1Field;
    private javax.swing.JFormattedTextField fone2Field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox referenciaComboBox;
    // End of variables declaration//GEN-END:variables
    
}
