/*
 * ClienteSegmentoPanel.java
 *
 * Created on 14 de Julho de 2007, 11:27
 */

package vendas.swing.app.cliente;

import java.util.List;
import ritual.swing.ListComboBoxModel;
import vendas.entity.Transportador;
import vendas.swing.core.EditPanel;

/**
 *
 * @author  Sam
 */
public class RepresTranspPanel extends EditPanel {
    
    /** Creates new form ClienteSegmentoPanel */
    public RepresTranspPanel() {
        initComponents();
    }
    
    public void setTransportadores(List transp) {
        transpComboBox.setModel(new ListComboBoxModel(transp));
    }

    @Override
    public void field2Object(Object obj) {
        Transportador transportador = (Transportador)obj;
        Transportador value = (Transportador)transpComboBox.getModel().getSelectedItem();
        transportador.setIdTrans(value.getIdTrans());
        transportador.setNome(value.getNome());
        transportador.setCodTrans(value.getCodTrans());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        transpComboBox = new javax.swing.JComboBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("transportador")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transpComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transpComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox transpComboBox;
    // End of variables declaration//GEN-END:variables
    
}
