/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MetaView.java
 *
 * Created on Apr 14, 2011, 6:59:07 PM
 */
package vendas.swing.app.main;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import ritual.swing.FractionCellRenderer;
import ritual.swing.NumericPlainDocument;
import ritual.swing.TApplication;
import ritual.swing.ViewFrame;
import ritual.util.NumberUtils;
import vendas.dao.PedidoDao;
import vendas.entity.Meta;
import vendas.swing.model.MetaModel;
import vendas.util.Messages;

/**
 *
 * @author sam
 */
public class MetaView extends ViewFrame {
    
    MetaModel model;

    /** Creates new form MetaView */
    public MetaView(String title) {
        super(title);
        initComponents();
        init();
    }
    
    public MetaView() {
        super("Metas");
        initComponents();
        init();
    }
    
    public void init() {
               setTitle("Metas");
        DecimalFormat df = new DecimalFormat("#0.00");
        valorField.setDocument(new NumericPlainDocument(df));
        valorField.setValue(0);
        anoField.setDocument(new NumericPlainDocument(new DecimalFormat("#0")));
        initCampos(); 
        pack();
        load();
    }
    
    private void load() {
        PedidoDao dao = (PedidoDao) TApplication.getInstance().lookupService("pedidoDao");
        model = new MetaModel(dao.findMetas());
        model.setDao(dao);
        metaTable.setModel(model);
        metaTable.getColumnModel().getColumn(1).setCellRenderer(new FractionCellRenderer(8, 2, SwingConstants.RIGHT));
       model.fireTableDataChanged();
    }
    
    private void initCampos() {
        valorField.setText("");
        anoField.setText("");
    }

    @Override
    public void remove() {
        if (!TApplication.getInstance().isGrant("EXCLUIR_META"))
            return;
        int i = metaTable.getSelectedRow();
        if (i < 0) {
            Messages.warningMessage(getBundle().getString("selectOne"));
            return;
        }
        try {
            //PedidoDao dao = (PedidoDao) TApplication.getInstance().lookupService("pedidoDao");
           //dao.deleteRow(model.getObject(i));
            model.deleteRow(i);
        } catch (Exception e) {
            getLogger().error(e.getMessage(), e);
        }
    }
    
    

    @Override
    public void refresh() {
        load();
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new JLabel();
        mesComboBox = new JComboBox();
        jLabel4 = new JLabel();
        jScrollPane3 = new JScrollPane();
        metaTable = new JTable();
        jLabel6 = new JLabel();
        jButton2 = new JButton();
        anoField = new JFormattedTextField();
        valorField = new JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMinimumSize(new Dimension(150, 150));

        ResourceBundle bundle = ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel3.setText(bundle.getString("mes")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        mesComboBox.setEditable(true);
        mesComboBox.setModel(new DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        mesComboBox.setName("mesComboBox"); // NOI18N

        jLabel4.setText(bundle.getString("ano")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        metaTable.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        metaTable.setName("metaTable"); // NOI18N
        jScrollPane3.setViewportView(metaTable);

        jLabel6.setText(bundle.getString("valor")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jButton2.setText(bundle.getString("incluir")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        anoField.setText("jFormattedTextField1");
        anoField.setName("anoField"); // NOI18N

        valorField.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0.00"))));
        valorField.setName("valorField"); // NOI18N

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel4)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mesComboBox, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(anoField, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valorField, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane3, 0, 0, Short.MAX_VALUE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(jLabel3, Alignment.TRAILING)
                    .addComponent(jLabel4, Alignment.TRAILING)
                    .addComponent(jLabel6, Alignment.TRAILING))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(anoField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(valorField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addComponent(mesComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 394, GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (valorField.getValue() == null || (anoField.getText() == null || anoField.getText().length() < 4))
            return;
        Meta meta = new Meta();
        meta.setValorMeta(NumberUtils.getBigDecimal(valorField.getValue()));
        meta.setAnoMes(anoField.getText() + mesComboBox.getSelectedItem());
        PedidoDao dao = (PedidoDao) TApplication.getInstance().lookupService("pedidoDao");
        try {
            if (dao.findById(Meta.class, meta.getAnoMes()) == null) {
                if (!TApplication.getInstance().isGrant("INCLUIR_META"))
                    return;
                dao.insertRecord(meta);
                model.addObject(meta);
            }
            else {
                if (!TApplication.getInstance().isGrant("ALTERAR_META"))
                    return;
                dao.updateRow(meta);
                model.updateRow(meta);
            }
            model.fireTableDataChanged(); 
            initCampos();
        } catch (Exception e) {
            getLogger().error(e.getMessage(), e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JFormattedTextField anoField;
    private JButton jButton2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel6;
    private JScrollPane jScrollPane3;
    private JComboBox mesComboBox;
    private JTable metaTable;
    private JFormattedTextField valorField;
    // End of variables declaration//GEN-END:variables
}
