/*
 * FilterFrame.java
 *
 * Created on 21 de Janeiro de 2008, 15:14
 */

package vendas.swing.core;

import ritual.swing.BaseFrame;
import java.awt.BorderLayout;
import ritual.swing.MDIDesktopPane;
import vendas.beans.FilterBean;
import ritual.swing.TApplication;
import vendas.util.Messages;

/**
 *
 * @author  Sam
 */
public class FilterFrame extends BaseFrame {
    
    private MDIDesktopPane dskpnl;
    private EditPanel editPanel;
    private FilterBean filterObject;
    
    /** Creates new form FilterFrame */
    public FilterFrame() {
        initComponents();
        pack();
    }
    
    public FilterFrame(String title, MDIDesktopPane dskpnl, EditPanel panel) {
        super(title);
        this.dskpnl = dskpnl;
        editPanel = panel;
        initComponents();
        getContentPane().add(panel, BorderLayout.CENTER);
        pack();
    }

    public EditPanel getEditPanel() {
        return editPanel;
    }

    public void setEditPanel(EditPanel editPanel) {
        this.editPanel = editPanel;
        getContentPane().add(editPanel, BorderLayout.CENTER);
        pack();
    }
    
    public void setFilterObject(FilterBean filter) {
        filterObject = filter;
    }
    
    public FilterBean getFilterObject() {
        return filterObject;
    }
    
    public void execute() {
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        confirmButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        confirmButton.setText(bundle.getString("confirmar")); // NOI18N
        confirmButton.setName("confirmButton"); // NOI18N
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(confirmButton)
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(confirmButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        if (editPanel.entryValidate()) {
            editPanel.field2Object(filterObject);
            execute();
        } else
            Messages.errorMessage(TApplication.getInstance().getResourceString("dadosInvalidos"));
    }//GEN-LAST:event_confirmButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
