/*
 * EditarCompromissoPanel.java
 *
 * Created on November 19, 2006, 4:20 PM
 */
package vendas.swing.app.contas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.List;
import ritual.swing.ListComboBoxModel;
import ritual.swing.NumericPlainDocument;
import ritual.util.DateUtils;
import ritual.util.NumberUtils;
import vendas.dao.TipoPgtoFinanceiroDao;
import vendas.entity.Compromisso;
import vendas.entity.Conta;
import vendas.entity.TipoPgtoFinanceiro;
import vendas.swing.core.EditPanel;

/**
 *
 * @author  jaime
 */
public class CompromissoEditPanel extends EditPanel {

    /** Creates new form EditarCompromissoPanel */
    public CompromissoEditPanel() {
        initComponents();
        init();
    }

    public void setFornecedorLabel(String value) {
        this.jLabel3.setText(value);
    }

    @Override
    public void init() {
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent ce) {
                        dtVencimentoField.requestFocusInWindow();
                    }
            });
        contaComboBox.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Conta conta = (Conta) contaComboBox.getModel().getSelectedItem();
                if (conta != null && conta.getContaMaster() != null)
                    grupoField.setText(conta.getContaMaster().getNome());
            }
        });
                DecimalFormat df = new DecimalFormat("#0.00");
        valorField.setDocument(new NumericPlainDocument(df));
    }
    
    public void loadTipoPgto(List tipos) {
        try {
            TipoPgtoFinanceiroDao tp = new TipoPgtoFinanceiroDao();
            tipoPgtoComboBox.setModel(new ListComboBoxModel(tipos));
        } catch (Exception e) {
            e.printStackTrace();
        }        
    }

    public void loadPlano(List contas) {
        contaComboBox.setModel(new ListComboBoxModel(contas));
    }

    @Override
    public void object2Field(Object obj) {
        Compromisso compromisso = (Compromisso) obj;
        dtVencimentoField.setDate(DateUtils.parse(DateUtils.format(compromisso.getDtVencimento())));
        if (compromisso.getDtPgto() != null) {
            dtPgtoField.setDate(DateUtils.parse(DateUtils.format(compromisso.getDtPgto())));
        }
        valorField.setValue(NumberUtils.getBigDecimal(compromisso.getValor()));
        contaComboBox.setSelectedItem(compromisso.getConta());
        tipoPgtoComboBox.setSelectedItem(compromisso.getTipoPgtoFinanceiro());
        textArea.setText(compromisso.getObservacao());
    }
    
    public Date getDtVencimento() {
        return dtVencimentoField.getDate();
    }
    public BigDecimal getValor() {
        return (BigDecimal)valorField.getValue();
    }
    public Conta getConta() {
        return (Conta)contaComboBox.getModel().getSelectedItem();
    }
    public TipoPgtoFinanceiro getTipoPgto() {
        return (TipoPgtoFinanceiro)tipoPgtoComboBox.getModel().getSelectedItem();
    }

    @Override
    public void field2Object(Object obj) {
        Compromisso compromisso = (Compromisso) obj;
        compromisso.setValor(NumberUtils.getBigDecimal(valorField.getValue()));
        compromisso.setObservacao(textArea.getText());
        compromisso.setConta((Conta) contaComboBox.getModel().getSelectedItem());
        compromisso.setTipoPgto((TipoPgtoFinanceiro) tipoPgtoComboBox.getModel().getSelectedItem());
        compromisso.setDtVencimento(dtVencimentoField.getDate());
        compromisso.setDtPgto(dtPgtoField.getDate());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dtVencimentoField = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        valorField = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contaComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        tipoPgtoComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        dtPgtoField = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        grupoField = new javax.swing.JFormattedTextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("dtVencimento")); // NOI18N

        dtVencimentoField.setDateFormatString("dd/MM/yyyy"); // NOI18N

        jLabel2.setText(bundle.getString("valor")); // NOI18N

        valorField.setColumns(10);
        valorField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        valorField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel7.setText(bundle.getString("grupo")); // NOI18N

        jLabel3.setText(bundle.getString("compromisso")); // NOI18N

        contaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText(bundle.getString("tpPgto")); // NOI18N

        tipoPgtoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText(bundle.getString("dtPgto")); // NOI18N

        dtPgtoField.setDateFormatString("dd/MM/yyyy"); // NOI18N

        jLabel6.setText(bundle.getString("observacao")); // NOI18N

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        grupoField.setColumns(10);
        grupoField.setEditable(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2)
                            .add(jLabel7)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(contaComboBox, 0, 242, Short.MAX_VALUE)
                            .add(valorField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .add(dtVencimentoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(grupoField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jLabel5)
                            .add(jLabel6))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .add(tipoPgtoComboBox, 0, 245, Short.MAX_VALUE)
                            .add(dtPgtoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 154, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel1)
                    .add(dtVencimentoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(valorField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(contaComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(grupoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tipoPgtoComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel5)
                        .add(20, 20, 20)
                        .add(jLabel6))
                    .add(layout.createSequentialGroup()
                        .add(dtPgtoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox contaComboBox;
    private com.toedter.calendar.JDateChooser dtPgtoField;
    private com.toedter.calendar.JDateChooser dtVencimentoField;
    private javax.swing.JFormattedTextField grupoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    private javax.swing.JComboBox tipoPgtoComboBox;
    private javax.swing.JFormattedTextField valorField;
    // End of variables declaration//GEN-END:variables

}
