/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CompromissoFilterPanel.java
 *
 * Created on Mar 5, 2011, 11:21:39 AM
 */
package vendas.swing.app.contas;

import java.text.SimpleDateFormat;
import java.util.Date;
import ritual.swing.ListComboBoxModel;
import ritual.util.DateUtils;
import vendas.beans.CompromissoFilter;
import vendas.entity.Conta;
import vendas.swing.core.EditPanel;

/**
 *
 * @author sam
 */
public class CompromissoFilterPanel extends EditPanel {

    /** Creates new form CompromissoFilterPanel */
    public CompromissoFilterPanel() {
        initComponents();
    }

    @Override
    public void object2Field(Object obj) {
        CompromissoFilter filter = (CompromissoFilter) obj;
    }

    @Override
    public void field2Object(Object obj) {
        CompromissoFilter filter = (CompromissoFilter) obj;
        filter.setConta((Conta) contaCombo.getModel().getSelectedItem());
        filter.setGrupo((Conta) grupoCombo.getModel().getSelectedItem());
        
        try {
            if (dtEndField.getDate() != null) {
                filter.setDtEnd(DateUtils.parse(DateUtils.format(dtEndField.getDate())));
                filter.setDtIni(DateUtils.parse(DateUtils.format(dtIniField.getDate())));
            }
            if (dtIniPgtoField.getDate() != null) {
            String s = new SimpleDateFormat("dd/MM/yyyy 23:59:59").format(dtEndPgtoField.getDate()); 
            Date d = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").parse(s);  
            filter.setDtEndPgto(d);
            s = new SimpleDateFormat("dd/MM/yyyy 00:00:00").format(dtIniPgtoField.getDate());  
            d = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").parse(s);  
            filter.setDtIniPgto(d);
            }
        } catch (Exception e) {
             e.printStackTrace();
        }

        if (todosRadio.isSelected()) {
            filter.setSituacao(0);
        }
        if (pendentesRadio.isSelected()) {
            filter.setSituacao(1);
        }
        if (pagosRadio.isSelected()) {
            filter.setSituacao(2);
        }

        StringBuilder filterTitle = new StringBuilder();

        if (dtIniField.getDate() != null) {
            filterTitle.append(getBundle().getString("vencimentosIni"));
            filterTitle.append(" ");
            filterTitle.append(DateUtils.format(dtIniField.getDate()));
            filterTitle.append(getBundle().getString("para"));
            filterTitle.append(DateUtils.format(dtEndField.getDate()));
            filterTitle.append(". ");
        }
        if (pendentesRadio.isSelected()) {
            filterTitle.append(getBundle().getString("pendentes"));
            filterTitle.append(". ");
        }
        if (pagosRadio.isSelected()) {
            filterTitle.append(getBundle().getString("pagos"));
            filterTitle.append(". ");
        }
        filter.setTitle(filterTitle.toString());
    }

    public void setContas(ListComboBoxModel lista) {
        contaCombo.setModel(lista);
    }
    public void setGrupo(ListComboBoxModel lista) {
        grupoCombo.setModel(lista);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        dtIniField = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        dtEndField = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        todosRadio = new javax.swing.JRadioButton();
        pendentesRadio = new javax.swing.JRadioButton();
        pagosRadio = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        dtIniPgtoField = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        dtEndPgtoField = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        contaCombo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        grupoCombo = new javax.swing.JComboBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("vencimentos")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        dtIniField.setDateFormatString("dd/MM/yyyy"); // NOI18N
        dtIniField.setName("dtIniField"); // NOI18N

        jLabel2.setText(bundle.getString("para")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        dtEndField.setDateFormatString("dd/MM/yyyy"); // NOI18N
        dtEndField.setName("dtEndField"); // NOI18N

        jLabel3.setText(bundle.getString("situacao")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        buttonGroup1.add(todosRadio);
        todosRadio.setSelected(true);
        todosRadio.setText(bundle.getString("all")); // NOI18N
        todosRadio.setName("todosRadio"); // NOI18N

        buttonGroup1.add(pendentesRadio);
        pendentesRadio.setText(bundle.getString("pendentes")); // NOI18N
        pendentesRadio.setName("pendentesRadio"); // NOI18N

        buttonGroup1.add(pagosRadio);
        pagosRadio.setText(bundle.getString("pagos")); // NOI18N
        pagosRadio.setName("pagosRadio"); // NOI18N

        jLabel5.setText(bundle.getString("pagamentos")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        dtIniPgtoField.setDateFormatString("dd/MM/yyyy"); // NOI18N
        dtIniPgtoField.setName("dtIniPgtoField"); // NOI18N

        jLabel6.setText(bundle.getString("para")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        dtEndPgtoField.setDateFormatString("dd/MM/yyyy"); // NOI18N
        dtEndPgtoField.setName("dtEndPgtoField"); // NOI18N

        jLabel4.setText(bundle.getString("compromisso")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        contaCombo.setName("contaCombo"); // NOI18N

        jLabel8.setText(bundle.getString("grupo")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        grupoCombo.setName("grupoCombo"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel5)
                            .add(dtIniPgtoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 135, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(dtEndPgtoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 135, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(dtIniField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 135, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(dtEndField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 135, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(todosRadio)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(pendentesRadio)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(pagosRadio))
                            .add(jLabel3)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(contaCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 289, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel4))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel8)
                            .add(grupoCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 289, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(dtEndField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel2)
                                .add(todosRadio)
                                .add(pendentesRadio)
                                .add(pagosRadio))
                            .add(dtIniField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(dtEndPgtoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel6)
                            .add(dtIniPgtoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jLabel8))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(contaCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(grupoCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox contaCombo;
    private com.toedter.calendar.JDateChooser dtEndField;
    private com.toedter.calendar.JDateChooser dtEndPgtoField;
    private com.toedter.calendar.JDateChooser dtIniField;
    private com.toedter.calendar.JDateChooser dtIniPgtoField;
    private javax.swing.JComboBox grupoCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton pagosRadio;
    private javax.swing.JRadioButton pendentesRadio;
    private javax.swing.JRadioButton todosRadio;
    // End of variables declaration//GEN-END:variables
}
