/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendas.swing.app.contas;

import java.text.DecimalFormat;
import javax.swing.JFormattedTextField;
import ritual.swing.BoundedPlainDocument;
import ritual.swing.NumericPlainDocument;
import ritual.util.DateUtils;
import ritual.util.DateVerifier;
import ritual.util.NumberUtils;
import vendas.entity.Contabil;
import vendas.swing.core.EditPanel;

/**
 *
 * @author jaimeoliveira
 */
public class Contabil3EditPanel extends EditPanel {

    /**
     * Creates new form Contabil3EditPanel
     */
    public Contabil3EditPanel() {
        initComponents();
        valorField.setInputVerifier(new DateVerifier(true));
        valorField.setDocument(new NumericPlainDocument(new DecimalFormat("#0.00")));
    }
    
        @Override
    public void object2Field(Object obj) {
        Contabil contabil = (Contabil) obj;
        descTextField.setText(contabil.getDescricao());
        dtEventoField.setDate(contabil.getDtVencimento());
        valorField.setValue(contabil.getValor());
    }

    @Override
    public void field2Object(Object obj) {
        Contabil contabil = (Contabil) obj;
        contabil.setDescricao(descTextField.getText());
        contabil.setDtVencimento(DateUtils.parse(DateUtils.format(dtEventoField.getDate())));
        contabil.setValor(NumberUtils.getBigDecimal(valorField.getValue()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dtEventoField = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        valorField = new javax.swing.JFormattedTextField();
        descTextField = new javax.swing.JFormattedTextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("compromisso")); // NOI18N

        jLabel3.setText(bundle.getString("valor")); // NOI18N

        dtEventoField.setDateFormatString("dd/MM/yyyy");

        jLabel5.setText(bundle.getString("dtVencimento")); // NOI18N

        valorField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        valorField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                valorFieldFocusLost(evt);
            }
        });

        descTextField.setColumns(50);
        descTextField.setDocument(new BoundedPlainDocument(50));
        descTextField.setText("jFormattedTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(dtEventoField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 234, Short.MAX_VALUE))
                    .addComponent(descTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtEventoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void valorFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorFieldFocusLost
        // TODO add your handling code here:
        JFormattedTextField f = (JFormattedTextField) evt.getComponent();
        if (f.getText() == null || f.getText().length() == 0)
        f.setValue(null);
    }//GEN-LAST:event_valorFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField descTextField;
    private com.toedter.calendar.JDateChooser dtEventoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JFormattedTextField valorField;
    // End of variables declaration//GEN-END:variables
}
