/*
 * ContaEditPanel.java
 *
 * Created on 4 de Novembro de 2007, 17:36
 */
package vendas.swing.app.contas;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import ritual.swing.BoundedPlainDocument;
import vendas.entity.ContaFluxo;
import vendas.swing.core.EditPanel;

/**
 *
 * @author  Sam
 */
public class ContaEditPanel extends EditPanel {

    /** 
     * Creates new form ContaEditPanel 
     */
    public ContaEditPanel() {
        initComponents();
        addComponentListener(new ComponentAdapter() {
                    @Override
                    public void componentShown(ComponentEvent ce) {
                        nomeField.requestFocusInWindow();
                    }
                });
    }

    public void setNome(String value) {
        nomeField.setText(value);
    }

    public String getNome() {
        String value = nomeField.getText();
        return value;
    }
    
        @Override
    public void object2Field(Object obj) {
        ContaFluxo tipo = (ContaFluxo) obj;
        setNome(tipo.getNome());
        contaCheckBox.setSelected("S".equals(tipo.getIndicaContaBancaria()));
    }

    @Override
    public void field2Object(Object obj) {
        ContaFluxo tipo = (ContaFluxo) obj;
        tipo.setNome(getNome());
        
        if (contaCheckBox.isSelected())
           tipo.setIndicaContaBancaria("S");
        else
           tipo.setIndicaContaBancaria("N");
    }

    @Override
    public boolean entryValidate() {
        return getNome() != null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeField = new javax.swing.JFormattedTextField();
        contaCheckBox = new javax.swing.JCheckBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("nome")); // NOI18N

        nomeField.setColumns(40);
        nomeField.setDocument(new BoundedPlainDocument(40));

        contaCheckBox.setText("E uma conta bancaria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(contaCheckBox)
                        .addContainerGap(119, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeField, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contaCheckBox)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox contaCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField nomeField;
    // End of variables declaration                   

}
