/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MovimentoFilterPanel.java
 *
 * Created on Mar 5, 2011, 11:21:39 AM
 */
package vendas.swing.app.contas;

import ritual.swing.ListComboBoxModel;
import ritual.swing.TApplication;
import ritual.util.DateUtils;
import vendas.beans.MovimentoFilter;
import vendas.dao.GrupoMovimentoDao;
import vendas.entity.GrupoMovimento;
import vendas.swing.core.EditPanel;

/**
 *
 * @author sam
 */
public class MovimentoFilterPanel extends EditPanel {

    /** Creates new form MovimentoFilterPanel */
    public MovimentoFilterPanel() {
        initComponents();
    }

    @Override
    public void object2Field(Object obj) {
        MovimentoFilter filter = (MovimentoFilter) obj;
        dtEndField.setDate(filter.getDtTermino());
        dtIniField.setDate(filter.getDtInicio());
        
        GrupoMovimentoDao grupoDao = new GrupoMovimentoDao();
        
        try {
            TApplication app = TApplication.getInstance();
            grupoComboBox.setModel(new ListComboBoxModel(grupoDao.findByExample(app.getUser().getIdvendedor())));
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        grupoComboBox.setSelectedItem(null);
    }  

    @Override
    public void field2Object(Object obj) {
        MovimentoFilter filter = (MovimentoFilter) obj;
        
        try {
            if (dtEndField.getDate() != null && dtIniField.getDate() != null) {
                filter.setDtTermino(DateUtils.parse(DateUtils.format(dtEndField.getDate())));
                filter.setDtInicio(DateUtils.parse(DateUtils.format(dtIniField.getDate())));
                filter.setGrupo((GrupoMovimento)grupoComboBox.getSelectedItem());
                StringBuilder sb = new StringBuilder();
                sb.append(DateUtils.format(filter.getDtInicio())).append(" - ").append(DateUtils.format(filter.getDtTermino()));
                filter.setTitle(sb.toString());
            } else if (dtIniField.getDate() != null) {
                
            }
        } catch (Exception e) {
             e.printStackTrace();
        }

        if (todosRadio.isSelected()) {
            filter.setTipo(-1);
        }
        if (debitoRadio.isSelected()) {
            filter.setTipo(0);
            filter.addTitle("Somente débitos");
        }
        if (creditoRadio.isSelected()) {
            filter.setTipo(1);
                        filter.addTitle("Somente créditos");
        }

    }

    public void habilitaGrupo(boolean habilita) {
        jLabel4.setVisible(habilita);
        grupoComboBox.setVisible(habilita);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        dtIniField = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        dtEndField = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        todosRadio = new javax.swing.JRadioButton();
        debitoRadio = new javax.swing.JRadioButton();
        creditoRadio = new javax.swing.JRadioButton();
        grupoComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("data")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        dtIniField.setName("dtIniField"); // NOI18N

        jLabel2.setText(bundle.getString("para")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        dtEndField.setName("dtEndField"); // NOI18N

        jLabel3.setText(bundle.getString("tipo")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        buttonGroup1.add(todosRadio);
        todosRadio.setSelected(true);
        todosRadio.setText(bundle.getString("all")); // NOI18N
        todosRadio.setName("todosRadio"); // NOI18N

        buttonGroup1.add(debitoRadio);
        debitoRadio.setText(bundle.getString("debito")); // NOI18N
        debitoRadio.setName("debitoRadio"); // NOI18N

        buttonGroup1.add(creditoRadio);
        creditoRadio.setText(bundle.getString("credito")); // NOI18N
        creditoRadio.setName("creditoRadio"); // NOI18N

        grupoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        grupoComboBox.setName("grupoComboBox"); // NOI18N

        jLabel4.setText(bundle.getString("grupo")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, grupoComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel1)
                                    .add(dtIniField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 135, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(dtEndField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 135, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(todosRadio)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(debitoRadio)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(creditoRadio))
                            .add(jLabel3))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(dtEndField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel2)
                                .add(todosRadio)
                                .add(debitoRadio)
                                .add(creditoRadio))
                            .add(dtIniField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4)
                .add(11, 11, 11)
                .add(grupoComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton creditoRadio;
    private javax.swing.JRadioButton debitoRadio;
    private com.toedter.calendar.JDateChooser dtEndField;
    private com.toedter.calendar.JDateChooser dtIniField;
    private javax.swing.JComboBox<String> grupoComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton todosRadio;
    // End of variables declaration//GEN-END:variables
}
