connect /Users/sam/Databases/vendas.fdb user "sysdba" password "masterkey";

./gbak -backup /Users/sam/Databases/contas.fdb /Users/sam/Databases/contas.bkp -y /Users/sam/Databases/contas.log -v -user sysdba -pas masterkey
./gbak -replace /Users/sam/Databases/contas.bkp /Users/sam/Databases/contas.fdb -v -user sysdba -pas masterkey

create table TBPENDENCIA (
    IDPENDENCIA INTEGER NOT NULL,
    DTINCLUSAO TIMESTAMP NOT NULL,
    DTALTERACAO TIMESTAMP,
    USERNAME VARCHAR(20) NOT NULL,
    DSPENDENCIA varchar(1024) not null,
    inresolvido char(1) default 'N' not null,
    primary key (idpendencia)
)

CREATE SEQUENCE TBPENDENCIA_IDPENDENCIA_SEQ;

CREATE INDEX IDXPENDENCIA1 ON TBPENDENCIA(DTINCLUSAO);
CREATE INDEX IDXPENDENCIA2 ON TBPENDENCIA(USERNAME);

CREATE TABLE TBCLIENTEGRUPO (
   IDGRPCLIENTE INTEGER NOT NULL,
   IDCLIENTE INTEGER NOT NULL,
   PRIMARY KEY (IDCLIENTE, IDGRPCLIENTE)
);

INSERT INTO TBCLIENTEGRUPO
SELECT g.GRUPO_CLIENTE, g.CLIENTE FROM CLIENTE_GRUPO g, cliente c
where g.cliente = c.cliente;

CREATE TABLE TBUSER (
    USERNAME VARCHAR(20) NOT NULL,
    PASSWD VARCHAR(100),
    NAMEDESC VARCHAR(40),
    EMAIL VARCHAR(100),
    EMAILPASSWD VARCHAR(100),
    perfil varchar(20),
    port int,
    IDVENDEDOR INT,
    serverName varchar(100),
    assinatura BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    PRIMARY KEY (iduser)
);

create table tbagenda (
   IDAGENDA integer not null,
   USERNAME VARCHAR(20) NOT NULL,
   dtevento TIMESTAMP not null,
   descricao BLOB SUB_TYPE 1 SEGMENT SIZE 80 not null,
   primary key (idagenda)
);

CREATE INDEX IDXAGENDA1 ON TBagenda(username, DTEVENTO);

CREATE TABLE TBMENSAGEM (
   IDMENSAGEM INTEGER not null,
   TITULO VARCHAR(50) NOT NULL,
   MENSAGEM BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   TIPO CHAR(1),
   PRIMARY KEY (IDMENSAGEM)
);

create table Tbmeta (
    anomes char(6) not null,
    valorMeta numeric(10,2) not null,
    primary key (anomes)
)


INSERT INTO TBMENSAGEM SELECT ID, TITULO, MENSAGEM, TIPO FROM MENSAGEM;

CREATE TABLE TBPARAMS (
   ID INT NOT NULL,
   RAZAO VARCHAR(50) NOT NULL,
   FANTASIA VARCHAR(50),
   ENDERECO VARCHAR(40),
   CIDADE VARCHAR(30),
   BAIRRO VARCHAR(25),
   CEP VARCHAR(8),
   UF VARCHAR(2),
   ENDERECOMAIL VARCHAR(100),
   CIDADEMAIL VARCHAR(40),
   BAIRROMAIL VARCHAR(40),
   CEPMAIL VARCHAR(8),
   UFMAIL VARCHAR(2),
   CGC VARCHAR(14),
   INSEST VARCHAR(18),
   FONE VARCHAR(36),
   FONE2 VARCHAR(36),
   FAX VARCHAR(12),
   EMAIL VARCHAR(50),
   SERVIDOR VARCHAR(50),
   CXPOSTAL VARCHAR(15),
   PROMOCAO BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   EMAILMSG BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   EMAILMSGCOBRANCA BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   EMAILMSGCLIENTE BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   MSGANIVERSARIO BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   arquivo BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   PRIMARY KEY (ID)
);

INSERT INTO TBPARAMS
SELECT -1, RAZAO, FANTASIA, ENDERECO, CIDADE, BAIRRO, CEP, UF, CGC, 
INSEST, FONE, FAX, EMAIL, SERVIDOR, CXPOSTAL, PROMOCAO, EMAILMSG FROM PARAMS;

CREATE TABLE TBBANCO (
   IDBANCO VARCHAR(3) NOT NULL,
   NOME VARCHAR(25) NOT NULL,
   PRIMARY KEY (IDBANCO)
);

CREATE INDEX IDXBANCO1 ON TBBANCO(NOME);

INSERT INTO TBBANCO SELECT BANCO, NOME FROM BANCO;

commit;

CREATE TABLE TBCONTA (
   IDCONTA INTEGER NOT NULL,
   IDBANCO VARCHAR(3),
   AGENCIA VARCHAR(10),
   CCORRENTE VARCHAR(10),
   PRIMARY KEY (IDCONTA)
);

ALTER TABLE TBCONTA ADD CONSTRAINT FKCONTA1 FOREIGN KEY (IDBANCO) 
REFERENCES TBBANCO(IDBANCO);

insert into tbconta
select num_conta_repres, numbanco, numagencia, numconta from 
conta_empresa;
   
CREATE TABLE TBVENDEDOR (
   IDVENDEDOR INTEGER NOT NULL,
   NOME VARCHAR(40) NOT NULL,
   ENDERECO VARCHAR(40),
   BAIRRO VARCHAR(30),
   CIDADE VARCHAR(30),
   CEP VARCHAR(8),
   UF VARCHAR(2),
   COMISSAO VARCHAR(1),
   FONE1 VARCHAR(12),
   FONE2 VARCHAR(12),
   VALCOMISSAO NUMERIC(5,2),
   ANIVERSARIO CHAR(4),
   SIGLA VARCHAR(3),
   PRIMARY KEY (IDVENDEDOR)
);

INSERT INTO TBVENDEDOR
SELECT VENDEDOR, NOME, ENDERECO, BAIRRO, CIDADE, CEP, UF, COMISSAO, 
FONE1, FONE2, VALCOMISSAO FROM VENDEDOR;

CREATE TABLE TBSITCLIENTE (
   IDSITCLIENTE INTEGER not null,
   NOME VARCHAR(30) NOT NULL,
   PEDIDO CHAR(1) NOT NULL,
   PRIMARY KEY (IDSITCLIENTE)
);

INSERT INTO TBSITCLIENTE SELECT NUM_SITUACAO, NOME, PEDIDO FROM 
SITUACAO_CLIENTE;

CREATE TABLE TBSEGMERCADO (
   IDSEGMENTO INTEGER not null,
   NOME VARCHAR(30) NOT NULL,
   PRIMARY KEY (IDSEGMENTO)
);

INSERT INTO TBSEGMERCADO SELECT SEGMENTO, NOME FROM SEGMENTO_MERCADO;
commit;

CREATE TABLE TBREFERENCIA (
   IDREFERENCIA INTEGER not null,
   NOME VARCHAR(100) NOT NULL,
   FONE VARCHAR(20) NOT NULL,
   PRIMARY KEY (IDREFERENCIA)
);

CREATE TABLE TBFORMAVENDA (
   IDFORMAVENDA INTEGER not null,
   NOME VARCHAR(30) NOT NULL,
   PRIMARY KEY (IDFORMAVENDA)
);


CREATE TABLE TBGRUPOCLIENTE (
   IDGRPCLIENTE INTEGER NOT NULL,
   NOMEGRUPO VARCHAR(40) NOT NULL,
   PRIMARY KEY (IDGRPCLIENTE)
);

INSERT INTO TBGRUPOCLIENTE SELECT GRUPO_CLIENTE, NOME_GRUPO FROM 
GRUPO_CLIENTE;

commit;

create table tbcorreio (
   idmensagem int not null,
   idorigem varchar(15) not null,
   iddestino varchar(15) not null,
   dataenvio timestamp not null,
   dataleitura timestamp,
   mensagem blob SUB_TYPE 1 SEGMENT SIZE 80 not null,
   mensagemlida char not null,
   primary key (idmensagem)
);

CREATE TABLE TBCLIENTE (
   IDCLIENTE INTEGER  NOT NULL,
   BLOQUEADO CHAR(1) NOT NULL,
   RAZAO VARCHAR(50) NOT NULL,
   FANTASIA VARCHAR(30),
   site varchar(100),
   idTipo int;
   ENDERECO VARCHAR(60),
   BAIRRO VARCHAR(25),
   CIDADE VARCHAR(30),
   CEP VARCHAR(8),
   UF VARCHAR(2),
   CGC VARCHAR(14),
   INSEST VARCHAR(18),
   FONE1 VARCHAR(12),
   FONE2 VARCHAR(12),
   FONE3 VARCHAR(12),
   FAX VARCHAR(12),
   DTINCLUS TIMESTAMP,
   DTCANCEL TIMESTAMP,
   IDVENDEDOR INTEGER,
   COBRANCA VARCHAR(50),
   IDSITCLIENTE INTEGER not null,
   PGANTECIPADO char(1),
   EMPILHADEIRA char(1),
   entregarboleto char(1),
   IDGRUPOCLIENTE INTEGER,
   limitecredito numeric(10,2),
   numdiasatraso numeric(10,2),
   FOTO BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   HISTORICO BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   PRIMARY KEY (IDCLIENTE)
);
commit;

CREATE INDEX IDXCLIENTE1 ON TBCLIENTE(RAZAO);
CREATE INDEX IDXCLIENTE2 ON TBCLIENTE(IDSITCLIENTE);
CREATE INDEX IDXCLIENTE3 ON TBCLIENTE(CIDADE);
CREATE INDEX IDXCLIENTE4 ON TBCLIENTE(DTINCLUS);

ALTER TABLE TBCLIENTE ADD CONSTRAINT FKCLIENTE1 FOREIGN KEY (IDVENDEDOR) 
    REFERENCES TBVENDEDOR(IDVENDEDOR);
ALTER TABLE TBCLIENTE ADD CONSTRAINT FKCLIENTE2 FOREIGN KEY (IDSITCLIENTE)
    REFERENCES TBSITCLIENTE (IDSITCLIENTE);
ALTER TABLE TBCLIENTE ADD CONSTRAINT FKCLIENTE3 FOREIGN KEY (IDGRUPOCLIENTE)
    REFERENCES TBGRUPOCLIENTE (IDGRPCLIENTE);

UPDATE CLIENTE SET CLIENTE.VENDEDOR = 1 WHERE
    CLIENTE.VENDEDOR NOT IN (SELECT VENDEDOR.VENDEDOR FROM VENDEDOR);
UPDATE CLIENTE SET CLIENTE.EMPILHADEIRA = '0' WHERE
    CLIENTE.EMPILHADEIRA IS NULL;

CREATE TABLE TBREFERENCIACLIENTE (
   IDREFERENCIACLIENTE INTEGER NOT NULL,
   IDREFERENCIA INTEGER NOT NULL,
   IDCLIENTE INTEGER  NOT NULL,
   FONE1 VARCHAR(12),
   FONE2 VARCHAR(12),
   FAX VARCHAR(12),
   EMAIL VARCHAR(100),
   PRIMARY KEY (IDREFERENCIACLIENTE)
);

alter table tbreferenciacliente add constraint fkreferenciacliente1 foreign key (idcliente) references tbcliente (idcliente);
alter table tbreferenciacliente add constraint fkreferenciacliente2 foreign key (idreferencia) references tbreferencia (idreferencia);

CREATE TABLE TBBANCOREFCLIENTE (
   IDREFERENCIA INTEGER NOT NULL,
   IDCLIENTE INTEGER  NOT NULL,
   IDBANCO VARCHAR(3) NOT NULL,
   CONTA VARCHAR(20),
   AGENCIA VARCHAR(10),
   PRIMARY KEY (IDREFERENCIA)
);

alter table TBBANCOREFCLIENTE add constraint fkrefBANCOcliente1 foreign key (idcliente) references tbcliente (idcliente);
alter table TBBANCOREFCLIENTE add constraint fkrefBANCOcliente2 foreign key (idbanco) references tbbanco (idbanco);

commit;

INSERT INTO TBCLIENTE
SELECT CLIENTE, RAZAO, FANTASIA, ENDERECO, BAIRRO, CIDADE, CEP, UF, CGC, 
INSEST, FONE1, FONE2, FONE3, FAX, DTINCLUS, DTCANCEL,
  VENDEDOR, COBRANCA, NUM_SITUACAO, EMPILHADEIRA, NULL FROM CLIENTE;
commit;

CREATE TABLE TBCLIENTECONTATO (
   IDCLIENTE INTEGER  NOT NULL,
   TIPO CHAR(1) NOT NULL,
   NUMITEM INTEGER NOT NULL,
   ENDERECO VARCHAR(50),
   PRIMARY KEY (IDCLIENTE, TIPO, NUMITEM)
);

ALTER TABLE TBCLIENTECONTATO ADD CONSTRAINT FKCLIENTECONTATO1 FOREIGN KEY (IDCLIENTE)
     REFERENCES TBCLIENTE (IDCLIENTE);

INSERT INTO TBCLIENTECONTATO
SELECT CLIENTE, 1, 1, EMAIL FROM CLIENTE WHERE EMAIL IS NOT NULL;

INSERT INTO TBCLIENTECONTATO
SELECT CLIENTE, 2, 2, MSN FROM CLIENTE WHERE MSN IS NOT NULL;

CREATE TABLE TBCLIENTEENDERECO (
   IDCLIENTE INTEGER  NOT NULL,
   TIPO CHAR(1) NOT NULL,
   ENDERECO VARCHAR(40),
   BAIRRO VARCHAR(25),
   CIDADE VARCHAR(30),
   CEP VARCHAR(8),
   UF VARCHAR(2),
   PRIMARY KEY (IDCLIENTE, TIPO)
);
commit;
ALTER TABLE TBCLIENTEENDERECO ADD CONSTRAINT FKCLIENTEENDERECO1 FOREIGN KEY (IDCLIENTE) REFERENCES TBCLIENTE (IDCLIENTE);

INSERT INTO TBCLIENTEENDERECO
  SELECT CLIENTE, TIPO, ENDERECO, BAIRRO, CIDADE, CEP, UF FROM ENDERECOCLIENTE;

commit;

CREATE TABLE TBSEGMENTOCLIENTE (
   IDCLIENTE INTEGER NOT NULL,
   IDSEGMENTO INTEGER NOT NULL,
   PRIMARY KEY (IDCLIENTE, IDSEGMENTO)
);

ALTER TABLE TBSEGMENTOCLIENTE ADD CONSTRAINT FKSEGMENTOCLIENTE1 FOREIGN KEY (IDCLIENTE)
    REFERENCES TBCLIENTE (IDCLIENTE);
ALTER TABLE TBSEGMENTOCLIENTE ADD CONSTRAINT FKSEGMENTOCLIENTE2 FOREIGN KEY (IDSEGMENTO)
    REFERENCES TBSEGMERCADO (IDSEGMENTO);

INSERT INTO TBSEGMENTOCLIENTE SELECT CLIENTE, SEGMENTO FROM 
SEGMENTO_CLIENTE;

CREATE TABLE TBVISITACLIENTE (
   IDVISITACLIENTE integer not null,
   IDCLIENTE integer,
   DTVISITA timestamp NOT NULL,
   IDVENDEDOR integer not null,
   DTVISITAREAL timestamp,
   TIPOVISITA varchar(1),
   GEROUPEDIDO varchar(1),
   OBS blob sub_type 1,
   PRIMARY KEY (IDVISITACLIENTE)
);

ALTER TABLE TBVISITACLIENTE ADD CONSTRAINT FKVISITACLIENTE1 FOREIGN KEY (IDCLIENTE)
    REFERENCES TBCLIENTE (IDCLIENTE);
ALTER TABLE TBVISITACLIENTE ADD CONSTRAINT FKVISITACLIENTE2 FOREIGN KEY (IDVENDEDOR)
    REFERENCES TBVENDEDOR (IDVENDEDOR);

CREATE unique INDEX IDXVISITACLIENTE1 ON TBVISITACLIENTE(DTVISITA, IDVENDEDOR, IDCLIENTE);

INSERT INTO TBVISITACLIENTE
SELECT c.CLIENTE, c.DATA, c.VENDEDOR, c.TIPO_VISITA, 
c.PEDIDO FROM VISITA_CLIENTE c, vendedor v
where c.vendedor = v.vendedor;

CREATE TABLE TBCONTATOVENDEDOR (
   IDCONTATO INTEGER not null,
   IDVENDEDOR INTEGER NOT NULL,
   CONTATO VARCHAR(30) NOT NULL,
   DTANIVER VARCHAR(4),
   TIPOCONTATO VARCHAR(1) NOT NULL,
   MSN VARCHAR(40),
   OBSERVACAO BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   PRIMARY KEY (IDCONTATO)
);

ALTER TABLE TBCONTATOVENDEDOR ADD CONSTRAINT FCCONTATOVENDEDOR1 FOREIGN KEY (IDVENDEDOR)
    REFERENCES TBVENDEDOR (IDVENDEDOR);

CREATE TABLE TBCOMPRADOR (
   IDCOMPRADOR INTEGER not null,
   IDCLIENTE INTEGER NOT NULL,
   CONTATO VARCHAR(30) NOT NULL,
   DTANIVER VARCHAR(4),
   TIPOCOMPRADOR VARCHAR(1),
   MSN VARCHAR(40),
   OBSERVACAO BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   PRIMARY KEY (IDCOMPRADOR)
);

CREATE INDEX IDXCOMPRADORCLIENTE1 ON TBCOMPRADOR(IDCLIENTE);

ALTER TABLE TBCOMPRADOR ADD CONSTRAINT FKCOMPRADORCLIENTE1 FOREIGN KEY (IDCLIENTE)
    REFERENCES TBCLIENTE (IDCLIENTE);

INSERT INTO TBCOMPRADOR SELECT NUM_COMPRADOR, CLIENTE, CONTATO, 
DTANIVER, TIPO_COMPRADOR, MSN FROM COMPRADOR_CLIENTE;


CREATE TABLE TBFORMAPGTO (
   IDPGTO CHAR(3) NOT NULL,
   NOME VARCHAR(25) NOT NULL,
   PRIMARY KEY (IDPGTO)
);

INSERT INTO TBFORMAPGTO SELECT PGTO, NOME FROM FORMA_PGTO;

CREATE TABLE TBGRUPOPRODUTO (
   IDCODGRUPO INTEGER not null,
   NOMEGRUPO VARCHAR(50) NOT NULL,
   PRIMARY KEY (IDCODGRUPO)
);

INSERT INTO TBGRUPOPRODUTO SELECT COD_GRUPO, NOME_GRUPO FROM GRUPOPRODUTO;

CREATE TABLE TBSUBGRUPOPRD (
   IDCODSUBGRUPO INTEGER not null,
   IDCODGRUPO INTEGER not null,
   NOMEGRUPO VARCHAR(50) NOT NULL,
   PRIMARY KEY (IDCODSUBGRUPO)
);

ALTER TABLE TBSUBGRUPOPRD ADD CONSTRAINT FKSUBGRUPOPRODUTO1 FOREIGN KEY (IDCODGRUPO) REFERENCES TBGRUPOPRODUTO (IDCODGRUPO);

CREATE TABLE TBUNIDADEPRODUTO (
   IDUNIDADE VARCHAR(5) NOT NULL,
   NOME VARCHAR(25) NOT NULL,
   PRIMARY KEY (IDUNIDADE)
);

INSERT INTO TBUNIDADEPRODUTO SELECT UNIDADE, NOME FROM UNIDADE_PRODUTO;
commit;


CREATE TABLE TBPRODUTO (
   IDPRODUTO INT NOT NULL,
   BLOQUEADO CHAR(1) NOT NULL,
   DESCRICAO VARCHAR(40) NOT NULL,
   IDUNIDADE VARCHAR(5) NOT NULL,
   IDUNDCUMUL VARCHAR(5) NOT NULL,
   FATORCNV NUMERIC(10,4) NOT NULL,
   PESO NUMERIC(10,4),
   IDCODGRUPO INTEGER,
   IDCODSUBGRUPO INTEGER,
   FOTO BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   PRIMARY KEY (IDPRODUTO)
);

CREATE INDEX IDXPRODUTO1 ON TBPRODUTO(DESCRICAO);
CREATE INDEX IDXPRODUTO2 ON TBPRODUTO(IDUNIDADE);
CREATE INDEX IDXPRODUTO3 ON TBPRODUTO(IDCODGRUPO);
commit;

ALTER TABLE TBPRODUTO ADD CONSTRAINT FKPRODUTO1 FOREIGN KEY (IDUNIDADE) REFERENCES TBUNIDADEPRODUTO (IDUNIDADE);
ALTER TABLE TBPRODUTO ADD CONSTRAINT FKPRODUTO2 FOREIGN KEY (IDUNDCUMUL) REFERENCES TBUNIDADEPRODUTO (IDUNIDADE);
ALTER TABLE TBPRODUTO ADD CONSTRAINT FKPRODUTO3 FOREIGN KEY (IDCODGRUPO) REFERENCES TBGRUPOPRODUTO (IDCODGRUPO);
ALTER TABLE TBPRODUTO ADD CONSTRAINT FKPRODUTO4 FOREIGN KEY (IDCODSUBGRUPO) REFERENCES TBSUBGRUPOPRD (IDCODSUBGRUPO);

UPDATE PRODUTO SET COD_GRUPO = 1 WHERE (COD_GRUPO IS NULL) OR (COD_GRUPO = 0);
commit;
INSERT INTO TBPRODUTO SELECT PRODUTO, DESCRICAO, UNIDADE, UNDCUMUL, 
FATORCNV, COD_GRUPO FROM PRODUTO;

CREATE TABLE TBREPRES (
   IDREPRES INTEGER NOT NULL,
   RAZAO VARCHAR(50) NOT NULL,
   FANTASIA VARCHAR(30),
   site varchar(100),
   ENDERECO VARCHAR(60),
   CIDADE VARCHAR(30),
   BAIRRO VARCHAR(25),
   CEP VARCHAR(8),
   UF VARCHAR(2),
   CGC VARCHAR(14),
   INSEST VARCHAR(18),
   FONE1 VARCHAR(12),
   FONE2 VARCHAR(12),
   FONE3 VARCHAR(12),
   FAX VARCHAR(12),
   DTINCLUS TIMESTAMP,
   DATATABELA TIMESTAMP,
   TOTAL NUMERIC(10,2),
   INATIVO CHAR(1),
   CONTACOR VARCHAR(10),
   DIASATENDIMENTO INTEGER,
   AGENCIA VARCHAR(8),
   COMISSAO NUMERIC(10,2) NOT NULL,
   datatabela timestamp,
   METAVENDA BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   OBSERVACAO BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   OBSERVACAOCLIENTE BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   OBSPRODUTO BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   OBSPROMOCAO BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   PRIMARY KEY (IDREPRES)
);

CREATE INDEX IDXREPRES1 ON TBREPRES(RAZAO);

INSERT INTO TBREPRES SELECT REPRES, RAZAO, FANTASIA, ENDERECO, CIDADE, 
   BAIRRO, CEP, UF, CGC, INSEST, FONE1, FONE2, FONE3, FAX, DTINCLUS,
   TOTAL, INATIVO, CONTACOR, AGENCIA, COMISSAO, OBSERVACAO, OBS2, OBS3
   FROM REPRES;
commit; 

Create table tbarquivopreco (
  idarquivo integer not null,
  idrepres integer not null,
  descricao varchar(512),
  arquivo BLOB SUB_TYPE 1 SEGMENT SIZE 80,
  primary key (idarquivo)
);

CREATE TABLE TBREPRESCONTATO (
   IDREPRES INTEGER  NOT NULL,
   TIPO CHAR(1) NOT NULL,
   NUMITEM INTEGER NOT NULL,
   ENDERECO VARCHAR(50),
   PRIMARY KEY (IDREPRES, TIPO, NUMITEM)
);

ALTER TABLE TBREPRESCONTATO ADD CONSTRAINT FKREPRESCONTATO1 FOREIGN KEY (IDREPRES)
     REFERENCES TBREPRES (IDREPRES);

INSERT INTO TBREPRESCONTATO
SELECT REPRES, 1, 1, EMAIL FROM REPRES WHERE EMAIL IS NOT NULL;

INSERT INTO TBREPRESCONTATO
SELECT REPRES, 2, 2, MSN FROM REPRES WHERE MSN IS NOT NULL;


create table tbcomissaovendedor (
   idvendedor integer not null,
   idrepres integer not null,
   comissao NUMERIC(10,2) not null,
   primary key (idvendedor, idrepres)
);

alter table tbcomissaovendedor add constraint fkcomissaovendedor1 foreign key (idvendedor) references tbvendedor (idvendedor);
alter table tbcomissaovendedor add constraint fkcomissaovendedor2 foreign key (idrepres) references tbrepres (idrepres);

insert into tbcomissaovendedor select vendedor, repres, comissao from comissaorepres;

CREATE TABLE TBSEGMENTOREPRES (
   IDREPRES INTEGER NOT NULL,
   IDSEGMENTO INTEGER NOT NULL,
   PRIMARY KEY (IDREPRES, IDSEGMENTO)

);

ALTER TABLE TBSEGMENTOREPRES ADD CONSTRAINT FKSEGMENTOREPRES1 FOREIGN KEY (IDREPRES) REFERENCES TBREPRES (IDREPRES);
ALTER TABLE TBSEGMENTOREPRES ADD CONSTRAINT FKSEGMENTOREPRES2 FOREIGN KEY (IDSEGMENTO) REFERENCES TBSEGMERCADO (IDSEGMENTO);

INSERT INTO TBSEGMENTOREPRES SELECT REPRES, SEGMENTO FROM 
SEGMENTO_REPRES;

CREATE TABLE TBVENDEDORREPRES (
   IDVENDEDOR INTEGER not null,
   IDREPRES INTEGER NOT NULL,
   CONTATO VARCHAR(30) NOT NULL,
   DTANIVER VARCHAR(4),
   CORRESPONDENCIA SMALLINT,
   MSN varchar(40),
   OBSERVACAO BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   PRIMARY KEY (IDVENDEDOR)
);

ALTER TABLE TBVENDEDORREPRES ADD CONSTRAINT FKVENDEDORREPRES1 FOREIGN 
KEY (IDREPRES) REFERENCES TBREPRES (IDREPRES);

INSERT INTO TBVENDEDORREPRES SELECT NUM_VENDEDOR_REPRES, REPRES, 
CONTATO, DTANIVER, CORRESPONDENCIA, msn FROM VENDEDOR_REPRES;

CREATE TABLE TBREPRESPRODUTO (
   IDREPRES INTEGER NOT NULL,
   IDPRODUTO INT NOT NULL,
   TABELA VARCHAR(1) NOT NULL,
   IPI NUMERIC(10,2),
   OBS BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   PRAZO SMALLINT,
   PRECO NUMERIC(10,2),
   preco2 numeric(10,2),
   PRECOFINAL NUMERIC(10,2),
   PRECOV NUMERIC(10,2),
   QTDUND NUMERIC(10,2),
   COMISSAO NUMERIC(10,2),
   FRETE NUMERIC(10,2),
   EMBALAGEM NUMERIC(10,4),
   PCAUND INTEGER,
   PCAEMBALAGEM INTEGER,
   ATIVO SMALLINT,
   PRIMARY KEY (IDREPRES, IDPRODUTO)
);

CREATE INDEX IDXREPRESPRODUTO1 ON TBREPRESPRODUTO(IDPRODUTO);
CREATE INDEX IDXREPRESPRODUTO2 ON TBREPRESPRODUTO(IDREPRES);

ALTER TABLE TBREPRESPRODUTO ADD CONSTRAINT FKREPRESPRODUTO1 FOREIGN KEY 
(IDREPRES) REFERENCES TBREPRES (IDREPRES);
ALTER TABLE TBREPRESPRODUTO ADD CONSTRAINT FKREPRESPRODUTO2 FOREIGN KEY 
(IDPRODUTO) REFERENCES TBPRODUTO (IDPRODUTO);

INSERT INTO TBREPRESPRODUTO 
SELECT REPRES, PRODUTO, TABELA, IPI, OBS, 
PRAZO, PRECO, PRECO_FINAL, PRECOV, QTDUND, 0, FRETE, EMBALAGEM, ATIVO FROM 
REPRES_PRODUTO;

update tbrepresproduto p set p.comissao = (select r.comissao from tbrepres r where r.IDREPRES = p.IDREPRES);
commit;

CREATE TABLE TBCLIENTEREPRES (
   IDREPRES INTEGER NOT NULL,
   IDCLIENTE INTEGER NOT NULL,
   CODREPR VARCHAR(10),
   CODIDENT VARCHAR(10),
   LIMITECREDITO NUMERIC(10,2),
   PRIMARY KEY (IDREPRES, IDCLIENTE)
);

CREATE INDEX IDXCLIENTEREPRES1 ON TBCLIENTEREPRES(IDCLIENTE);
CREATE INDEX IDXCLIENTEREPRES2 ON TBCLIENTEREPRES(IDREPRES);

ALTER TABLE TBCLIENTEREPRES ADD CONSTRAINT FKCLIENTEREPRES1 FOREIGN KEY 
(IDREPRES) REFERENCES TBREPRES (IDREPRES);
ALTER TABLE TBCLIENTEREPRES ADD CONSTRAINT FKCLIENTEREPRES2 FOREIGN KEY 
(IDCLIENTE) REFERENCES TBCLIENTE (IDCLIENTE);

INSERT INTO TBCLIENTEREPRES SELECT REPRES, CLIENTE, CODREPR, CODIDENT, 
LIMITECREDITO FROM CLIENTE_REPRES;

CREATE TABLE TBCONTAREPRES (
   IDCONTAREPRES INTEGER NOT NULL,
   IDREPRES INTEGER NOT NULL,
   IDBANCO VARCHAR(3) NOT NULL,
   AGENCIA VARCHAR(10) NOT NULL,
   CCORRENTE VARCHAR(10) NOT NULL,
   NOME VARCHAR(50) NOT NULL,
   CPFCNPJ VARCHAR(14),
   ATIVO CHAR(1),
   PRIMARY KEY (IDCONTAREPRES)
);

ALTER TABLE TBCONTAREPRES ADD CONSTRAINT FKCONTAREPRES1 FOREIGN KEY 
(IDREPRES) REFERENCES TBREPRES (IDREPRES);
ALTER TABLE TBCONTAREPRES ADD CONSTRAINT FKCONTAREPRES2 FOREIGN KEY 
(IDBANCO) REFERENCES TBBANCO (IDBANCO);

INSERT INTO TBCONTAREPRES SELECT  NUM_CONTA_REPRES, REPRES, BANCO, 
AGENCIA, CCORRENTE, NOME FROM CONTA_REPRES;

CREATE TABLE TBENTRADAREPRES (
   IDENTRADA INTEGER not null,
   IDREPRES INTEGER NOT NULL,
   DTENTRADA TIMESTAMP NOT NULL,
   VALOR NUMERIC(10,2) NOT NULL,
   HISTORICO VARCHAR(30),
   TIPO VARCHAR(1),
   PEDIDO VARCHAR(80),
   OBSERVACAO VARCHAR(256),
   PRIMARY KEY (IDENTRADA)
);

CREATE INDEX IDXENTRADAREPRES1 ON TBENTRADAREPRES(IDREPRES);
CREATE INDEX IDXENTRADAREPRES2 ON TBENTRADAREPRES(DTENTRADA);

ALTER TABLE TBENTRADAREPRES ADD CONSTRAINT FKENTRADAREPRES FOREIGN KEY 
(IDREPRES) REFERENCES TBREPRES (IDREPRES);

INSERT INTO TBENTRADAREPRES SELECT NUM_ENTRADA, REPRES, DATA, VALOR, 
HISTORICO, TIPO, PEDIDO, OBS FROM ENTRADA_REPRES;

CREATE TABLE TBFORMAPGTOREPRES (
   IDREPRES INTEGER NOT NULL,
   IDPGTO CHAR(3) NOT NULL,
   FRETE VARCHAR(20),
   PGFRETE VARCHAR(20),
   IPI VARCHAR(20),
   ICMS VARCHAR(20),
   ENTREGA VARCHAR(20),
   PEDMINIMO VARCHAR(20),
   PROCEDEN VARCHAR(20),
   NFPERC VARCHAR(20),
   OBS VARCHAR(256),
   DISP VARCHAR(20),
   PRIMARY KEY (IDREPRES, IDPGTO)
);

ALTER TABLE TBFORMAPGTOREPRES ADD CONSTRAINT FKFORMAPGTOREPRES1 FOREIGN 
KEY (IDREPRES) REFERENCES TBREPRES (IDREPRES);
ALTER TABLE TBFORMAPGTOREPRES ADD CONSTRAINT FKFORMAPGTOREPRES2 FOREIGN 
KEY (IDPGTO) REFERENCES TBFORMAPGTO (IDPGTO);

INSERT INTO TBFORMAPGTOREPRES
SELECT REPRES, PGTO, FRETE, PGFRETE, IPI, ICMS, 
  ENTREGA, PEDMINIMO, PROCEDEN, NFPERC, OBS, DISP FROM FORMA_PGTO_REPRES
WHERE PGTO IN (SELECT PGTO FROM FORMA_PGTO);

CREATE TABLE TBTRANSPORTADOR (
   IDTRANS INTEGER NOT NULL,
   CODTRANS CHAR(3) NOT NULL,
   NOME VARCHAR(25) NOT NULL,
   FONE1 VARCHAR(12),
   FONE2 VARCHAR(12),
   FAX1 VARCHAR(12),
   FAX2 VARCHAR(12),
   IDPGTO CHAR(3),
   PRIMARY KEY (IDTRANS)
);

ALTER TABLE TBTRANSPORTADOR ADD CONSTRAINT FKTRANSPORTADOR1 FOREIGN KEY (IDPGTO) REFERENCES TBFORMAPGTO (IDPGTO);

create unique index idxtransp01 on tbtransportador(idtrans);

INSERT INTO TBTRANSPORTADOR SELECT NUM_TRANS, TRANS, NOME, FONE1, FONE2, 
FAX1, FAX2 FROM TRANSPORTADOR;
commit;

create table tbtipopgto (
  idtipopgto integer not null,
  nome varchar(40) not null,
  primary key (idtipopgto)
);

insert into tbtipopgto values (0, 'NAO DEFINIDO');
insert into tbtipopgto values (1, 'CHEQUE');
insert into tbtipopgto values (2, 'BOLETO');
insert into tbtipopgto values (3, 'DEPOSITO');
insert into tbtipopgto values (4, 'DINHEIRO');


commit;

CREATE TABLE TBPEDIDO (
   IDPEDIDO INTEGER NOT NULL,
   pre char not null,
   IDPEDIDOREPRES INTEGER,
   DTPEDIDO TIMESTAMP NOT NULL,
   IDCLIENTE INTEGER NOT NULL,
   IDCLIENTERES INTEGER,
   IDVENDEDOR INTEGER NOT NULL,
   IDREPRES INTEGER NOT NULL,
   IDTRANS INTEGER NOT NULL,
   IDPGTO CHAR(3) NOT NULL,
   IDPGTOCLIENTE CHAR(3),
   IDPGTOTRANSP CHAR(3),
   idtipopgto integer not null,
   VALOR NUMERIC(10,2) NOT NULL,
   VALORCLIENTE NUMERIC(10,2) NOT NULL,
   VALORPEND NUMERIC(10,2),
   VALOROP NUMERIC(10,2),
   COMISSVEN NUMERIC(10,2) NOT NULL,
   COMISSAO NUMERIC(10,2) NOT NULL,
   EMITIDO VARCHAR(1),
   ENTREGA TIMESTAMP,
   TPENTREGA VARCHAR(20),
   FRETE NUMERIC(10,2),
   DTCANCEL TIMESTAMP,
   ATEND VARCHAR(1) NOT NULL,
   IDFORMAVENDA integer default 1 NOT NULL,
   SITUACAO VARCHAR(1) NOT NULL,
   ACOMPANHAR VARCHAR(1) NOT NULL,
   emitidoCobranca char(1) not null,
   precobranca char (1) not null,
   embarqueimediato char (1) not null default '0',
   precobranca char (1) not null,
   TIPOPEDIDO SMALLINT,
   ISROMANEIO SMALLINT,
   EMAILVENDENVIADO SMALLINT,
   IPI NUMERIC(10,2),
   SEGURO NUMERIC(10,2),
   OBS BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   OBSATENDIMENTO BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   OBS2 BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   OBS3 obs3 BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   complemento BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   dtcriacao timestamp default current_date,
   idusuariocriador integer,
   dtemitidocliente timestamp,
   dtemitidorepres timestamp,
   PRIMARY KEY (IDPEDIDO)
);
commit;

CREATE INDEX IDXPEDIDO1 ON TBPEDIDO(IDREPRES);
CREATE INDEX IDXPEDIDO2 ON TBPEDIDO(IDCLIENTE);
CREATE INDEX IDXPEDIDO3 ON TBPEDIDO(IDVENDEDOR);
CREATE INDEX IDXPEDIDO4 ON TBPEDIDO(DTPEDIDO);
CREATE INDEX IDXPEDIDO5 ON TBPEDIDO(ENTREGA);

ALTER TABLE TBPEDIDO ADD CONSTRAINT FKPEDIDO1 FOREIGN KEY (IDREPRES) REFERENCES TBREPRES (IDREPRES);
ALTER TABLE TBPEDIDO ADD CONSTRAINT FKPEDIDO2 FOREIGN KEY (IDCLIENTE) REFERENCES TBCLIENTE (IDCLIENTE);
ALTER TABLE TBPEDIDO ADD CONSTRAINT FKPEDIDO3 FOREIGN KEY (IDCLIENTERES) REFERENCES TBCLIENTE (IDCLIENTE);
ALTER TABLE TBPEDIDO ADD CONSTRAINT FKPEDIDO4 FOREIGN KEY (IDVENDEDOR) REFERENCES TBVENDEDOR (IDVENDEDOR);
ALTER TABLE TBPEDIDO ADD CONSTRAINT FKPEDIDO5 FOREIGN KEY (IDTRANS) REFERENCES TBTRANSPORTADOR (IDTRANS);
ALTER TABLE TBPEDIDO ADD CONSTRAINT FKPEDIDO6 FOREIGN KEY (IDPGTO) REFERENCES TBFORMAPGTO (IDPGTO);
ALTER TABLE TBPEDIDO ADD CONSTRAINT FKPEDIDO7 FOREIGN KEY (IDPGTOTRANSP) REFERENCES TBFORMAPGTO (IDPGTO);
alter table tbpedido add constraint fkpedido8 foreign key (idtipopgto) references tbtipopgto (idtipopgto);
ALTER TABLE TPPEDIDO ADD CONSTRAINT FKPEDIDO9 FOREIGN KEY (IDPGTOCLIENTE) REFERENCES TBFORMAPGTO (IDPGTO);
ALTER TABLE TPPEDIDO ADD CONSTRAINT FKPEDIDO10 FOREIGN KEY (IDFORMAVENDA) REFERENCES TBFORMAVENDA (IDFORMAVENDA);

UPDATE PEDIDO SET CLIENTERES = NULL WHERE CLIENTERES NOT IN (SELECT CLIENTE FROM CLIENTE);
UPDATE PEDIDO SET ACOMPANHAR = '0' WHERE ACOMPANHAR IS NULL;
UPDATE PEDIDO SET COMISSVEN = 0 WHERE COMISSVEN is null;
commit;
INSERT INTO TBPEDIDO
SELECT p.PEDIDO, p.DTPEDIDO, p.CLIENTE, p.CLIENTERES, 
p.VENDEDOR, p.REPRES, p.NUM_TRANS, p.PGTO, p.PGTOTRANSP, 0, p.VALOR, p.VALORPEND, p.valorop,
p.COMISSVEN, p.COMISSAO, p.EMITIDO, p.ENTREGA, p.TPENTREGA, p.FRETE, p.DTCANCEL, p.ATEND, p.SITUACAO, 
p.ACOMPANHAR, p.TIPOPEDIDO, p.ISROMANEIO, p.IPI, p.SEGURO, p.OBS, p.OBS2
FROM PEDIDO p, vendedor v, cliente c
where p.vendedor = v.vendedor and p.cliente = c.cliente;

create table tbpedidoembarque (
idpedidoembarque integer not null,
idpedido integer not null,
dtembarque timestamp not null,
primary key (idpedidoembarque)
);

alter table tbpedidoembarque add constraint fkpedidoembarque1 foreign key (idpedido) references tbpedido (idpedido);


create table tborcamento (
   IDORCAMENTO INTEGER NOT NULL,
   IDPEDIDO INTEGER,
   DTORCAMENTO TIMESTAMP NOT NULL,
   DTVALIDADE TIMESTAMP NOT NULL,
   DTENTREGA TIMESTAMP,
   IDCLIENTE INTEGER NOT NULL,
   IDVENDEDOR INTEGER NOT NULL,
   IDREPRES INTEGER NOT NULL,
   IDPGTO CHAR(3) NOT NULL,
   VALOR NUMERIC(10,2) NOT NULL,
   SITUACAO VARCHAR(1) NOT NULL,
   OBS BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   PRIMARY KEY (IDORCAMENTO)
);

ALTER TABLE TBORCAMENTO ADD CONSTRAINT FKORCAMENTO1 FOREIGN KEY (IDREPRES) REFERENCES TBREPRES (IDREPRES);
ALTER TABLE TBORCAMENTO ADD CONSTRAINT FKORCAMENTO2 FOREIGN KEY (IDCLIENTE) REFERENCES TBCLIENTE (IDCLIENTE);
ALTER TABLE TBORCAMENTO ADD CONSTRAINT FKORCAMENTO3 FOREIGN KEY (IDVENDEDOR) REFERENCES TBVENDEDOR (IDVENDEDOR);
ALTER TABLE TBORCAMENTO ADD CONSTRAINT FKORCAMENTO4 FOREIGN KEY (IDPGTO) REFERENCES TBFORMAPGTO (IDPGTO);

CREATE TABLE TBITEMORCAMENTO (
   IDORCAMENTO INTEGER NOT NULL,
   IDPRODUTO INT NOT NULL,
   QTD NUMERIC(10,3) NOT NULL,
   IPI NUMERIC(10,2),
   VALOR NUMERIC(10,2) NOT NULL,
   SITUACAO VARCHAR(1) NOT NULL,
   embalagem int,
   PRIMARY KEY (IDORCAMENTO, IDPRODUTO)
);

CREATE INDEX IDXITEMORCAMENTO1 ON TBITEMORCAMENTO(IDORCAMENTO);
CREATE INDEX IDXITEMORCAMENTO2 ON TBITEMORCAMENTO(IDPRODUTO);

ALTER TABLE TBITEMORCAMENTO ADD CONSTRAINT FKITEMORCAMENTO1 FOREIGN KEY
(IDORCAMENTO) REFERENCES TBORCAMENTO (IDORCAMENTO);
ALTER TABLE TBITEMORCAMENTO ADD CONSTRAINT FKITEMORCAMENTO2 FOREIGN KEY
(IDPRODUTO) REFERENCES TBPRODUTO (IDPRODUTO);

Create table tbarquivopedido (
  idarquivo integer not null,
  idpedido integer not null,
  descricao varchar(512),
  arquivo BLOB SUB_TYPE 1 SEGMENT SIZE 80,
  primary key (idarquivo)
);


alter table tbarquivopreco add constraint fkarquivopreco1 foreign key (idrepres) references tbrepres (idrepres);


Create table tbarquivoorcamento (
  idarquivo integer not null,
  idorcamento integer not null,
  descricao varchar(512),
  arquivo BLOB SUB_TYPE 1 SEGMENT SIZE 80,
  primary key (idarquivo)
);

alter table tbarquivoorcamento add constraint fkarquivoorcamento1 foreign key (idorcamento) references tborcamento (idorcamento);

commit;

CREATE TABLE TBITEMPEDIDO (
   IDPEDIDO INTEGER NOT NULL,
   IDPRODUTO INT NOT NULL,
   QTD NUMERIC(10,3) NOT NULL,
   QTDROMANEIO NUMERIC(10,2),
   IPI NUMERIC(10,2),
   VALOR NUMERIC(10,2) NOT NULL,
   VALORCLIENTE NUMERIC(10,2),
   VALORROMANEIO NUMERIC(10,2),
   SITUACAO VARCHAR(1) NOT NULL,
   DTENTREGA TIMESTAMP,
   COMISSAO NUMERIC(10,2) NOT NULL,
   embalagem int,
   PRIMARY KEY (IDPEDIDO, IDPRODUTO)
);

CREATE INDEX IDXITEMPEDIDO1 ON TBITEMPEDIDO(IDPEDIDO);
CREATE INDEX IDXITEMPEDIDO2 ON TBITEMPEDIDO(IDPRODUTO);

ALTER TABLE TBITEMPEDIDO ADD CONSTRAINT FKITEMPEDIDO1 FOREIGN KEY 
(IDPEDIDO) REFERENCES TBPEDIDO (IDPEDIDO);
ALTER TABLE TBITEMPEDIDO ADD CONSTRAINT FKITEMPEDIDO2 FOREIGN KEY 
(IDPRODUTO) REFERENCES TBPRODUTO (IDPRODUTO);

INSERT INTO TBITEMPEDIDO
SELECT i.PEDIDO, i.PRODUTO, i.QTD, i.QTD_ROMANEIO, i.IPI, 
i.VALOR, i.VALOR_ROMANEIO, i.SITUACAO, i.DTENTREGA, p.comissao
FROM ITEM_PEDIDO i, tbpedido p
where i.pedido = p.idpedido;

CREATE TABLE TBATENDIMENTOPEDIDO (
   IDPEDIDO INTEGER NOT NULL,
   NF VARCHAR(10) NOT NULL,
   DTNOTA TIMESTAMP NOT NULL,
   VALOR NUMERIC(10,2) NOT NULL,
   VALORCOM NUMERIC(10,2),
   DTCOMPREV TIMESTAMP,
   DTFRETE TIMESTAMP,
   PAGO VARCHAR(1),
   EMITIDO VARCHAR(1),
   OPERADOR VARCHAR(2),
   RECIBO VARCHAR(10),
   fornecedor varchar(100),
   DTCOM TIMESTAMP,
   dtrecibo timestamp,
   OBSERVACAO BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   valoripi numeric(10,2),
   substrib numeric(10,2),
   valorfrete numeric(10,2),
   valoricms numeric(10,2),
   valorseguro numeric(10,2),
   valordesconto numeric(10,2),
   dtdesconto timestamp,
   motorista varchar(50),
   fonemotorista varchar(20),
   PRIMARY KEY (IDPEDIDO, NF)
);

CREATE INDEX IDXATENDIMENTO1 ON TBATENDIMENTOPEDIDO(DTNOTA);
CREATE INDEX IDXATENDIMENTO2 ON TBATENDIMENTOPEDIDO(NF);
CREATE INDEX IDXATENDIMENTO3 ON TBATENDIMENTOPEDIDO(IDPEDIDO);
CREATE INDEX IDXATENDIMENTO4 ON TBATENDIMENTOPEDIDO(DTCOM);

ALTER TABLE TBATENDIMENTOPEDIDO ADD CONSTRAINT FKATENDIMENTOPEDIDO1 
FOREIGN KEY (IDPEDIDO) REFERENCES TBPEDIDO (IDPEDIDO);

INSERT INTO TBATENDIMENTOPEDIDO
SELECT ap.PEDIDO, ap.NF, ap.DTNOTA, ap.VALOR, 
ap.VALORCOM, ap.DTCOMPREV, ap.PAGO, ap.EMITIDO, ap.RECIBO, ap.DTCOM FROM 
ATENDIMENTO_PEDIDO ap, tbpedido p where ap.pedido = p.idpedido;

commit;

create table tbrecibocomissao (
   idrecibo integer not null,
   dtrecibo timestamp not null,
   idvendedor integer no null,
   recibo BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   primary key (idrecibo)
);

create index idxrecibocomissao1 on tbrecibocomissao(idvendedor);
create index idxrecibocomissao2 on tbrecibocomissao(dtrecibo);

CREATE SEQUENCE TBRECIBOCOMISAO_ID_SEQ;
SET GENERATOR TBRECIBOCOMISAO_ID_SEQ TO 1;

alter table tbrecibocomissao add constraint fkrecibocomissaovend foreign key (idvendedor) references tbvendedor (idvendedor);

CREATE TABLE TBITEMPEDIDOATEND (
   IDPEDIDO INTEGER NOT NULL,
   NF VARCHAR(10) NOT NULL,
   IDPRODUTO INT NOT NULL,
   QTD NUMERIC(10,3) NOT NULL,
   QTDE NUMERIC(10,3) NOT NULL,
   IPI SMALLINT,
   VALOR NUMERIC(10,2) NOT NULL,
   COMISSAO NUMERIC(10,2) NOT NULL,
   DTENTREGA TIMESTAMP,
   PRIMARY KEY (IDPEDIDO, NF, IDPRODUTO)
);

CREATE INDEX IDXITEMPEDIDOATEND1 ON TBITEMPEDIDOATEND(IDPEDIDO);
CREATE INDEX IDXITEMPEDIDOATEND2 ON TBITEMPEDIDOATEND(IDPRODUTO);
CREATE INDEX IDXITEMPEDIDOATEND3 ON TBITEMPEDIDOATEND(NF);

ALTER TABLE TBITEMPEDIDOATEND ADD CONSTRAINT FKITEMPEDIDOATEND1 FOREIGN 
KEY (IDPEDIDO, NF) REFERENCES TBATENDIMENTOPEDIDO (IDPEDIDO, NF);
ALTER TABLE TBITEMPEDIDOATEND ADD CONSTRAINT FKITEMPEDIDOATEND2 FOREIGN 
KEY (IDPRODUTO) REFERENCES TBPRODUTO (IDPRODUTO);

INSERT INTO TBITEMPEDIDOATEND
SELECT i.PEDIDO, i.NF, i.PRODUTO, i.QTD, i.IPI, 
i.VALOR, i.DTENTREGA FROM ITEM_PEDIDO_ATEND i, TBATENDIMENTOPEDIDO p 
where i.pedido = p.idpedido
and i.nf = p.nf;

commit;

CREATE TABLE TBPGTOCLIENTE (
   IDPGTOCLIENTE INTEGER NOT NULL,
   IDPEDIDO INTEGER NOT NULL,
   NF VARCHAR(10) NOT NULL,
   VENC TIMESTAMP NOT NULL,
   COMPLEMEN VARCHAR(30),
   VALOR NUMERIC(10,2) NOT NULL,
   TPPGTO VARCHAR(2),
   DTPGTO TIMESTAMP,
   DTPREVPG TIMESTAMP,
   VLRPGTO NUMERIC(10,2),
   IDCONTAREPRES INTEGER,
   cobranca char(1),
   tbpgtocliente add valorcobranca numeric(10,2),
    observacao BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   PRIMARY KEY (IDPGTOCLIENTE)
);
commit;

CREATE INDEX IDXPGTOCLIENTE1 ON TBPGTOCLIENTE(IDPEDIDO);
CREATE INDEX IDXPGTOCLIENTE2 ON TBPGTOCLIENTE(NF);
CREATE INDEX IDXPGTOCLIENTE3 ON TBPGTOCLIENTE(VENC);
CREATE INDEX IDXPGTOCLIENTE4 ON TBPGTOCLIENTE(DTPGTO);

ALTER TABLE TBPGTOCLIENTE ADD CONSTRAINT FKPGTOCLIENTE1 FOREIGN KEY 
(IDPEDIDO, NF) REFERENCES TBATENDIMENTOPEDIDO (IDPEDIDO, NF);
ALTER TABLE TBPGTOCLIENTE ADD CONSTRAINT FKPGTOCLIENTE2 FOREIGN KEY 
(IDCONTAREPRES) REFERENCES TBCONTAREPRES (IDCONTAREPRES);

UPDATE PGTO_CLIENTE SET NUM_CONTA_REPRES = NULL WHERE NUM_CONTA_REPRES = 0;
update pgto_cliente set NUM_CONTA_REPRES = NULL where num_conta_repres not in (select
 num_conta_repres from conta_repres);

commit;
INSERT INTO TBPGTOCLIENTE
SELECT a.NUM_PGTO, a.PEDIDO, a.NF, a.VENC, a.COMPLEMEN, 
a.VALOR, a.TPPGTO, a.DTPGTO, a.DTPREVPG, a.VLRPGTO, a.NUM_CONTA_REPRES
FROM PGTO_CLIENTE a, tbATENDIMENTOPEDIDO p
where a.pedido = p.idpedido
and a.nf = p.nf;

create table tbroteirovendedor (
idroteiro integer not null,
idvendedor integer not null,
descricao varchar(45) not null,
primary key (idroteiro)
);

alter table tbroteirovendedor add constraint fkroteirovendedor1 foreign key (idvendedor) references tbvendedor (idvendedor);

INSERT INTO TBROTEIROVENDEDOR SELECT ROTEIRO, VENDEDOR, DESCRICAO FROM ROTEIROVENDEDOR;

create table tbroteirocliente (
idroteiro integer not null,
idcliente integer not null,
primary key (idroteiro, idcliente)
);
commit;

alter table tbroteirocliente add constraint fkroteirocliente1 foreign key
(idroteiro) references tbroteirovendedor (idroteiro);

alter table tbroteirocliente add constraint fkroteirocliente2 foreign key
(idcliente) references tbcliente (idcliente);

INSERT INTO TBROTEIROCLIENTE SELECT ROTEIRO, CLIENTE FROM ROTEIROCLIENTE;

commit;

create table tbcontabil (
  idcontabil integer not null,
  idtipo integer not null,
  numAno integer not null,
  numMes integer not null,
  descricao varchar(50) not null,
  compromisso varchar(50),
  valor numeric(15,2),
  dtvencimento timestamp,
  primary key (idcontabil)
);

CREATE INDEX IDXCONTABIL1 ON TBContabil(numAno, numMes);

CREATE SEQUENCE TBCONTABIL_IDCONTABIL_SEQ;
CREATE SEQUENCE TBMENSAGEM_IDMENSAGEM_SEQ;
CREATE SEQUENCE TBCORREIO_IDMENSAGEM_SEQ;
CREATE SEQUENCE TBCONTA_IDCONTA_SEQ;
CREATE SEQUENCE TBVENDEDOR_IDVENDEDOR_SEQ;
CREATE SEQUENCE TBSITCLIENTE_IDSITCLIENTE_SEQ;
CREATE SEQUENCE TBSEGMERCADO_IDSEGMENTO_SEQ;
CREATE SEQUENCE TBCLIENTE_IDCLIENTE_SEQ;
CREATE SEQUENCE TBCOMPRADOR_IDCOMPRADOR_SEQ;
CREATE SEQUENCE TBGRUPOCLIENTE_IDGRPCLIENTE_SEQ;
CREATE SEQUENCE TBGRUPOPRODUTO_IDCODGRUPO_SEQ;
CREATE SEQUENCE TBSUBGRUPOPRD_IDCODSUBGRUPO_SEQ;
CREATE SEQUENCE TBREPRES_IDREPRES_SEQ;
CREATE SEQUENCE TBCONTATOVENDEDOR_IDCONTATO_SEQ;
CREATE SEQUENCE TBVENDEDORREPRES_IDVENDEDOR_SEQ;
CREATE SEQUENCE TBCONTAREPRES_IDCONTAREPRES_SEQ;
CREATE SEQUENCE TBENTRADAREPRES_IDENTRADA_SEQ;
CREATE SEQUENCE TBTRANSPORTADOR_IDTRANS_SEQ;
CREATE SEQUENCE TBPGTOCLIENTE_IDPGTOCLIENTE_SEQ;
CREATE SEQUENCE TBROTEIROVENDEDOR_IDROTEIRO_SEQ;
CREATE SEQUENCE TBPEDIDO_IDPEDIDO_SEQ;
CREATE SEQUENCE TBORCAMENTO_IDORCAMENTO_SEQ;
CREATE SEQUENCE TBPRODUTO_IDPRODUTO_SEQ;
CREATE SEQUENCE TBUSER_IDUSER_SEQ;
CREATE SEQUENCE TBPLANOCONTA_IDCONTA_SEQ;
CREATE SEQUENCE TBARECEBER_IDCOMPROMISSO_SEQ;
CREATE SEQUENCE TBAPAGAR_IDCOMPROMISSO_SEQ;
CREATE SEQUENCE TBTPPGTOFINANC_IDTIPOPGTO_seq;
CREATE SEQUENCE TBARQUIVOPEDIDO_IDARQUIVO_SEQ;
CREATE SEQUENCE TBARQORCAMENTO_IDARQUIVO_SEQ;
CREATE SEQUENCE TBREFCLIENTE_IDREFERENCIA_SEQ;
CREATE SEQUENCE TBBANCOREFCLI_IDREFERENCIA_SEQ;
CREATE SEQUENCE TBREFERENCIA_IDREFERENCIA_SEQ;
CREATE SEQUENCE TBARQUIVOPRECO_IDARQUIVO_SEQ;
CREATE SEQUENCE TBPEDIDOEMBRQ_IDPEDIDOEMBRQ_SEQ;
CREATE SEQUENCE TBCONTABIL_IDCONTABIL_SEQ;


create table TBTIPOPGTOFINANCEIRO (
  idtipopgto integer not null,
  idvendedor integer not null,
  nome varchar(40) not null,
  primary key (idtipopgto)
);

ALTER TABLE TBTIPOPGTOFINANCEIRO ADD CONSTRAINT FKTIPOPGTOFINANCEIRO1 FOREIGN KEY (IDVENDEDOR) REFERENCES TBVENDEDOR (IDVENDEDOR);

CREATE INDEX IDXTBTIPOPGTOFINANCEIRO1 ON TBTIPOPGTOFINANCEIRO(IDVENDEDOR);

create table tbplanoconta (
  idconta int not null,
  idvendedor int not null,
  nome varchar(40) not null,
  tipo smallint not null,
  grupo smallint not null,
  idcontamaster int,
  primary key (idconta)
);

ALTER TABLE TBPLANOCONTA ADD CONSTRAINT FKPLANOCONTA1 FOREIGN KEY (IDCONTAMASTER) REFERENCES TBPLANOCONTA (IDCONTA);
ALTER TABLE TBPLANOCONTA ADD CONSTRAINT FKPLANOCONTA2 FOREIGN KEY (IDVENDEDOR) REFERENCES TBVENDEDOR (IDVENDEDOR);

CREATE INDEX IDXPLANOCONTA1 ON TBPLANOCONTA(IDVENDEDOR);

CREATE TABle tbareceber (
  idcompromisso int not null,
  dtvencimento timestamp not null,
  valor numeric (10,2) not null,
  dtpgto timestamp,
  idconta int not null,
  idtipopgto int not null,
  observacao varchar(512),
  primary key (idcompromisso)
);

ALTER TABLE TBARECEBER ADD CONSTRAINT FKARECEBER1 FOREIGN KEY (IDCONTA) REFERENCES TBPLANOCONTA (IDCONTA);
ALTER TABLE TBARECEBER ADD CONSTRAINT FKARECEBER2 FOREIGN KEY (IDTIPOPGTO) REFERENCES TBTIPOPGTOFINANCEIRO (IDTIPOPGTO);

CREATE TABle tbapagar (
  idcompromisso int not null,
  dtvencimento timestamp not null,
  valor numeric (10,2) not null,
  dtpgto timestamp,
  idconta int not null,
  idtipopgto int not null,
  observacao varchar(512),
  primary key (idcompromisso)
);

ALTER TABLE TBAPAGAR ADD CONSTRAINT FKAPAGAR1 FOREIGN KEY (IDCONTA) REFERENCES TBPLANOCONTA (IDCONTA);
ALTER TABLE TBAPAGAR ADD CONSTRAINT FKAPAGAR2 FOREIGN KEY (IDTIPOPGTO) REFERENCES TBTIPOPGTOFINANCEIRO (IDTIPOPGTO);

alter table tbcorreio add constraint fkcorreio1 foreign key (idorigem) references tbuser (username)
alter table tbcorreio add constraint fkcorreio2 foreign key (iddestino) references tbuser (username)

create table tbcontafluxo (
   idconta integer not null,
   idvendedor integer not null,
   nome varchar(100) not null,
   obs BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   primary key (idconta)
);

create index idxcontafluxo1 on tbcontafluxo(nome);
create index idxcontafluxo2 on tbcontafluxo(idvendedor, idconta);

CREATE SEQUENCE TBCONTAFLUXO_IDCONTA_SEQ;

alter table tbcontafluxo add constraint fkmcontafluxo1 foreign key (idvendedor) references tbvendedor (idvendedor);


create table tbmovimento (
   idmovimento integer not null,
   idvendedor integer not null,
   idconta integer not null,
   dtmov timestamp not null,
   documento varchar(100),
   descricao BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   tipo char not null,
   valor numeric(10,2) not null,
   obs BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   primary key (idmovimento)
);

CREATE SEQUENCE TBMOVIMENTO_IDMOVIMENTO_SEQ;

alter table tbmovimento add constraint fkmovimento1 foreign key (idconta) references tbcontafluxo (idconta);
alter table tbmovimento add constraint fkmovimento2 foreign key (idvendedor) references tbvendedor (idvendedor);

CREATE INDEX IDXMOVIMENTO1 ON TBMOVIMENTO(IDVENDEDOR, IDCONTA, DTMOV, TIPO);
CREATE INDEX IDXMOVIMENTO2 ON TBMOVIMENTO(IDVENDEDOR, DTMOV);

set generator TBCONTAFLUXO_IDCONTA_SEQ to 0;

CREATE SEQUENCE TBAGENDA_IDAGENDA_SEQ;

insert into tbcontafluxo (idconta,nome) values (gen_id(TBCONTAFLUXO_IDCONTA_SEQ, 1), 'BBrasil Ag.1235-1  C/C 5074-1');
insert into tbcontafluxo (idconta,nome) values (gen_id(TBCONTAFLUXO_IDCONTA_SEQ, 1), 'Banco Itau Ag 0654   CC 02900-8');
insert into tbcontafluxo (idconta,nome) values (gen_id(TBCONTAFLUXO_IDCONTA_SEQ, 1), 'Ag 0654 C/C 65482-1');
insert into tbcontafluxo (idconta,nome) values (gen_id(TBCONTAFLUXO_IDCONTA_SEQ, 1), 'Ag 0879-6 C/C 44799-4');
insert into tbcontafluxo (idconta,nome) values (gen_id(TBCONTAFLUXO_IDCONTA_SEQ, 1), 'Bradesco Ag. 0879-6 C/C 44440-5');

--

CREATE TABLE TBCOLABORADOR (
   IDCOLABORADOR INTEGER  NOT NULL,
   NOME VARCHAR(100) NOT NULL,
   RAZAO VARCHAR(100),
   site varchar(100),
   ENDERECO VARCHAR(60),
   BAIRRO VARCHAR(25),
   CIDADE VARCHAR(30),
   CEP VARCHAR(8),
   UF VARCHAR(2),
   CNPJ VARCHAR(14),
   CPF VARCHAR(11),
   INSEST VARCHAR(18),
   FONE1 VARCHAR(12),
   FONE2 VARCHAR(12),
   FONE3 VARCHAR(12),
   DTINCLUS TIMESTAMP,
   DTULTVISITA TIMESTAMP,
   idfuncao integer,
   email varchar(100),
   FOTO BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   OBSERVACAO BLOB SUB_TYPE 1 SEGMENT SIZE 80,
   PRIMARY KEY (IDCOLABORADOR)
);

create table tbfuncaocolaborador (
	idfuncao integer not null,
	nome varchar(50) not null,
	primary key (idfuncao)
);

insert into tbfuncaocolaborador (idfuncao, nome) values (1, 'Arquiteto');
insert into tbfuncaocolaborador (idfuncao, nome) values (2, 'Designer');
insert into tbfuncaocolaborador (idfuncao, nome) values (3, 'Especificador');
insert into tbfuncaocolaborador (idfuncao, nome) values (4, 'Outro');

create sequence TBCOLABORADOR_ID_FUNCAO_SEQ;

alter table TBCOLABORADOR add constraint fk_colaborador_funcao foreign key (idfuncao) references tbfuncaocolaborador (idfuncao);

--

set generator TBCONTAFLUXO_IDCONTA_SEQ to 6;

alter table tbcontafluxo add idvendedor integer not null;

create index idxcontafluxo2 on tbcontafluxo(idvendedor, idconta);

update tbcontafluxo set idvendedor = 1;

alter table tbmovimento add idvendedor integer not null;

drop index idxmovimento1;
drop index idxmovimento2;

update tbmovimento set idvendedor = 1;

CREATE INDEX IDXMOVIMENTO1 ON TBMOVIMENTO(IDVENDEDOR, IDCONTA, DTMOV, TIPO);
CREATE INDEX IDXMOVIMENTO2 ON TBMOVIMENTO(IDVENDEDOR, DTMOV);

alter table tbmovimento add constraint fkmovimento2 foreign key (idvendedor) references tbvendedor (idvendedor);



/*
connect /Users/sam/Databases/vendas.fdb user "sysdba" password "masterkey";
select 1, 'tbmensagem', max(idmensagem) from tbmensagem union
select 2, 'tbconta', max(idconta) from tbonta union
select 3, 'tbvendedor', max(idvendedor) from tbvendedor union
select 4, 'tbsitcliente', max(idsitcliente) from tbsitcliente union
select 5, 'tbsegmercado', max(idsegmento) from tbsegmercado union
select 6, 'tbcliente', max(idcliente) from tbcliente union
select 7, 'tbcomprador', max(idcomprador) from tbcomprador union
select 8, 'tbgrupocliente', max(idgrpcliente) from tbgrupocliente union
select 9, 'tbgrupoproduto', max(idcodgrupo) from tbgrupoproduto union
select 10, 'tbrepres', max(idrepres) from tbrepres union
select 11, 'tbvendedorrepres', max(idvendedor) from tbvendedorrepres union
select 12, 'tbcontarepres', max(idcontarepres) from tbcontarepres union
select 13, 'tbentradarepres', max(identrada) from tbentradarepres union
select 14, 'tbtransportador', max(idtrans) from tbtransportador union
select 15, 'tbpgtocliente', max(idpgtocliente) from tbpgtocliente union
select 16, 'tbpedido', max(idpedido) from tbpedido union
select 17, 'tbroteirovendedor', max(idroteiro) from tbroteirovendedor;

SET GENERATOR TBARQUIVOPEDIDO_IDARQUIVO_SEQ TO 1;
set generator TBMENSAGEM_IDMENSAGEM_SEQ to 1;
set generator TBCONTA_IDCONTA_SEQ to 2;
set generator TBVENDEDOR_IDVENDEDOR_SEQ to 27;
set generator TBSITCLIENTE_IDSITCLIENTE_SEQ to 9;
set generator TBSEGMERCADO_IDSEGMENTO_SEQ to 25;
set generator TBCLIENTE_IDCLIENTE_SEQ to 1514;
set generator TBCOMPRADOR_IDCOMPRADOR_SEQ to 1879;
set generator TBGRUPOCLIENTE_IDGRPCLIENTE_SEQ to 62;
set generator TBGRUPOPRODUTO_IDCODGRUPO_SEQ to 131;
set generator TBREPRES_IDREPRES_SEQ to 197;
set generator TBVENDEDORREPRES_IDVENDEDOR_SEQ to 195;
set generator TBCONTAREPRES_IDCONTAREPRES_SEQ to 222;
set generator TBENTRADAREPRES_IDENTRADA_SEQ to 4898;
set generator TBTRANSPORTADOR_IDTRANS_SEQ to 111;
set generator TBPGTOCLIENTE_IDPGTOCLIENTE_SEQ to 11540;
set generator TBPEDIDO_IDPEDIDO_SEQ to 200019422;
set generator TBPRODUTO_IDPRODUTO_SEQ to 21000400;
set generator TBROTEIROVENDEDOR_IDROTEIRO_SEQ to 24;
commit;
*/

DROP TABLE AGENCIA;
DROP TABLE ATENDIMENTO_PEDIDO;
DROP TABLE BANCO;
DROP TABLE CLIENTE;
DROP TABLE CLIENTE_GRUPO;
DROP TABLE CLIENTE_REPRES;
DROP TABLE COMPRADOR_CLIENTE;
DROP TABLE CONTATOS;
DROP TABLE CONTA_EMPRESA;
DROP TABLE CONTA_REPRES;
DROP TABLE EMPRESAS;
DROP TABLE ENTRADA_REPRES;
DROP TABLE FORMA_PGTO;
DROP TABLE FORMA_PGTO_REPRES;
DROP TABLE FUNCOES;
DROP TABLE GRUPOPRODUTO;
DROP TABLE GRUPO_CLIENTE;
DROP TABLE GRUPO_CLIENTES;
DROP TABLE ITEM_PEDIDO;
DROP TABLE ITEM_PEDIDO_ATEND;
DROP TABLE ITEM_ROMANEIO;
DROP TABLE MENSAGEM;
DROP TABLE PARAMS;
DROP TABLE PEDIDO;
DROP TABLE PGTO_CLIENTE;
DROP TABLE PGTO_ROMANEIO;
DROP TABLE PRODUTO;
DROP TABLE REPRES;
DROP TABLE REPRES_PRODUTO;
DROP TABLE ROMANEIO;
DROP TABLE SEGMENTO_CLIENTE;
DROP TABLE SEGMENTO_MERCADO;
DROP TABLE SEGMENTO_REPRES;
DROP TABLE SITUACAO_CLIENTE;
DROP TABLE TIPOPGTO;
DROP TABLE TRANSPORTADOR;
DROP TABLE UNIDADE_PRODUTO;
DROP TABLE VENDEDOR;
DROP TABLE VENDEDOR_REPRES;
DROP TABLE VISITA_CLIENTE;
DROP TABLE ROTEIROVENDEDOR;
DROP TABLE ROTEIROCLIENTE;
DROP TABLE PLANOCONTA;
DROP TABLE ENDERECOCLIENTE;
DROP TABLE CONTASARECEBER;
DROP TABLE CONTASAPAGAR;
DROP TABLE COMISSAOREPRES;

SET TERM ^ ; 
create procedure dateadd(mes integer, curr timestamp) returns (newdate 
timestamp) as
declare omes integer;
declare ano integer;
begin

omes = extract(month from curr) + mes;
ano = extract(year from curr);

if (omes < 1) then begin
  omes = omes + 12;
  ano = ano - 1;
end

newdate = cast( cast(omes as varchar(2)) || '/01/' || cast(ano as 
varchar(4)) as timestamp);
suspend;

end ^
SET TERM ; ^

commit;

