/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserForm.java
 *
 * Created on Nov 26, 2011, 11:00:23 AM
 */
package vendas.security;

import java.util.ArrayList;
import java.util.List;
import ritual.swing.ListComboBoxModel;
import ritual.swing.TApplication;
import vendas.dao.VendedorDao;
import vendas.entity.Perfil;
import vendas.entity.User;
import vendas.entity.Vendedor;
import vendas.swing.core.EditPanel;
import vendas.util.Constants;

/**
 *
 * @author sam
 */
public class UserForm extends EditPanel {
    
     VendedorDao vendedorDao;

    /** Creates new form UserForm */
    public UserForm() {
        initComponents();
        List<String>perfis = new ArrayList<String>();
        perfis.add(Constants.ADMIN);
        perfis.add(Constants.ESCRITORIO);
        perfis.add(Constants.VENDEDOR);
        perfilComboBox.setModel(new ListComboBoxModel(perfis));
        vendedorDao = (VendedorDao) TApplication.getInstance().lookupService("vendedorDao");
        vendedorComboBox.setModel(new ListComboBoxModel(vendedorDao.findAllAtivos()));
    }
    
    @Override
    public void object2Field(Object obj) {
        User user = (User) obj;
        nomeTextField.setText(user.getUserName());
        senhaField.setText(null);
        if (user.getPerfis() != null && !user.getPerfis().isEmpty()) {
            perfilComboBox.setSelectedItem(user.getPerfis().get(0).getPerfil());
        }
        
        if (user.getIdvendedor() != null) {
            try {
                vendedorComboBox.setSelectedItem(vendedorDao.findById(Vendedor.class, user.getIdvendedor()));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    
    @Override
    public void field2Object(Object obj) {
        User user = (User) obj;
        user.setUserName(nomeTextField.getText().toUpperCase());
        Perfil perfil = null;
        try {
            perfil = (Perfil)vendedorDao.findById(Perfil.class, (String)perfilComboBox.getModel().getSelectedItem());
        } catch (Exception e) {
            
        }
        user.addPerfil(perfil);
        Vendedor vendedor = (Vendedor)vendedorComboBox.getModel().getSelectedItem();
        user.setIdvendedor(vendedor.getIdVendedor());
        String s = new String(senhaField.getPassword());
        if (s != null && s.length() > 0)
            try {
                user.setPasswd(Crypt.encrypt(nomeTextField.getText(), new String(senhaField.getPassword())));
            } catch (Exception e) {
                e.printStackTrace();
            }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JFormattedTextField();
        senhaField = new javax.swing.JPasswordField();
        perfilComboBox = new javax.swing.JComboBox();
        vendedorComboBox = new javax.swing.JComboBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("nome")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(bundle.getString("senha")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(bundle.getString("perfil")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(bundle.getString("vendedor")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        nomeTextField.setName("nomeTextField"); // NOI18N

        senhaField.setName("senhaField"); // NOI18N

        perfilComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        perfilComboBox.setName("perfilComboBox"); // NOI18N

        vendedorComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        vendedorComboBox.setName("vendedorComboBox"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(layout.createSequentialGroup()
                        .add(jLabel3)
                        .add(61, 61, 61)
                        .add(perfilComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel4)
                        .add(34, 34, 34)
                        .add(vendedorComboBox, 0, 270, Short.MAX_VALUE))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                            .add(jLabel2)
                            .add(56, 56, 56)
                            .add(senhaField))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                            .add(93, 93, 93)
                            .add(nomeTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(nomeTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(senhaField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(perfilComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(vendedorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JFormattedTextField nomeTextField;
    private javax.swing.JComboBox perfilComboBox;
    private javax.swing.JPasswordField senhaField;
    private javax.swing.JComboBox vendedorComboBox;
    // End of variables declaration//GEN-END:variables
}
