/*
 * ClienteRepresPanel.java
 *
 * Created on 30 de Novembro de 2007, 22:15
 */
package vendas.swing.app.repres;

import vendas.beans.ClientesFilter;
import vendas.entity.Repres;
import vendas.entity.Vendedor;
import vendas.swing.core.EditPanel;
import ritual.swing.BoundedPlainDocument;
import ritual.swing.TApplication;
import ritual.util.DateUtils;
import vendas.dao.VendedorDao;
import vendas.entity.SegMercado;
import vendas.util.Constants;
import vendas.util.VendasUtil;

/**
 *
 * @author  Sam
 */
public class ClienteRepresPanel extends EditPanel {

    /** Creates new form ClienteRepresPanel */
    public ClienteRepresPanel() {
        initComponents();
    }

    @Override
    public void init() {
        represComboBox.setModel(VendasUtil.getRepresListModel(true));
        vendedorComboBox.setModel(VendasUtil.getVendedoresListModel());
        segmentoComboBox.setModel(VendasUtil.getSegMercadoListModel());
        TApplication app = TApplication.getInstance();
        if (app.getUser().isVendedor()) {
            VendedorDao dao = (VendedorDao) app.lookupService("vendedorDao");
            try {
                vendedorComboBox.setSelectedItem(dao.findById(Vendedor.class, app.getUser().getIdvendedor()));
                vendedorComboBox.setEnabled(false);
            } catch (Exception e) {
                getLogger().error(e);
            }
        }
    }

    @Override
    public void object2Field(Object obj) {
    }

    @Override
    public void field2Object(Object obj) {
        ClientesFilter filtro = (ClientesFilter) obj;
        if (dtInclusaoIniField.getDate() != null) {
            filtro.setDtInclusaoIni(DateUtils.parse(DateUtils.format(dtInclusaoIniField.getDate())));
            filtro.setDtInclusaoEnd(DateUtils.parse(DateUtils.format(dtInclusaoEndField.getDate())));
        }
        if (dtPedidoIniField.getDate() != null) {
            filtro.setDtPedidoIni(DateUtils.parse(DateUtils.format(dtPedidoIniField.getDate())));
            filtro.setDtPedidoEnd(DateUtils.parse(DateUtils.format(dtPedidoEndField.getDate())));
        }
        filtro.setRepres((Repres) represComboBox.getModel().getSelectedItem());
        if (filtro.getRepres() != null && filtro.getRepres().getIdRepres() != null) {
            filtro.setTitle(filtro.getRepres().getRazao());
        }
        filtro.setVendedor((Vendedor) vendedorComboBox.getModel().getSelectedItem());
        filtro.setSegmento((SegMercado) segmentoComboBox.getModel().getSelectedItem());
        filtro.getCliente().setCidade(cidadeField.getText());
        if (codigoCheckBox.isSelected()) {
            filtro.setOrder(0);
        } else {
            filtro.setOrder(1);
        }
        if (disabledCheckBox.isSelected()) {
            filtro.setPedidoDesabilitado(true);
        } else {
            filtro.setPedidoDesabilitado(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        represComboBox = new javax.swing.JComboBox();
        disabledCheckBox = new javax.swing.JCheckBox();
        codigoCheckBox = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        dtInclusaoIniField = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        dtInclusaoEndField = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        cidadeField = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        vendedorComboBox = new javax.swing.JComboBox();
        dtPedidoEndField = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        dtPedidoIniField = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        segmentoComboBox = new javax.swing.JComboBox();

        setName("Form"); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel13.setText(bundle.getString("representada")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        represComboBox.setName("represComboBox"); // NOI18N

        disabledCheckBox.setText(bundle.getString("pedidoDesabilitado")); // NOI18N
        disabledCheckBox.setName("disabledCheckBox"); // NOI18N

        codigoCheckBox.setText(bundle.getString("ordenarCodigo")); // NOI18N
        codigoCheckBox.setName("codigoCheckBox"); // NOI18N

        jLabel14.setText(bundle.getString("dtInclusao")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ClienteRepresPanel.class);
        dtInclusaoIniField.setDateFormatString(resourceMap.getString("dtInclusaoIniField.dateFormatString")); // NOI18N
        dtInclusaoIniField.setName("dtInclusaoIniField"); // NOI18N

        jLabel15.setText(bundle.getString("para")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        dtInclusaoEndField.setDateFormatString(resourceMap.getString("dtInclusaoEndField.dateFormatString")); // NOI18N
        dtInclusaoEndField.setName("dtInclusaoEndField"); // NOI18N

        jLabel6.setText(bundle.getString("cidade")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        cidadeField.setDocument(new BoundedPlainDocument(30));
        cidadeField.setName("cidadeField"); // NOI18N

        jLabel8.setText(bundle.getString("vendedor")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        vendedorComboBox.setName("vendedorComboBox"); // NOI18N

        dtPedidoEndField.setDateFormatString(resourceMap.getString("dtPedidoEndField.dateFormatString")); // NOI18N
        dtPedidoEndField.setName("dtPedidoEndField"); // NOI18N

        jLabel16.setText(bundle.getString("para")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        dtPedidoIniField.setDateFormatString(resourceMap.getString("dtPedidoIniField.dateFormatString")); // NOI18N
        dtPedidoIniField.setName("dtPedidoIniField"); // NOI18N

        jLabel17.setText(bundle.getString("dtPedido")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel9.setText(bundle.getString("segmento")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        segmentoComboBox.setName("segmentoComboBox"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(disabledCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(codigoCheckBox))
                    .addComponent(jLabel13)
                    .addComponent(represComboBox, 0, 468, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(dtInclusaoIniField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addGap(10, 10, 10)
                        .addComponent(dtInclusaoEndField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(76, 76, 76))
                            .addComponent(cidadeField, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)))
                    .addComponent(jLabel8)
                    .addComponent(vendedorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(dtPedidoIniField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addGap(10, 10, 10)
                        .addComponent(dtPedidoEndField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addComponent(segmentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(represComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disabledCheckBox)
                    .addComponent(codigoCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtInclusaoIniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dtInclusaoEndField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtPedidoIniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dtPedidoEndField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vendedorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(segmentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField cidadeField;
    private javax.swing.JCheckBox codigoCheckBox;
    private javax.swing.JCheckBox disabledCheckBox;
    private com.toedter.calendar.JDateChooser dtInclusaoEndField;
    private com.toedter.calendar.JDateChooser dtInclusaoIniField;
    private com.toedter.calendar.JDateChooser dtPedidoEndField;
    private com.toedter.calendar.JDateChooser dtPedidoIniField;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox represComboBox;
    private javax.swing.JComboBox segmentoComboBox;
    private javax.swing.JComboBox vendedorComboBox;
    // End of variables declaration//GEN-END:variables
}
