/*
 * ContaRepresPanel.java
 *
 * Created on 22 de Julho de 2007, 22:37
 */

package vendas.swing.app.repres;

import java.util.List;
import vendas.entity.Banco;
import vendas.entity.ContaRepres;
import vendas.swing.core.EditPanel;
import ritual.swing.BoundedPlainDocument;
import ritual.swing.ListComboBoxModel;

/**
 *
 * @author  Sam
 */
public class ContaRepresPanel extends EditPanel {
    
    /** Creates new form ContaRepresPanel */
    public ContaRepresPanel() {
        initComponents();
    }
    
    public void setBanco(List lista) {
        bancoComboBox.setModel(new ListComboBoxModel(lista));
    }    
        
    @Override
    public void object2Field(Object obj) {
        ContaRepres conta = (ContaRepres) obj;        
        agenciaField.setText(conta.getAgencia());
        bancoComboBox.setSelectedItem(conta.getBanco());
        tipoComboBox.setSelectedItem(conta.getTipoConta());
        contaField.setText(conta.getContaCorrente());
        nomeField.setText(conta.getNome());
        cpfCnpjField.setText(conta.getCpfCnpj());
        ativoCheckBox.setSelected(conta.isAtivo());
    }
    
    @Override
    public void field2Object(Object obj) {
        ContaRepres conta = (ContaRepres) obj;        
        conta.setAgencia(agenciaField.getText());
        Banco banco = (Banco)bancoComboBox.getModel().getSelectedItem();
        conta.setBanco(banco);
        conta.setContaCorrente(contaField.getText());
        conta.setNome(nomeField.getText());
        conta.setCpfCnpj(cpfCnpjField.getText());
        conta.setAtivo(ativoCheckBox.isSelected());
        conta.setTipoConta((String)tipoComboBox.getModel().getSelectedItem());
        System.out.println(conta.getTipoConta());
    }        
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        tipoComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        bancoComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        agenciaField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        contaField = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        nomeField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        cpfCnpjField = new javax.swing.JFormattedTextField();
        ativoCheckBox = new javax.swing.JCheckBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/swing/app/repres/Bundle"); // NOI18N
        jLabel6.setText(bundle.getString("ContaRepresPanel.jLabel6.text")); // NOI18N

        tipoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Conta corrente", "PIX" }));
        tipoComboBox.setActionCommand(bundle.getString("ContaRepresPanel.tipoComboBox.actionCommand")); // NOI18N

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle1.getString("banco")); // NOI18N

        jLabel2.setText(bundle1.getString("agencia")); // NOI18N

        jLabel3.setText(bundle1.getString("contaCorrente")); // NOI18N

        jLabel4.setText(bundle1.getString("nome")); // NOI18N

        nomeField.setDocument(new BoundedPlainDocument(40));

        jLabel5.setText(bundle1.getString("cpfcnpj")); // NOI18N

        cpfCnpjField.setDocument(new BoundedPlainDocument(40));

        ativoCheckBox.setText(bundle1.getString("ativo")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeField, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(contaField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bancoComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cpfCnpjField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ativoCheckBox))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(agenciaField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bancoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agenciaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfCnpjField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ativoCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField agenciaField;
    private javax.swing.JCheckBox ativoCheckBox;
    private javax.swing.JComboBox bancoComboBox;
    private javax.swing.JFormattedTextField contaField;
    private javax.swing.JFormattedTextField cpfCnpjField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JFormattedTextField nomeField;
    private javax.swing.JComboBox tipoComboBox;
    // End of variables declaration//GEN-END:variables
    
}
