/*
 * FormaPgtoRepresPanel.java
 *
 * Created on 22 de Julho de 2007, 20:32
 */

package vendas.swing.app.repres;

import java.util.List;
import ritual.swing.ListComboBoxModel;
import vendas.entity.FormaPgto;
import vendas.entity.FormaPgtoRepres;
import vendas.swing.core.EditPanel;

/**
 *
 * @author  Sam
 */
public class FormaPgtoRepresPanel extends EditPanel {
    
    /** Creates new form FormaPgtoRepresPanel */
    public FormaPgtoRepresPanel() {
        initComponents();
    }
    
    public void setFormaPgto(List lista) {
        formaPgtoComboBox.setModel(new ListComboBoxModel(lista));
    }
    
    @Override
    public void object2Field(Object obj) {
        FormaPgtoRepres formaPgto = (FormaPgtoRepres) obj;        
        disponibilidadeField.setText(formaPgto.getDisponibilidade());
        entregaField.setText(formaPgto.getEntrega());
        formaPgtoComboBox.setSelectedItem(formaPgto.getFormaPgto());
        freteField.setText(formaPgto.getFrete());
        icmsField.setText(formaPgto.getIcms());
        ipiField.setText(formaPgto.getIpi());
        observacaoField.setText(formaPgto.getObs());
        pedidoMinimoField.setText(formaPgto.getPedidoMinimo());
        percentualField.setText(formaPgto.getPercentualNota());
        pgtoFreteField.setText(formaPgto.getPgtoFrete());
        procedenciaField.setText(formaPgto.getProcedencia());
    }
    
    @Override
    public void field2Object(Object obj) {
        FormaPgtoRepres formaPgtoRepres = (FormaPgtoRepres) obj;        
        FormaPgto formaPgto;
        formaPgtoRepres.setDisponibilidade(disponibilidadeField.getText());
        formaPgtoRepres.setEntrega(entregaField.getText());
        formaPgto = (FormaPgto)formaPgtoComboBox.getModel().getSelectedItem();
        formaPgtoRepres.setFormaPgto(formaPgto);
        formaPgtoRepres.getFormaPgtoRepresPK().setIdPgto(formaPgto.getIdPgto());
        formaPgtoRepres.setFrete(freteField.getText());
        formaPgtoRepres.setIcms(icmsField.getText());
        formaPgtoRepres.setIpi(ipiField.getText());
        formaPgtoRepres.setObs(observacaoField.getText());
        formaPgtoRepres.setPedidoMinimo(pedidoMinimoField.getText());
        formaPgtoRepres.setPercentualNota(percentualField.getText());
        formaPgtoRepres.setPgtoFrete(pgtoFreteField.getText());
        formaPgtoRepres.setProcedencia(procedenciaField.getText());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formaPgtoLabel = new javax.swing.JLabel();
        formaPgtoComboBox = new javax.swing.JComboBox();
        entregaLabel = new javax.swing.JLabel();
        entregaField = new javax.swing.JFormattedTextField();
        freteLabel = new javax.swing.JLabel();
        freteField = new javax.swing.JFormattedTextField();
        pgtoFreteLabel = new javax.swing.JLabel();
        pgtoFreteField = new javax.swing.JFormattedTextField();
        disponibilidadeLabel = new javax.swing.JLabel();
        disponibilidadeField = new javax.swing.JFormattedTextField();
        icmsLabel = new javax.swing.JLabel();
        icmsField = new javax.swing.JFormattedTextField();
        ipiLabel = new javax.swing.JLabel();
        ipiField = new javax.swing.JFormattedTextField();
        pedidoMinimoLabel = new javax.swing.JLabel();
        pedidoMinimoField = new javax.swing.JFormattedTextField();
        procedenciaLabel = new javax.swing.JLabel();
        procedenciaField = new javax.swing.JFormattedTextField();
        percentualLabel = new javax.swing.JLabel();
        percentualField = new javax.swing.JFormattedTextField();
        observacaoLabel = new javax.swing.JLabel();
        observacaoField = new javax.swing.JFormattedTextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        formaPgtoLabel.setText(bundle.getString("formaPgto")); // NOI18N

        entregaLabel.setText(bundle.getString("dtEntrega")); // NOI18N

        freteLabel.setText(bundle.getString("frete")); // NOI18N

        pgtoFreteLabel.setText(bundle.getString("pgtoFrete")); // NOI18N

        disponibilidadeLabel.setText(bundle.getString("disponibilidade")); // NOI18N

        icmsLabel.setText(bundle.getString("icms")); // NOI18N

        ipiLabel.setText(bundle.getString("ipi")); // NOI18N

        pedidoMinimoLabel.setText(bundle.getString("pedidoMinimo")); // NOI18N

        procedenciaLabel.setText(bundle.getString("procedencia")); // NOI18N

        percentualLabel.setText(bundle.getString("percentual")); // NOI18N

        observacaoLabel.setText(bundle.getString("observacao")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(freteLabel)
                            .addComponent(icmsLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(procedenciaLabel)
                                .addGap(64, 64, 64))
                            .addComponent(icmsField)
                            .addComponent(freteField, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(procedenciaField))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pgtoFreteLabel)
                                    .addComponent(ipiLabel)
                                    .addComponent(percentualLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ipiField, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(pgtoFreteField, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(percentualField, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))))
                    .addComponent(formaPgtoLabel)
                    .addComponent(formaPgtoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(observacaoLabel)
                            .addComponent(pedidoMinimoLabel)
                            .addComponent(disponibilidadeLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(entregaField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pedidoMinimoField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(disponibilidadeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entregaLabel)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(observacaoField, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formaPgtoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formaPgtoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entregaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entregaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(freteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(freteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pgtoFreteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(disponibilidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pgtoFreteLabel)
                            .addComponent(disponibilidadeLabel))
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icmsLabel)
                    .addComponent(ipiLabel)
                    .addComponent(pedidoMinimoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icmsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pedidoMinimoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(procedenciaLabel)
                            .addComponent(percentualLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(procedenciaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(percentualField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(observacaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(observacaoLabel, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField disponibilidadeField;
    private javax.swing.JLabel disponibilidadeLabel;
    private javax.swing.JFormattedTextField entregaField;
    private javax.swing.JLabel entregaLabel;
    private javax.swing.JComboBox formaPgtoComboBox;
    private javax.swing.JLabel formaPgtoLabel;
    private javax.swing.JFormattedTextField freteField;
    private javax.swing.JLabel freteLabel;
    private javax.swing.JFormattedTextField icmsField;
    private javax.swing.JLabel icmsLabel;
    private javax.swing.JFormattedTextField ipiField;
    private javax.swing.JLabel ipiLabel;
    private javax.swing.JFormattedTextField observacaoField;
    private javax.swing.JLabel observacaoLabel;
    private javax.swing.JFormattedTextField pedidoMinimoField;
    private javax.swing.JLabel pedidoMinimoLabel;
    private javax.swing.JFormattedTextField percentualField;
    private javax.swing.JLabel percentualLabel;
    private javax.swing.JFormattedTextField pgtoFreteField;
    private javax.swing.JLabel pgtoFreteLabel;
    private javax.swing.JFormattedTextField procedenciaField;
    private javax.swing.JLabel procedenciaLabel;
    // End of variables declaration//GEN-END:variables
    
}
