/*
 * VisitasPanel.java
 *
 * Created on 30 de Novembro de 2007, 20:26
 */

package vendas.swing.app.repres;

import java.util.ArrayList;
import java.util.List;
import ritual.swing.ListComboBoxModel;
import vendas.beans.RepresFilter;
import vendas.dao.RepresDao;
import ritual.swing.TApplication;
import ritual.util.DateUtils;
import vendas.entity.Repres;
import vendas.swing.core.EditPanel;
import ritual.util.DateVerifier;

/**
 *
 * @author  Sam
 */
public class RecebimentosPanel extends EditPanel {
    
    RepresDao represDao;
    DateVerifier dtVerifier = new DateVerifier(true);

    /** Creates new form VisitasPanel */
    public RecebimentosPanel() {
        initComponents();
    }

    @Override
    public void init() {
        represDao = (RepresDao)TApplication.getInstance().lookupService("represDao");
        represComboBox.setModel(new ListComboBoxModel(getRepres()));
    }

    private List getRepres() {
        List lista = new ArrayList();
        Repres repres = new Repres();
        repres.setRazao(getBundle().getString("comboTodos"));
        lista.add(repres);
        try {
            lista.addAll(represDao.findAll());
        } catch (Exception e) {
            getLogger().error(e.getMessage());
        }
        return lista;
    }

    @Override
    public void field2Object(Object obj) {
        RepresFilter filter = (RepresFilter) obj;
        filter.setDtRecebimentoIni(dtIniField.getDate());
        filter.setDtRecebimentoEnd(dtEndField.getDate());
        
        filter.setTitle(DateUtils.format(dtIniField.getDate()) + " - " + DateUtils.format(dtEndField.getDate()));
        filter.setRepres((Repres)represComboBox.getModel().getSelectedItem());
        filter.setDesc(descCheckBox.isSelected());
        if (represRadioButton.isSelected())
            filter.setOrdem(filter.RAZAO);
        else
            filter.setOrdem(filter.VALOR);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        dtIniField = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        dtEndField = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        represComboBox = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        represRadioButton = new javax.swing.JRadioButton();
        valorRadioButton = new javax.swing.JRadioButton();
        descCheckBox = new javax.swing.JCheckBox();

        setName("Form"); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel2.setText(bundle.getString("periodo")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(RecebimentosPanel.class);
        dtIniField.setDateFormatString(resourceMap.getString("dtIniField.dateFormatString")); // NOI18N
        dtIniField.setName("dtIniField"); // NOI18N

        jLabel3.setText(bundle.getString("para")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        dtEndField.setDateFormatString(resourceMap.getString("dtEndField.dateFormatString")); // NOI18N
        dtEndField.setName("dtEndField"); // NOI18N

        jLabel8.setText(bundle.getString("representada")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        represComboBox.setName("represComboBox"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ordem"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        buttonGroup1.add(represRadioButton);
        represRadioButton.setSelected(true);
        represRadioButton.setText(bundle.getString("fornecedor")); // NOI18N
        represRadioButton.setName("represRadioButton"); // NOI18N

        buttonGroup1.add(valorRadioButton);
        valorRadioButton.setText(bundle.getString("valor")); // NOI18N
        valorRadioButton.setName("valorRadioButton"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(represRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valorRadioButton))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(represRadioButton)
                    .addComponent(valorRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        descCheckBox.setText(bundle.getString("decrescente")); // NOI18N
        descCheckBox.setName("descCheckBox"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(represComboBox, 0, 334, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dtIniField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dtEndField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descCheckBox)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtIniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(dtEndField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(represComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(descCheckBox)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox descCheckBox;
    private com.toedter.calendar.JDateChooser dtEndField;
    private com.toedter.calendar.JDateChooser dtIniField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox represComboBox;
    private javax.swing.JRadioButton represRadioButton;
    private javax.swing.JRadioButton valorRadioButton;
    // End of variables declaration//GEN-END:variables
    
}
