/*
 * RepresClientePanel.java
 *
 * Created on 23 de Julho de 2007, 22:01
 */
package vendas.swing.app.repres;

import java.text.DecimalFormat;
import java.util.List;
import ritual.swing.ListComboBoxModel;
import ritual.swing.NumericPlainDocument;
import ritual.util.NumberUtils;
import vendas.entity.Cliente;
import vendas.entity.ClienteRepres;
import vendas.swing.core.EditPanel;

/**
 *
 * @author  Sam
 */
public class RepresClientePanel extends EditPanel {

    /** Creates new form RepresClientePanel */
    public RepresClientePanel() {
        initComponents();
        DecimalFormat df = new DecimalFormat("#0.00");
        limiteField.setDocument(new NumericPlainDocument(df));
    }

    public void setCliente(List cliente) {
        clienteComboBox.setModel(new ListComboBoxModel(cliente));
    }

    @Override
    public void object2Field(Object obj) {
        ClienteRepres cliente = (ClienteRepres) obj;
        codIdentField.setText(cliente.getCodIdentificador());
        codRepresField.setText(cliente.getCodRepres());
        clienteComboBox.setSelectedItem(cliente.getCliente());
        limiteField.setValue(cliente.getLimiteCredito());
    }

    @Override
    public void field2Object(Object obj) {
        ClienteRepres cliente = (ClienteRepres) obj;
        cliente.setCodIdentificador(codIdentField.getText());
        cliente.setCodRepres(codRepresField.getText());
        Cliente value = (Cliente) clienteComboBox.getModel().getSelectedItem();
        cliente.getClienteRepresPK().setIdCliente(value.getIdCliente());
        cliente.setCliente(value);
        cliente.setLimiteCredito(NumberUtils.getBigDecimal(limiteField.getValue()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        clienteComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        codIdentField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        codRepresField = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        limiteField = new javax.swing.JFormattedTextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("cliente")); // NOI18N

        jLabel2.setText(bundle.getString("identificador")); // NOI18N

        jLabel3.setText(bundle.getString("codigo")); // NOI18N

        jLabel4.setText(bundle.getString("limite")); // NOI18N

        limiteField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        limiteField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                limiteFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clienteComboBox, 0, 409, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(codIdentField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(codRepresField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(limiteField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codIdentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codRepresField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(limiteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limiteFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_limiteFieldFocusLost
        // TODO add your handling code here:
        if (limiteField.getText() == null || limiteField.getText().length() == 0)
            limiteField.setValue(null);
    }//GEN-LAST:event_limiteFieldFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox clienteComboBox;
    private javax.swing.JFormattedTextField codIdentField;
    private javax.swing.JFormattedTextField codRepresField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JFormattedTextField limiteField;
    // End of variables declaration//GEN-END:variables
}
