/*
 * RepresEditPanel.java
 *
 * Created on 30 de Junho de 2007, 11:24
 */
package vendas.swing.app.repres;

import java.text.DecimalFormat;
import vendas.entity.Repres;
import vendas.swing.core.EditPanel;
import ritual.swing.BoundedPlainDocument;
import ritual.swing.NumericPlainDocument;
import ritual.util.DateVerifier;
import ritual.util.NumberUtils;

/**
 *
 * @author  Sam
 */
public class RepresEditPanel extends EditPanel {

    /** Creates new form RepresEditPanel */
    public RepresEditPanel() {
        initComponents();
        razaoField.setDocument(new BoundedPlainDocument(50));
        try {
            ufField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU")));
        } catch (Exception e) {
        }
        DecimalFormat df = new DecimalFormat("#0.00");
        comissaoTextField.setDocument(new NumericPlainDocument(df));
        freteTextField.setDocument(new NumericPlainDocument(df));

    }

    @Override
    public void object2Field(Object obj) {
        Repres repres = (Repres) obj;
        ativoCheckBox.setSelected(repres.getAtivo().booleanValue());
        bairroField.setText(repres.getBairro());
        cepField.setText(repres.getCep());
        cidadeField.setText(repres.getCidade());
        //cnpjField.setText(StringUtils.formatarCnpj(repres.getCnpj()));
        cnpjField.setText(repres.getCnpj());
        comissaoTextField.setValue(repres.getComissao());
        dtInclusaoField.setDate(repres.getDtInclusao());
        enderecoField.setText(repres.getEndereco());
        fone1Field.setText(repres.getFone1());
        fone2Field.setText(repres.getFone2());
        fone3Field.setText(repres.getFone3());
        inscrEstField.setText(repres.getInscrEstadual());
        obsPedidoTextArea.setText(repres.getObservacao());
        obsPedidoClienteTextArea.setText(repres.getObservacaoCliente());
        obsProdutoTextArea.setText(repres.getObsProduto());
        metaVendaTextArea.setText(repres.getMetaVenda());
        razaoField.setText(repres.getRazao());
        ufField.setText(repres.getUf());
        diasTextField.setValue(repres.getDiasAtendimento());
        reduzidoField.setText((repres.getFantasia()));
        siteField.setText((repres.getSite()));
        freteTextField.setValue(repres.getValorFrete());
    }

    @Override
    public void field2Object(Object obj) {
        Repres repres = (Repres) obj;
        repres.setAtivo(ativoCheckBox.isSelected());
        repres.setBairro(bairroField.getText());
        repres.setCep(cepField.getText());
        repres.setCidade(cidadeField.getText());
        repres.setCnpj(cnpjField.getText());
        repres.setComissao(NumberUtils.getBigDecimal(comissaoTextField.getValue()));
        repres.setValorFrete(NumberUtils.getBigDecimal(freteTextField.getValue()));
        repres.setDtInclusao(dtInclusaoField.getDate());
        repres.setEndereco(enderecoField.getText());
        repres.setFone1(fone1Field.getText());
        repres.setFone2(fone2Field.getText());
        repres.setFone3(fone3Field.getText());
        repres.setInscrEstadual(inscrEstField.getText());
        repres.setObservacao(obsPedidoTextArea.getText());
        repres.setObservacaoCliente(obsPedidoClienteTextArea.getText());
        repres.setObsProduto(obsProdutoTextArea.getText());
        repres.setMetaVenda(metaVendaTextArea.getText());
        repres.setRazao(razaoField.getText());
        repres.setUf(ufField.getText());
        repres.setFantasia(reduzidoField.getText());
        repres.setSite(siteField.getText());

        if (diasTextField.getValue() == null)
            repres.setDiasAtendimento(0);
        else {
            repres.setDiasAtendimento(NumberUtils.getInteger(diasTextField.getValue()));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        razaoLabel = new javax.swing.JLabel();
        razaoField = new javax.swing.JFormattedTextField();
        bairroLabel1 = new javax.swing.JLabel();
        reduzidoField = new javax.swing.JFormattedTextField();
        siteLabel = new javax.swing.JLabel();
        siteField = new javax.swing.JFormattedTextField();
        cnpjLabel = new javax.swing.JLabel();
        cnpjField = new javax.swing.JFormattedTextField();
        inscrEstLabel = new javax.swing.JLabel();
        inscrEstField = new javax.swing.JFormattedTextField();
        dtInclusaoLabel = new javax.swing.JLabel();
        dtInclusaoField = new com.toedter.calendar.JDateChooser();
        enderecoLabel = new javax.swing.JLabel();
        enderecoField = new javax.swing.JFormattedTextField();
        bairroLabel = new javax.swing.JLabel();
        bairroField = new javax.swing.JFormattedTextField();
        cepLabel = new javax.swing.JLabel();
        cepField = new javax.swing.JFormattedTextField();
        cidadeLabel = new javax.swing.JLabel();
        cidadeField = new javax.swing.JFormattedTextField();
        ufLabel = new javax.swing.JLabel();
        ufField = new javax.swing.JFormattedTextField();
        fone1Label = new javax.swing.JLabel();
        fone1Field = new javax.swing.JFormattedTextField();
        fone2Label = new javax.swing.JLabel();
        fone2Field = new javax.swing.JFormattedTextField();
        fone3Label = new javax.swing.JLabel();
        fone3Field = new javax.swing.JFormattedTextField();
        observacaoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        obsPedidoTextArea = new javax.swing.JTextArea();
        observacaoLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        obsProdutoTextArea = new javax.swing.JTextArea();
        observacaoLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        metaVendaTextArea = new javax.swing.JTextArea();
        comissaoLabel1 = new javax.swing.JLabel();
        diasTextField = new javax.swing.JFormattedTextField();
        comissaoLabel = new javax.swing.JLabel();
        ativoCheckBox = new javax.swing.JCheckBox();
        comissaoTextField = new javax.swing.JFormattedTextField();
        comissaoLabel2 = new javax.swing.JLabel();
        freteTextField = new javax.swing.JFormattedTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        obsPedidoClienteTextArea = new javax.swing.JTextArea();
        observacaoLabel3 = new javax.swing.JLabel();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        razaoLabel.setText(bundle.getString("razaoSocial")); // NOI18N

        razaoField.setInputVerifier(new DateVerifier(true));

        bairroLabel1.setText(bundle.getString("nomeReduzido")); // NOI18N

        reduzidoField.setColumns(30);
        reduzidoField.setDocument(new BoundedPlainDocument(30));

        siteLabel.setText(bundle.getString("site")); // NOI18N

        siteField.setColumns(100);

        cnpjLabel.setText(bundle.getString("cnpj")); // NOI18N

        inscrEstLabel.setText(bundle.getString("inscrEstadual")); // NOI18N

        dtInclusaoLabel.setText(bundle.getString("dtInclusao")); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(RepresEditPanel.class);
        dtInclusaoField.setDateFormatString(resourceMap.getString("dtInclusaoField.dateFormatString")); // NOI18N

        enderecoLabel.setText(bundle.getString("endereco")); // NOI18N

        enderecoField.setColumns(40);
        enderecoField.setDocument(new BoundedPlainDocument(40));

        bairroLabel.setText(bundle.getString("bairro")); // NOI18N

        bairroField.setColumns(30);
        bairroField.setDocument(new BoundedPlainDocument(30));

        cepLabel.setText(bundle.getString("cep")); // NOI18N

        cepField.setColumns(8);
        cepField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("########"))));

        cidadeLabel.setText(bundle.getString("cidade")); // NOI18N

        cidadeField.setColumns(30);
        cidadeField.setDocument(new BoundedPlainDocument(30));

        ufLabel.setText(bundle.getString("uf")); // NOI18N

        ufField.setColumns(2);
        ufField.setDocument(new BoundedPlainDocument(2));

        fone1Label.setText(bundle.getString("fone1")); // NOI18N

        fone1Field.setColumns(12);

        fone2Label.setText(bundle.getString("fone2")); // NOI18N

        fone2Field.setColumns(12);

        fone3Label.setText(bundle.getString("fone3")); // NOI18N

        fone3Field.setColumns(12);

        observacaoLabel.setText(bundle.getString("obsPedidoFornecedor")); // NOI18N

        obsPedidoTextArea.setColumns(20);
        obsPedidoTextArea.setLineWrap(true);
        obsPedidoTextArea.setRows(5);
        jScrollPane1.setViewportView(obsPedidoTextArea);

        observacaoLabel1.setText(bundle.getString("obsProduto")); // NOI18N

        obsProdutoTextArea.setColumns(20);
        obsProdutoTextArea.setLineWrap(true);
        obsProdutoTextArea.setRows(5);
        jScrollPane2.setViewportView(obsProdutoTextArea);

        observacaoLabel2.setText(bundle.getString("metaVenda")); // NOI18N

        metaVendaTextArea.setColumns(20);
        metaVendaTextArea.setLineWrap(true);
        metaVendaTextArea.setRows(5);
        jScrollPane3.setViewportView(metaVendaTextArea);

        comissaoLabel1.setText(bundle.getString("diasAtendimento")); // NOI18N

        diasTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        diasTextField.setInputVerifier(new DateVerifier(true));

        comissaoLabel.setText(bundle.getString("percComissao")); // NOI18N

        ativoCheckBox.setText(bundle.getString("ativo")); // NOI18N
        ativoCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        comissaoTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        comissaoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comissaoTextFieldFocusLost(evt);
            }
        });

        comissaoLabel2.setText(bundle.getString("frete")); // NOI18N

        freteTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        freteTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                freteTextFieldFocusLost(evt);
            }
        });

        obsPedidoClienteTextArea.setColumns(20);
        obsPedidoClienteTextArea.setLineWrap(true);
        obsPedidoClienteTextArea.setRows(5);
        jScrollPane4.setViewportView(obsPedidoClienteTextArea);

        observacaoLabel3.setText(bundle.getString("obsPedidoCliente")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecoLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cnpjField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cnpjLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inscrEstField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inscrEstLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtInclusaoLabel)
                                    .addComponent(dtInclusaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(observacaoLabel)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(observacaoLabel1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)))
                            .addComponent(razaoLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(razaoField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(enderecoField, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(fone1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fone1Label))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(fone2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fone2Label)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(bairroLabel)
                                                .addComponent(bairroField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cepLabel)
                                                .addComponent(cepField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cidadeLabel))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ufLabel)
                                                .addComponent(ufField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(fone3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fone3Label))
                                    .addGap(42, 42, 42)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bairroLabel1)
                                    .addComponent(reduzidoField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(siteLabel)
                                        .addGap(153, 153, 153))
                                    .addComponent(siteField, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(observacaoLabel3)
                        .addContainerGap(453, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(observacaoLabel2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comissaoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comissaoLabel2)
                            .addComponent(freteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diasTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comissaoLabel)
                            .addComponent(comissaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ativoCheckBox))
                        .addGap(84, 84, 84))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(razaoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(razaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bairroLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reduzidoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(siteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(siteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnpjLabel)
                    .addComponent(inscrEstLabel)
                    .addComponent(dtInclusaoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cnpjField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inscrEstField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtInclusaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enderecoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enderecoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bairroLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bairroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cepLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cidadeLabel)
                            .addComponent(ufLabel))
                        .addGap(34, 34, 34))
                    .addComponent(cidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ufField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fone1Label)
                    .addComponent(fone2Label)
                    .addComponent(fone3Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fone1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fone2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fone3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(observacaoLabel)
                            .addComponent(observacaoLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(observacaoLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comissaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comissaoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(observacaoLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comissaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comissaoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(freteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ativoCheckBox)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comissaoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comissaoTextFieldFocusLost
        // TODO add your handling code here:
        if (comissaoTextField.getText() == null || comissaoTextField.getText().length() == 0) {
            comissaoTextField.setValue(null);
        }
    }//GEN-LAST:event_comissaoTextFieldFocusLost

    private void freteTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_freteTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_freteTextFieldFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ativoCheckBox;
    private javax.swing.JFormattedTextField bairroField;
    private javax.swing.JLabel bairroLabel;
    private javax.swing.JLabel bairroLabel1;
    private javax.swing.JFormattedTextField cepField;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JFormattedTextField cidadeField;
    private javax.swing.JLabel cidadeLabel;
    private javax.swing.JFormattedTextField cnpjField;
    private javax.swing.JLabel cnpjLabel;
    private javax.swing.JLabel comissaoLabel;
    private javax.swing.JLabel comissaoLabel1;
    private javax.swing.JLabel comissaoLabel2;
    private javax.swing.JFormattedTextField comissaoTextField;
    private javax.swing.JFormattedTextField diasTextField;
    private com.toedter.calendar.JDateChooser dtInclusaoField;
    private javax.swing.JLabel dtInclusaoLabel;
    private javax.swing.JFormattedTextField enderecoField;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JFormattedTextField fone1Field;
    private javax.swing.JLabel fone1Label;
    private javax.swing.JFormattedTextField fone2Field;
    private javax.swing.JLabel fone2Label;
    private javax.swing.JFormattedTextField fone3Field;
    private javax.swing.JLabel fone3Label;
    private javax.swing.JFormattedTextField freteTextField;
    private javax.swing.JFormattedTextField inscrEstField;
    private javax.swing.JLabel inscrEstLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea metaVendaTextArea;
    private javax.swing.JTextArea obsPedidoClienteTextArea;
    private javax.swing.JTextArea obsPedidoTextArea;
    private javax.swing.JTextArea obsProdutoTextArea;
    private javax.swing.JLabel observacaoLabel;
    private javax.swing.JLabel observacaoLabel1;
    private javax.swing.JLabel observacaoLabel2;
    private javax.swing.JLabel observacaoLabel3;
    private javax.swing.JFormattedTextField razaoField;
    private javax.swing.JLabel razaoLabel;
    private javax.swing.JFormattedTextField reduzidoField;
    private javax.swing.JFormattedTextField siteField;
    private javax.swing.JLabel siteLabel;
    private javax.swing.JFormattedTextField ufField;
    private javax.swing.JLabel ufLabel;
    // End of variables declaration//GEN-END:variables
}
