/*
 * PedidoFilterPanel.java
 *
 * Created on 15 de Julho de 2007, 12:36
 */
package vendas.swing.app.pedido;

import vendas.beans.PedidoFilter;
import vendas.entity.GrupoProduto;
import vendas.entity.Repres;
import vendas.swing.core.EditPanel;
import ritual.util.DateUtils;
import vendas.entity.SubGrupoProduto;
import vendas.util.VendasUtil;

/**
 *
 * @author  Sam
 */
public class ClienteGrupoPanel extends EditPanel {

    /** Creates new form PedidoFilterPanel */
    public ClienteGrupoPanel() {
        initComponents();

    }

    @Override
    public void init() {
        try {
            represComboBox.setModel(VendasUtil.getRepresListModel(true));
            grupoComboBox.setModel(VendasUtil.getGrupoProdutoListModel());
        } catch (Exception e) {
            getLogger().error(e.getMessage(), e);
        }
    }

    @Override
    public void object2Field(Object obj) {
        PedidoFilter pedido = (PedidoFilter) obj;
        dtPedido1Field.setDate(pedido.getDtEmissaoIni());
        dtPedido2Field.setDate(pedido.getDtEmissaoEnd());
        grupoComboBox.setSelectedItem(pedido.getGrupoProduto());
        subGrupoComboBox.setSelectedItem(pedido.getSubGrupoProduto());
        represComboBox.setSelectedItem(pedido.getRepres());
    }

    @Override
    public void field2Object(Object obj) {
        PedidoFilter pedido = (PedidoFilter) obj;
        StringBuilder title = new StringBuilder();

        if (dtPedido1Field.getDate() != null) {
            pedido.setDtEmissaoIni(dtPedido1Field.getDate()); //DateUtils.parse(dtPedido1Field.getText())
            pedido.setDtEmissaoEnd(dtPedido2Field.getDate());
            title.append(getBundle().getString("emitidos"));
            title.append(" ");
            title.append(DateUtils.format(pedido.getDtEmissaoIni()));
            title.append(getBundle().getString("para"));
            title.append(DateUtils.format(pedido.getDtEmissaoEnd()));
            title.append(". ");
        }
        pedido.setGrupoProduto((GrupoProduto) grupoComboBox.getModel().getSelectedItem());
        SubGrupoProduto subGrupo = (SubGrupoProduto) subGrupoComboBox.getModel().getSelectedItem();
        pedido.setSubGrupoProduto(subGrupo);
        if ((subGrupo != null) && (subGrupo.getIdCodSubGrupo() != null)) {
            title.append("Sub-grupo ").append(subGrupo.getNomeGrupo()).append(". ");
        }
        pedido.setRepres((Repres) represComboBox.getModel().getSelectedItem());
        pedido.setTitle(title.toString());
        if (resumoRadioButton.isSelected()) {
            pedido.setTipoRelatorio(1);
        } else {
            pedido.setTipoRelatorio(2);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        dtPedido1Field = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        dtPedido2Field = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        grupoComboBox = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        represComboBox = new javax.swing.JComboBox();
        inativosCheckBox = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        subGrupoComboBox = new javax.swing.JComboBox();
        resumoRadioButton = new javax.swing.JRadioButton();
        relacaoRadioButton = new javax.swing.JRadioButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel2.setText(bundle.getString("dtEmissao")); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ClienteGrupoPanel.class);
        dtPedido1Field.setDateFormatString(resourceMap.getString("dtPedido1Field.dateFormatString")); // NOI18N

        jLabel3.setText(bundle.getString("para")); // NOI18N

        dtPedido2Field.setDateFormatString(resourceMap.getString("dtPedido2Field.dateFormatString")); // NOI18N

        jLabel18.setText(bundle.getString("grupoProduto")); // NOI18N

        grupoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupoComboBoxActionPerformed(evt);
            }
        });

        jLabel13.setText(bundle.getString("representada")); // NOI18N

        inativosCheckBox.setText(bundle.getString("mostrarInativas")); // NOI18N
        inativosCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inativosCheckBoxActionPerformed(evt);
            }
        });

        jLabel19.setText(bundle.getString("subgrupo")); // NOI18N

        buttonGroup1.add(resumoRadioButton);
        resumoRadioButton.setSelected(true);
        resumoRadioButton.setText(bundle.getString("resumo")); // NOI18N

        buttonGroup1.add(relacaoRadioButton);
        relacaoRadioButton.setText(bundle.getString("relacao")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resumoRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(relacaoRadioButton)
                        .addGap(167, 167, 167))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(dtPedido1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel3)
                                    .addGap(10, 10, 10)
                                    .addComponent(dtPedido2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2)
                                .addComponent(jLabel18)
                                .addComponent(grupoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(101, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(represComboBox, 0, 376, Short.MAX_VALUE)
                                .addComponent(inativosCheckBox)
                                .addComponent(jLabel13))
                            .addGap(23, 23, 23))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(subGrupoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19))
                            .addContainerGap(101, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtPedido1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(dtPedido2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grupoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subGrupoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(represComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inativosCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resumoRadioButton)
                    .addComponent(relacaoRadioButton))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void inativosCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inativosCheckBoxActionPerformed
        represComboBox.setModel(VendasUtil.getRepresListModel(inativosCheckBox.isSelected()));
    }//GEN-LAST:event_inativosCheckBoxActionPerformed

    private void grupoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupoComboBoxActionPerformed

        GrupoProduto grupo = (GrupoProduto) grupoComboBox.getModel().getSelectedItem();
        subGrupoComboBox.setModel(VendasUtil.getSubGrupoProdutoListModel(grupo));
    }//GEN-LAST:event_grupoComboBoxActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dtPedido1Field;
    private com.toedter.calendar.JDateChooser dtPedido2Field;
    private javax.swing.JComboBox grupoComboBox;
    private javax.swing.JCheckBox inativosCheckBox;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton relacaoRadioButton;
    private javax.swing.JComboBox represComboBox;
    private javax.swing.JRadioButton resumoRadioButton;
    private javax.swing.JComboBox subGrupoComboBox;
    // End of variables declaration//GEN-END:variables
}
