/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendas.swing.app.pedido;

import java.util.List;
import java.util.Map;
import ritual.swing.TApplication;
import vendas.beans.MovimentoFilter;
import vendas.dao.PedidoDao;
import vendas.swing.core.FilterFrame;
import vendas.util.Constants;
import vendas.util.Messages;
import vendas.util.Reports;

/**
 *
 * @author jaimeoliveira
 */
public class DescontosView extends FilterFrame {

    TApplication app = TApplication.getInstance();

    /**
     * Creates new form DescontosView
     */
    public DescontosView() {
        super();
        setTitle("Totais de desconto");
        PeriodoFilterPanel editPanel = new PeriodoFilterPanel();
        editPanel.init();
        setEditPanel(editPanel);
        MovimentoFilter pedidoFilter = new MovimentoFilter();
        setFilterObject(pedidoFilter);
    }

    @Override
    public void execute() {
        MovimentoFilter pedidoFilter = (MovimentoFilter) getFilterObject();
        PedidoDao pedidoDao = (PedidoDao) app.lookupService("pedidoDao");
        try {
            List lista = pedidoDao.findTotaisDesconto(pedidoFilter);
            if ((lista == null) || lista.isEmpty()) {
                Messages.errorMessage(app.getResourceString("noDataReport"));
            } else {
                Map model = app.getDefaultMap("Totais de desconto", pedidoFilter.getTitle());
                Reports.showReport(getClass().getResource(Constants.JRTOTALDESCONTO), model, lista);
            }
        } catch (Exception e) {
            getLogger().error(e.getMessage(), e);
            Messages.errorMessage(app.getResourceString("reportError"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
