/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImprimirPedidoPanel.java
 *
 * Created on Jun 3, 2012, 10:53:56 AM
 */

package vendas.swing.app.pedido;

import vendas.beans.PedidoPrint;
import vendas.swing.core.EditPanel;

/**
 *
 * @author sam
 */
public class ImprimirPedidoPanel extends EditPanel {

    /** Creates new form ImprimirPedidoPanel */
    public ImprimirPedidoPanel() {
        initComponents();
    }

    @Override
    public void object2Field(Object obj) {
        PedidoPrint filter = (PedidoPrint) obj;

    }
    @Override
    public void field2Object(Object obj) {
        PedidoPrint filter = (PedidoPrint) obj;
        filter.setReferencia(referenciaCheckBox.isSelected());
        if (represRadioButton.isSelected())
            filter.setTipo(0);
        else if (clienteRadioButton.isSelected())
            filter.setTipo(1);
        else
            filter.setTipo(2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        represRadioButton = new javax.swing.JRadioButton();
        clienteRadioButton = new javax.swing.JRadioButton();
        completoRadioButton = new javax.swing.JRadioButton();
        referenciaCheckBox = new javax.swing.JCheckBox();

        buttonGroup1.add(represRadioButton);
        represRadioButton.setSelected(true);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        represRadioButton.setText(bundle.getString("pedidoRepres")); // NOI18N
        represRadioButton.setName("represRadioButton"); // NOI18N
        represRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                represRadioButtonStateChanged(evt);
            }
        });

        buttonGroup1.add(clienteRadioButton);
        clienteRadioButton.setText(bundle.getString("pedidoCliente")); // NOI18N
        clienteRadioButton.setName("clienteRadioButton"); // NOI18N

        buttonGroup1.add(completoRadioButton);
        completoRadioButton.setText(bundle.getString("pedidoCompleto")); // NOI18N
        completoRadioButton.setName("completoRadioButton"); // NOI18N

        referenciaCheckBox.setText(bundle.getString("imprimiriReferencias")); // NOI18N
        referenciaCheckBox.setName("referenciaCheckBox"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(represRadioButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(clienteRadioButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(completoRadioButton))
                    .add(referenciaCheckBox))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(represRadioButton)
                    .add(clienteRadioButton)
                    .add(completoRadioButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(referenciaCheckBox)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void represRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_represRadioButtonStateChanged
        referenciaCheckBox.setEnabled(represRadioButton.isSelected());
        if (!represRadioButton.isSelected())
            referenciaCheckBox.setSelected(false);
    }//GEN-LAST:event_represRadioButtonStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton clienteRadioButton;
    private javax.swing.JRadioButton completoRadioButton;
    private javax.swing.JCheckBox referenciaCheckBox;
    private javax.swing.JRadioButton represRadioButton;
    // End of variables declaration//GEN-END:variables

}
