/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MapaFilterPanel.java
 *
 * Created on Dec 16, 2010, 12:26:08 AM
 */
package vendas.swing.app.pedido;

import java.text.DecimalFormat;
import java.util.Calendar;
import ritual.swing.NumericPlainDocument;
import ritual.util.NumberUtils;
import vendas.beans.MapaFilterBean;
import vendas.swing.core.EditPanel;

/**
 *
 * @author sam
 */
public class MapaFilterPanel extends EditPanel {

    /** Creates new form MapaFilterPanel */
    public MapaFilterPanel() {
        initComponents();
        anoTextField.setValue(Calendar.getInstance().get(Calendar.YEAR));
        DecimalFormat df = new DecimalFormat("#0");
        anoTextField.setDocument(new NumericPlainDocument(df));
    }

    @Override
    public void object2Field(Object obj) {
        anoTextField.setValue(Calendar.getInstance().get(Calendar.YEAR));
    }

    @Override
    public void field2Object(Object obj) {
        MapaFilterBean pedido = (MapaFilterBean) obj;
        pedido.setAno(NumberUtils.getInteger(anoTextField.getValue()));
        pedido.setVendas(vendasRadioButton.isSelected());
        if (vendasRadioButton.isSelected())
            pedido.setTitle("Vendas - " + anoTextField.getValue());
        else
            pedido.setTitle("Recebimentos - " + anoTextField.getValue());
    }

    @Override
    public boolean entryValidate() {
        return anoTextField.getValue() != null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        anoTextField = new javax.swing.JFormattedTextField();
        vendasRadioButton = new javax.swing.JRadioButton();
        recebimentosRadioButton = new javax.swing.JRadioButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("ano")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        anoTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        anoTextField.setName("anoTextField"); // NOI18N

        buttonGroup1.add(vendasRadioButton);
        vendasRadioButton.setSelected(true);
        vendasRadioButton.setText(bundle.getString("vendas")); // NOI18N
        vendasRadioButton.setName("vendasRadioButton"); // NOI18N

        buttonGroup1.add(recebimentosRadioButton);
        recebimentosRadioButton.setText(bundle.getString("recebimentos")); // NOI18N
        recebimentosRadioButton.setName("recebimentosRadioButton"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(anoTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(vendasRadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(recebimentosRadioButton)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(anoTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(vendasRadioButton)
                    .add(recebimentosRadioButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField anoTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton recebimentosRadioButton;
    private javax.swing.JRadioButton vendasRadioButton;
    // End of variables declaration//GEN-END:variables
}
