/*
 * NotaEdtPanel.java
 *
 * Created on 30 de Novembro de 2007, 16:33
 */
package vendas.swing.app.pedido;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFormattedTextField;
import ritual.swing.NumericPlainDocument;
import vendas.entity.AtendimentoPedido;
import vendas.swing.core.EditPanel;
import vendas.swing.model.ItensNotaModel;
import ritual.util.DateVerifier;
import ritual.util.NumberUtils;
import vendas.beans.CobrancaVO;
import vendas.entity.ArquivoPedido;
import vendas.swing.model.ArquivoPedidoModel;

/**
 *
 * @author  Sam
 */
public class ObsCobrancaEdtPanel extends EditPanel {

    DateVerifier dateVerifier = new DateVerifier();
    ItensNotaModel itensNotaModel;
    AtendimentoPedido atend;
    boolean isEditEnabled;

    /** Creates new form NotaEdtPanel */
    public ObsCobrancaEdtPanel() {
        initComponents();
        isEditEnabled = true;
        DecimalFormat df = new DecimalFormat("#0.00");
        subsTribField.setDocument(new NumericPlainDocument(df));

    }

    @Override
    public void object2Field(Object obj) {
        CobrancaVO cobranca = (CobrancaVO)obj;
        atend = cobranca.getAtend();
        obsTextArea.setText(atend.getObservacao());
        motoristaTextField.setText(atend.getMotorista());
        subsTribField.setValue(atend.getSubsTrib());
        foneTextField.setText(atend.getFoneMotorista());
        anexoCheckBox.setSelected(cobranca.getIncluirAnexo());
        ArquivoPedidoModel arqModel = new ArquivoPedidoModel(cobranca.getAnexos());
        anexosTable.setModel(arqModel);
        anexosTable.getColumnModel().getColumn(ArquivoPedidoModel.NOME).setPreferredWidth(250);

        itensNotaModel = new ItensNotaModel((List) atend.getItens());
        if ("A".equals(atend.getPedido().getSituacao())) {
            itensNotaModel.setReadOnly(true);
        } else {
            itensNotaModel.setReadOnly(false);
        }
    }

    public void setEditMode(boolean edit) {
        isEditEnabled = edit;
    }

    @Override
    public void field2Object(Object obj) {
        if (!isEditEnabled) {
            return;
        }

        CobrancaVO cobranca = (CobrancaVO)obj;
        atend = cobranca.getAtend();
        atend.setObservacao(obsTextArea.getText());
        atend.setMotorista(motoristaTextField.getText());
        atend.setFoneMotorista(foneTextField.getText());
        if (subsTribField.getValue() != null) {
            atend.setSubsTrib(NumberUtils.getBigDecimal(subsTribField.getValue()));
        }
        cobranca.setIncluirAnexo(anexoCheckBox.isSelected());
        
        int rows[] = anexosTable.getSelectedRows();
        ArquivoPedidoModel apm = (ArquivoPedidoModel)anexosTable.getModel();
        
        if (rows != null && rows.length > 0) {
            cobranca.setAnexosSelecionados(new ArrayList<ArquivoPedido>());
            for (int i : rows) {
                cobranca.getAnexosSelecionados().add((ArquivoPedido) apm.getObject(i));
            }
        }
    }

    private void deleteValue(java.awt.event.FocusEvent evt) {
        JFormattedTextField f = (JFormattedTextField) evt.getComponent();

        if (f.getText() == null || f.getText().length() == 0) {
            f.setValue(null);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        obsTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        motoristaTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        foneTextField = new javax.swing.JTextField();
        anexoCheckBox = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        subsTribField = new javax.swing.JFormattedTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        anexosTable = new javax.swing.JTable();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        setName("Form"); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel13.setText(bundle.getString("observacao")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        obsTextArea.setLineWrap(true);
        obsTextArea.setRows(5);
        obsTextArea.setName("obsTextArea"); // NOI18N
        jScrollPane2.setViewportView(obsTextArea);

        jLabel1.setText(bundle.getString("motorista")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ObsCobrancaEdtPanel.class);
        motoristaTextField.setText(resourceMap.getString("motoristaTextField.text")); // NOI18N
        motoristaTextField.setName("motoristaTextField"); // NOI18N

        jLabel2.setText(bundle.getString("fone")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        foneTextField.setText(resourceMap.getString("foneTextField.text")); // NOI18N
        foneTextField.setName("foneTextField"); // NOI18N

        anexoCheckBox.setText(bundle.getString("incluirAnexo")); // NOI18N
        anexoCheckBox.setName("anexoCheckBox"); // NOI18N

        jLabel22.setText(bundle.getString("subsTrib")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N

        subsTribField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        subsTribField.setInputVerifier(dateVerifier);
        subsTribField.setName("subsTribField"); // NOI18N
        subsTribField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                subsTribFieldFocusLost(evt);
            }
        });

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        anexosTable.setName("anexosTable"); // NOI18N
        jScrollPane3.setViewportView(anexosTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(motoristaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(foneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(188, 188, 188))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(subsTribField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(anexoCheckBox)))
                        .addContainerGap(272, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motoristaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subsTribField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anexoCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void subsTribFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_subsTribFieldFocusLost
        // TODO add your handling code here:
        deleteValue(evt);
}//GEN-LAST:event_subsTribFieldFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox anexoCheckBox;
    private javax.swing.JTable anexosTable;
    private javax.swing.JTextField foneTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField motoristaTextField;
    private javax.swing.JTextArea obsTextArea;
    private javax.swing.JFormattedTextField subsTribField;
    // End of variables declaration//GEN-END:variables
}
