/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProdutosVendidosFilterPanel.java
 *
 * Created on Feb 25, 2012, 2:23:51 PM
 */
package vendas.swing.app.pedido;

import ritual.util.DateUtils;
import vendas.beans.PedidoFilter;
import vendas.entity.Cliente;
import vendas.entity.GrupoProduto;
import vendas.entity.Produto;
import vendas.entity.Repres;
import vendas.entity.SubGrupoProduto;
import vendas.entity.Vendedor;
import vendas.swing.core.EditPanel;
import vendas.util.VendasUtil;

/**
 *
 * @author sam
 */
public class ProdutosVendidosFilterPanel extends EditPanel {

    /** Creates new form ProdutosVendidosFilterPanel */
    public ProdutosVendidosFilterPanel() {
        initComponents();
    }

    @Override
    public void init() {
        represComboBox.setModel(VendasUtil.getRepresListModel(true));
        vendedorComboBox.setModel(VendasUtil.getVendedoresListModel());
        clienteComboBox.setModel(VendasUtil.getClienteListModel());
        grupoComboBox.setModel(VendasUtil.getGrupoProdutoListModel());
    }

    @Override
    public boolean entryValidate() {
        return ((dtPedido1Field.getDate() != null) && (dtPedido2Field.getDate() != null));
    }


    @Override
    public void field2Object(Object obj) {
        StringBuilder title = new StringBuilder();
        PedidoFilter pedido = (PedidoFilter) obj;
        pedido.setRepres((Repres) represComboBox.getModel().getSelectedItem());
        pedido.setVendedor((Vendedor)vendedorComboBox.getModel().getSelectedItem());
        pedido.setCliente((Cliente)clienteComboBox.getModel().getSelectedItem());
        pedido.setQuebrarRepres(quebrarCheckBox.isSelected());

        if (dtPedido1Field.getDate() != null) {
            try {
                pedido.setDtEmissaoIni(DateUtils.parse(DateUtils.format(dtPedido1Field.getDate())));
                pedido.setDtEmissaoEnd(DateUtils.parse(DateUtils.format(dtPedido2Field.getDate())));
            } catch (Exception e) {
                e.printStackTrace();
            }
            title.append(DateUtils.format(dtPedido1Field.getDate())).append(" a ").append(DateUtils.format(dtPedido2Field.getDate())).append(". ");
        }
        if (pedido.getVendedor().getIdVendedor() != null)
            title.append("Vendedor ").append(pedido.getVendedor().getNome()). append(". ");
        if (pedido.getCliente().getIdCliente() != null)
            title.append(pedido.getCliente().getRazao()). append(". ");

        pedido.setProduto(new Produto());
        pedido.getProduto().setGrupoProduto((GrupoProduto) grupoComboBox.getModel().getSelectedItem());
        SubGrupoProduto subGrupo = (SubGrupoProduto) subGrupoComboBox.getModel().getSelectedItem();
        pedido.getProduto().setSubGrupoProduto(subGrupo);
        
        if ((subGrupo != null) && (subGrupo.getIdCodSubGrupo() != null)) {
            pedido.setTitle("Sub-grupo " + subGrupo.getNomeGrupo());
        }
        pedido.setTitle(title.toString());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        dtPedido1Field = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        dtPedido2Field = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        clienteComboBox = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        vendedorComboBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        represComboBox = new javax.swing.JComboBox();
        quebrarCheckBox = new javax.swing.JCheckBox();
        grupoComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        subGrupoComboBox = new javax.swing.JComboBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel2.setText(bundle.getString("dtPedido")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        dtPedido1Field.setDateFormatString("dd/MM/yyyy");
        dtPedido1Field.setName("dtPedido1Field"); // NOI18N

        jLabel3.setText(bundle.getString("para")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        dtPedido2Field.setDateFormatString("dd/MM/yyyy");
        dtPedido2Field.setName("dtPedido2Field"); // NOI18N

        jLabel11.setText(bundle.getString("cliente")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        clienteComboBox.setName("clienteComboBox"); // NOI18N

        jLabel10.setText(bundle.getString("vendedor")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        vendedorComboBox.setName("vendedorComboBox"); // NOI18N

        jLabel9.setText(bundle.getString("representada")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        represComboBox.setName("represComboBox"); // NOI18N

        quebrarCheckBox.setText(bundle.getString("quebrar")); // NOI18N
        quebrarCheckBox.setName("quebrarCheckBox"); // NOI18N

        grupoComboBox.setName("grupoComboBox"); // NOI18N
        grupoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupoComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setText(bundle.getString("grupo")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel15.setText(bundle.getString("subgrupo")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        subGrupoComboBox.setName("subGrupoComboBox"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel10)
                    .add(vendedorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 416, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9)
                    .add(layout.createSequentialGroup()
                        .add(represComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 416, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(quebrarCheckBox))
                    .add(jLabel11)
                    .add(clienteComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 416, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel6)
                            .add(grupoComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 184, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel15)
                            .add(subGrupoComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(82, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(dtPedido1Field, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel2))
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(jLabel3)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(dtPedido2Field, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(300, 300, 300)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(76, 76, 76)
                .add(jLabel10)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(vendedorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel11)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(clienteComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel9)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(represComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(quebrarCheckBox))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(grupoComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(jLabel15)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(subGrupoComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(4, 4, 4)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(layout.createSequentialGroup()
                            .add(jLabel2)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(dtPedido2Field, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(dtPedido1Field, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(jLabel3))
                    .addContainerGap(254, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void grupoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupoComboBoxActionPerformed
        GrupoProduto grupo = (GrupoProduto) grupoComboBox.getModel().getSelectedItem();
        subGrupoComboBox.setModel(VendasUtil.getSubGrupoProdutoListModel(grupo));
    }//GEN-LAST:event_grupoComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox clienteComboBox;
    private com.toedter.calendar.JDateChooser dtPedido1Field;
    private com.toedter.calendar.JDateChooser dtPedido2Field;
    private javax.swing.JComboBox grupoComboBox;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox quebrarCheckBox;
    private javax.swing.JComboBox represComboBox;
    private javax.swing.JComboBox subGrupoComboBox;
    private javax.swing.JComboBox vendedorComboBox;
    // End of variables declaration//GEN-END:variables
}
