/*
 * ProdutosClientePanel.java
 *
 * Created on 30 de Novembro de 2007, 22:23
 */
package vendas.swing.app.pedido;

import ritual.util.DateUtils;
import vendas.beans.PedidoFilter;
import vendas.entity.Cliente;
import vendas.entity.GrupoProduto;
import vendas.entity.Repres;
import vendas.swing.core.EditPanel;
import ritual.util.DateVerifier;
import ritual.util.NumberUtils;
import vendas.entity.SubGrupoProduto;
import vendas.util.VendasUtil;

/**
 *
 * @author  Sam
 */
public class ProdutosClientePanel extends EditPanel {

    private DateVerifier dateVerifier = new DateVerifier();

    /** Creates new form ProdutosClientePanel */
    public ProdutosClientePanel() {
        initComponents();
    }

    @Override
    public void init() {
        clienteComboBox.setModel(VendasUtil.getClienteListModel());
        represComboBox.setModel(VendasUtil.getRepresListModel(true));
        grupoComboBox.setModel(VendasUtil.getGrupoProdutoListModel());
    }

    @Override
    public void field2Object(Object obj) {
        PedidoFilter pedido = (PedidoFilter) obj;
        StringBuilder title = new StringBuilder();
        if (dtPedido1Field.getDate() != null) {
            pedido.setDtEmissaoIni(dtPedido1Field.getDate());
            pedido.setDtEmissaoEnd(dtPedido2Field.getDate());
        }
        if (pedido.getDtEmissaoIni() != null) {
            title.append(getBundle().getString("emitidos"));
            title.append(" ");
            title.append(DateUtils.format(pedido.getDtEmissaoIni()));
            title.append(getBundle().getString("para"));
            title.append(DateUtils.format(pedido.getDtEmissaoEnd()));
            title.append(". ");
        }
        pedido.getProduto().setIdProduto((Integer) produtoField.getValue());
        pedido.setRepres((Repres) represComboBox.getModel().getSelectedItem());
        pedido.setCliente((Cliente) clienteComboBox.getModel().getSelectedItem());
        pedido.setGrupoProduto((GrupoProduto) grupoComboBox.getModel().getSelectedItem());
        SubGrupoProduto subGrupo = (SubGrupoProduto) subGrupoComboBox.getModel().getSelectedItem();
        pedido.setSubGrupoProduto(subGrupo);
        if ((subGrupo != null) && (subGrupo.getIdCodSubGrupo() != null)) {
            title.append("Sub-grupo ").append(subGrupo.getNomeGrupo()).append(". ");
        }
        if (produtoButton.isSelected()) {
            pedido.setOrdem(0);
        } else {
            pedido.setOrdem(1);
        }

        pedido.setTitle(title.toString());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        dtPedido1Field = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        dtPedido2Field = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        produtoField = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        clienteComboBox = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        represComboBox = new javax.swing.JComboBox();
        inativosCheckBox = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        grupoComboBox = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        subGrupoComboBox = new javax.swing.JComboBox();
        produtoButton = new javax.swing.JRadioButton();
        clienteButton = new javax.swing.JRadioButton();

        setName("Form"); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel2.setText(bundle.getString("dtEmissao")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        dtPedido1Field.setName("dtPedido1Field"); // NOI18N

        jLabel3.setText(bundle.getString("para")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        dtPedido2Field.setName("dtPedido2Field"); // NOI18N

        jLabel17.setText(bundle.getString("produto")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        produtoField.setFormatterFactory(NumberUtils.getIntFormatterFactory());
        produtoField.setName("produtoField"); // NOI18N

        jLabel10.setText(bundle.getString("cliente")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        clienteComboBox.setName("clienteComboBox"); // NOI18N

        jLabel13.setText(bundle.getString("representada")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        represComboBox.setName("represComboBox"); // NOI18N

        inativosCheckBox.setText(bundle.getString("mostrarInativas")); // NOI18N
        inativosCheckBox.setName("inativosCheckBox"); // NOI18N
        inativosCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inativosCheckBoxActionPerformed(evt);
            }
        });

        jLabel14.setText(bundle.getString("grupoProduto")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        grupoComboBox.setName("grupoComboBox"); // NOI18N
        grupoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupoComboBoxActionPerformed(evt);
            }
        });

        jLabel15.setText(bundle.getString("subgrupo")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        subGrupoComboBox.setName("subGrupoComboBox"); // NOI18N

        buttonGroup1.add(produtoButton);
        produtoButton.setText(bundle.getString("ordenarProduto")); // NOI18N
        produtoButton.setName("produtoButton"); // NOI18N

        buttonGroup1.add(clienteButton);
        clienteButton.setSelected(true);
        clienteButton.setText(bundle.getString("ordenarCliente")); // NOI18N
        clienteButton.setName("clienteButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addComponent(inativosCheckBox)
                    .addComponent(jLabel15)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(produtoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clienteButton))
                    .addComponent(grupoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(represComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clienteComboBox, 0, 327, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dtPedido1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtPedido2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(22, 22, 22))
                            .addComponent(produtoField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addComponent(subGrupoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dtPedido1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtPedido2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(produtoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(represComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inativosCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grupoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subGrupoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produtoButton)
                    .addComponent(clienteButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inativosCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inativosCheckBoxActionPerformed
        represComboBox.setModel(VendasUtil.getRepresListModel(inativosCheckBox.isSelected()));
    }//GEN-LAST:event_inativosCheckBoxActionPerformed

    private void grupoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupoComboBoxActionPerformed
        GrupoProduto grupo = (GrupoProduto) grupoComboBox.getModel().getSelectedItem();
        subGrupoComboBox.setModel(VendasUtil.getSubGrupoProdutoListModel(grupo));
    }//GEN-LAST:event_grupoComboBoxActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton clienteButton;
    private javax.swing.JComboBox clienteComboBox;
    private com.toedter.calendar.JDateChooser dtPedido1Field;
    private com.toedter.calendar.JDateChooser dtPedido2Field;
    private javax.swing.JComboBox grupoComboBox;
    private javax.swing.JCheckBox inativosCheckBox;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton produtoButton;
    private javax.swing.JFormattedTextField produtoField;
    private javax.swing.JComboBox represComboBox;
    private javax.swing.JComboBox subGrupoComboBox;
    // End of variables declaration//GEN-END:variables
}
