/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendas.swing.app.auxiliar;

import vendas.swing.core.EditPanel;

/**
 *
 * @author jaime
 */
public class AgendaMovEditPanel extends EditPanel  {

    /**
     * Creates new form AgendaMovEditPanel
     */
    public AgendaMovEditPanel() {
        initComponents();
    }
    
        @Override
    public void object2Field(Object obj) {
        DataDiaAgendaModel agenda = (DataDiaAgendaModel) obj;
        dtEventoField.setDate(agenda.getDtEvento());
        diasButton.setSelected(agenda.getTipo().equals("Q"));
        dataButton.setSelected(agenda.getTipo().equals("D"));
    }

    @Override
    public void field2Object(Object obj) {
        DataDiaAgendaModel agenda = (DataDiaAgendaModel) obj;
        agenda.setDtEvento(dtEventoField.getDate());
        String dias = qtDias.getText();
        if (dias != null && dias.length() > 0) {
            agenda.setQtDia(Integer.decode(dias));
        }
        agenda.setTipo(dataButton.isSelected() ? "D" : "Q");
    }
    
    @Override
    public boolean entryValidate() {
        if (dataButton.isSelected() && dtEventoField.getDate() == null) {
            return false;
        }
        
        if (diasButton.isSelected() && qtDias.getText() == null) {
            return false;
        }
        
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dataButton = new javax.swing.JRadioButton();
        diasButton = new javax.swing.JRadioButton();
        dtEventoField = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        qtDias = new javax.swing.JFormattedTextField();

        buttonGroup1.add(dataButton);
        dataButton.setText("Data");
        dataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(diasButton);
        diasButton.setText("Dias");
        diasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diasButtonActionPerformed(evt);
            }
        });

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel5.setText(bundle.getString("dtEvento")); // NOI18N

        jLabel1.setText("Número dias");

        qtDias.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(diasButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dtEventoField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(qtDias)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataButton)
                    .addComponent(diasButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtEventoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataButtonActionPerformed

    private void diasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diasButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton dataButton;
    private javax.swing.JRadioButton diasButton;
    private com.toedter.calendar.JDateChooser dtEventoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JFormattedTextField qtDias;
    // End of variables declaration//GEN-END:variables
}
