/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AniversarioFilterPanel.java
 *
 * Created on Feb 12, 2011, 10:53:17 AM
 */
package vendas.swing.app.auxiliar;

import java.text.SimpleDateFormat;
import java.util.Date;
import vendas.beans.AniversarioFilter;
import vendas.swing.core.EditPanel;

/**
 *
 * @author sam
 */
public class AniversarioFilterPanel extends EditPanel {

    String[] meses = new String[]{"01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"};

    /** Creates new form AniversarioFilterPanel */
    public AniversarioFilterPanel() {
        initComponents();
    }

    @Override
    public void object2Field(Object obj) {
    }

    @Override
    public void field2Object(Object obj) {
        AniversarioFilter pedido = (AniversarioFilter) obj;
        if (hojeRadioButton.isSelected()) {
            SimpleDateFormat sdf = new SimpleDateFormat("MMdd");
            String mes = sdf.format(new Date());
            pedido.setMesInicial(mes);
            pedido.setMesFinal(mes);
        }
        if (mesRadioButton.isSelected()) {
            SimpleDateFormat sdf = new SimpleDateFormat("MM");
            String mes = sdf.format(new Date());
            pedido.setMesInicial(mes + "01");
            pedido.setMesFinal(mes + "31");
        }
        if (periodoRadioButton.isSelected()) {
            pedido.setMesInicial(meses[inicioComboBox.getSelectedIndex()] + "01");
            pedido.setMesFinal(meses[fimComboBox.getSelectedIndex()] + "31");
        }
        pedido.setNome(nomeField.getText().toUpperCase());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hojeRadioButton = new javax.swing.JRadioButton();
        mesRadioButton = new javax.swing.JRadioButton();
        periodoRadioButton = new javax.swing.JRadioButton();
        inicioComboBox = new javax.swing.JComboBox();
        fimComboBox = new javax.swing.JComboBox();
        nomeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("mesInicial")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(bundle.getString("mesFinal")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        buttonGroup1.add(hojeRadioButton);
        hojeRadioButton.setSelected(true);
        hojeRadioButton.setText(bundle.getString("hoje")); // NOI18N
        hojeRadioButton.setName("hojeRadioButton"); // NOI18N
        hojeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hojeRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(mesRadioButton);
        mesRadioButton.setText("Mês"); // NOI18N
        mesRadioButton.setName("mesRadioButton"); // NOI18N
        mesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(periodoRadioButton);
        periodoRadioButton.setText(bundle.getString("periodo")); // NOI18N
        periodoRadioButton.setName("periodoRadioButton"); // NOI18N
        periodoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodoRadioButtonActionPerformed(evt);
            }
        });

        inicioComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        inicioComboBox.setEnabled(false);
        inicioComboBox.setName("inicioComboBox"); // NOI18N

        fimComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        fimComboBox.setEnabled(false);
        fimComboBox.setName("fimComboBox"); // NOI18N

        nomeField.setName("nomeField");

        jLabel3.setText(bundle.getString("nome")); // NOI18N
        jLabel3.setName("jLabel3");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(hojeRadioButton)
                            .add(mesRadioButton)
                            .add(periodoRadioButton))
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jLabel3)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(nomeField)
                            .add(layout.createSequentialGroup()
                                .add(0, 0, Short.MAX_VALUE)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel1)
                                    .add(inicioComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel2)
                                    .add(fimComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(hojeRadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(mesRadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(periodoRadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(inicioComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(fimComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nomeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void periodoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodoRadioButtonActionPerformed
        setComboBox();
    }//GEN-LAST:event_periodoRadioButtonActionPerformed

    private void hojeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hojeRadioButtonActionPerformed
        setComboBox();
    }//GEN-LAST:event_hojeRadioButtonActionPerformed

    private void mesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesRadioButtonActionPerformed
        setComboBox();

    }//GEN-LAST:event_mesRadioButtonActionPerformed

    private void setComboBox() {
        inicioComboBox.setEnabled(periodoRadioButton.isSelected());
        fimComboBox.setEnabled(periodoRadioButton.isSelected());

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox fimComboBox;
    private javax.swing.JRadioButton hojeRadioButton;
    private javax.swing.JComboBox inicioComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton mesRadioButton;
    private javax.swing.JTextField nomeField;
    private javax.swing.JRadioButton periodoRadioButton;
    // End of variables declaration//GEN-END:variables
}
