/*
 * ComissaoVendedorEditPanel.java
 *
 * Created on 10 de Julho de 2007, 16:55
 */

package vendas.swing.app.auxiliar;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import ritual.swing.NumericPlainDocument;
import ritual.util.DateVerifier;
import vendas.entity.ComissaoVendedor;
import vendas.entity.Repres;
import vendas.swing.core.EditPanel;
import vendas.util.VendasUtil;

/**
 *
 * @author  p993702
 */
public class ComissaoVendedorEditPanel extends EditPanel  {
    
    DateVerifier dateVerifier = new DateVerifier();
    
    /** Creates new form ComissaoVendedorEditPanel */
    public ComissaoVendedorEditPanel() {
        initComponents();
                DecimalFormat df = new DecimalFormat("#0.00");
        comissaoField.setDocument(new NumericPlainDocument(df));
    }

    @Override
    public void init() {
        represComboBox.setModel(VendasUtil.getRepresListModel(true));
    }
    
    @Override
    public void object2Field(Object obj) {
        ComissaoVendedor comissaoVendedor = (ComissaoVendedor) obj;
        if (comissaoVendedor.getComissao() != null)
        comissaoField.setValue(comissaoVendedor.getComissao());
        represComboBox.setSelectedItem(comissaoVendedor.getRepres());
    }

    @Override
    public void field2Object(Object obj) {
        ComissaoVendedor comissaoVendedor = (ComissaoVendedor) obj;
        comissaoVendedor.setComissao(BigDecimal.valueOf((Long)comissaoField.getValue()));
        Repres repres = (Repres)represComboBox.getModel().getSelectedItem();
        comissaoVendedor.setRepres(repres);
        comissaoVendedor.getComissaoVendedorPK().setIdrepres(repres.getIdRepres());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        represComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        comissaoField = new javax.swing.JFormattedTextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel2.setText(bundle.getString("fornecedor")); // NOI18N

        represComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText(bundle.getString("comissao")); // NOI18N

        comissaoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(represComboBox, 0, 306, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(comissaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(represComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comissaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField comissaoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox represComboBox;
    // End of variables declaration//GEN-END:variables
    
}