/*
 * CorreioEditPanel.java
 *
 * Created on 10 de Julho de 2007, 16:55
 */

package vendas.swing.app.auxiliar;

import java.util.Date;
import ritual.swing.TApplication;
import vendas.beans.MensagemCorreio;
import vendas.dao.CorreioDao;
import vendas.entity.Correio;
import vendas.util.EditDialog;
import vendas.swing.core.EditPanel;
import vendas.util.Messages;

/**
 *
 * @author  p993702
 */
public class CorreioViewFrame extends EditPanel  {
    
    Correio current;
    
    /** Creates new form CorreioEditPanel */
    public CorreioViewFrame() {
        initComponents();
    }

    @Override
    public void object2Field(Object obj) {
        Correio correio = (Correio) obj;
        current = correio;
        msgTextPane.setText(correio.getMensagem());
        userField.setText(correio.getUserOrigem().getUserName());
        dataTextField.setText(correio.getDataEnvio().toString());
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        msgTextPane = new javax.swing.JTextPane();
        userField = new javax.swing.JTextField();
        dataTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        responderButton = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("origem")); // NOI18N

        jLabel2.setText(bundle.getString("mensagem")); // NOI18N

        msgTextPane.setEditable(false);
        jScrollPane2.setViewportView(msgTextPane);

        userField.setEditable(false);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(CorreioViewFrame.class);
        userField.setText(resourceMap.getString("userField.text")); // NOI18N

        dataTextField.setEditable(false);
        dataTextField.setText(resourceMap.getString("dataTextField.text")); // NOI18N

        jLabel3.setText(bundle.getString("dataEnvio")); // NOI18N

        responderButton.setText(bundle.getString("responder")); // NOI18N
        responderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(387, 387, 387))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(381, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(userField, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(responderButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(responderButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void responderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responderButtonActionPerformed
        // TODO add your handling code here:
        CorreioRespEditPanel editPanel = new CorreioRespEditPanel();
        EditDialog edtDlg = new EditDialog("Responder mensagem");
        edtDlg.setEditPanel(editPanel);
        MensagemCorreio banco = new MensagemCorreio();
        Correio correio;
        while (edtDlg.edit(banco)) {
            try {
                    correio = new Correio();
                    correio.setMensagem(banco.getMensagem());
                    correio.setUserDestino(current.getUserOrigem());
                    correio.setUserOrigem(TApplication.getInstance().getUser());
                    correio.setDataEnvio(new Date());
                    correio.setMensagemlida('0');
                    CorreioDao dao = (CorreioDao) TApplication.getInstance().lookupService("correioDao");
                    dao.insertRecord(correio);
                    Messages.infoMessage("Mensagem enviada.");
                break;
            } catch (Exception e) {
                getLogger().error(getBundle().getString("saveErrorMessage"), e);
                Messages.errorMessage(getBundle().getString("saveErrorMessage"));
            }
        }
        
    }//GEN-LAST:event_responderButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dataTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane msgTextPane;
    private javax.swing.JButton responderButton;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
    
}