/*
 * CorreioEditPanel.java
 *
 * Created on 10 de Julho de 2007, 16:55
 */

package vendas.swing.app.auxiliar;

import java.util.ArrayList;
import java.util.List;
import ritual.swing.TApplication;
import vendas.beans.MensagemCorreio;
import vendas.beans.UserSelect;
import vendas.dao.UserDao;
import vendas.entity.User;
import vendas.swing.core.EditPanel;
import vendas.swing.model.UsersTableModel;

/**
 *
 * @author  p993702
 */
public class CorreioEditPanel extends EditPanel  {
    
    /** Creates new form CorreioEditPanel */
    public CorreioEditPanel() {
        initComponents();
    }

    @Override
    public void object2Field(Object obj) {
        MensagemCorreio correio = (MensagemCorreio) obj;
        UserDao dao = (UserDao) TApplication.getInstance().lookupService("userDao");
        UsersTableModel users;
        try {
            users = new UsersTableModel();
            List lista = new ArrayList();
            List<User> usuarios = dao.findAll();
            User origem = TApplication.getInstance().getUser();
            for (User u : usuarios) {
                if (!origem.getUserName().equals(u.getUserName())) {
                UserSelect s = new UserSelect();
                s.setSelecionado(Boolean.FALSE);
                s.setUser(u);
                lista.add(s);
                }
            }
            users.setItemList(lista);
        } catch (Exception e) {
            users = null;
        }
        usersTable.setModel(users);
        usersTable.getColumnModel().getColumn(0).setPreferredWidth(20);
    }

    @Override
    public void field2Object(Object obj) {
        MensagemCorreio correio = (MensagemCorreio) obj;
        correio.setMensagem(msgTextPane.getText());
        UsersTableModel model = (UsersTableModel)usersTable.getModel();
        List<UserSelect> lista = model.getItemList();
        List usuarios = new ArrayList();
        for (UserSelect u : lista) {
            if (u.getSelecionado())
                usuarios.add(u.getUser());
        }
        correio.setUsuarios(usuarios);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        msgTextPane = new javax.swing.JTextPane();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("destino")); // NOI18N

        jLabel2.setText(bundle.getString("mensagem")); // NOI18N

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(usersTable);

        jScrollPane2.setViewportView(msgTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(387, 387, 387))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane msgTextPane;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
    
}