/*
 * GrupoProdutoEditPanel.java
 *
 * Created on 30 de Julho de 2007, 16:59
 */
package vendas.swing.app.auxiliar;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.table.TableColumn;
import org.jdesktop.application.Action;
import vendas.entity.GrupoProduto;
import vendas.swing.core.EditPanel;
import ritual.swing.BoundedPlainDocument;
import vendas.entity.SubGrupoProduto;
import vendas.swing.model.SubGrupoProdutoModel;

/**
 *
 * @author  Sam
 */
public class GrupoProdutoEditPanel extends EditPanel {

    GrupoProduto target;
    List deletedItens;

    /** Creates new form GrupoProdutoEditPanel */
    public GrupoProdutoEditPanel() {
        initComponents();
    }

    @Override
    public void object2Field(Object obj) {
        GrupoProduto grupo = (GrupoProduto) obj;
        target = grupo;
        nomeGrupoField.setText(grupo.getNomeGrupo());
        List<SubGrupoProduto> itens;
        if (grupo.getSubGrupoProdutoList() != null) {
            itens = new ArrayList<SubGrupoProduto>();
            for (int i = 0; i < grupo.getSubGrupoProdutoList().size(); i++)
                itens.add(null);
            Collections.copy(itens, (List)grupo.getSubGrupoProdutoList());
            Collections.sort(itens, new NomeGrupoComparator());
        } else {
            itens = new ArrayList<SubGrupoProduto>();
        }
        SubGrupoProdutoModel itemModel = new SubGrupoProdutoModel(itens);
        itemModel.setReadOnly(false);
        itensTable.setModel(itemModel);
        TableColumn col = itensTable.getColumnModel().getColumn(0);
    }

    @Override
    public void field2Object(Object obj) {
        GrupoProduto grupo = (GrupoProduto) obj;
        grupo.setNomeGrupo(nomeGrupoField.getText());
        SubGrupoProdutoModel itemModel = (SubGrupoProdutoModel) itensTable.getModel();
        grupo.setSubGrupoProdutoList(itemModel.getItemList());
    }

    @Action
    public void deleletAction() {
        int n = itensTable.getSelectedRow();
        if (n >= 0) {
            SubGrupoProdutoModel itp = (SubGrupoProdutoModel) itensTable.getModel();
            if (deletedItens == null)
                deletedItens = new ArrayList();
            deletedItens.add(itp.getObject(n));
            itp.removeObject(n);
            int i = itp.getRowCount();
            if (i > 0) {
                if (n >= i) {
                    n--;
                }
                itensTable.setRowSelectionInterval(n, n);
                itensTable.scrollRectToVisible(itensTable.getCellRect(n, 0, true));
            }
        }
    }

    @Action
    public void insertAction() {
        SubGrupoProdutoModel itemModel = (SubGrupoProdutoModel) itensTable.getModel();
        SubGrupoProduto item = new SubGrupoProduto();
        item.setGrupoProduto(target);
        itemModel.addObject(item);
        itemModel.fireTableDataChanged();
    }

    public List getDeletedItens() {
        return deletedItens;
    }

    public void setDeletedItens(List deletedItens) {
        this.deletedItens = deletedItens;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeGrupoField = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itensTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("nome")); // NOI18N

        nomeGrupoField.setDocument(new BoundedPlainDocument(40));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("subgrupos"))); // NOI18N

        itensTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(itensTable);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(GrupoProdutoEditPanel.class, this);
        addButton.setAction(actionMap.get("insertAction")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(GrupoProdutoEditPanel.class);
        addButton.setIcon(resourceMap.getIcon("addButton.icon")); // NOI18N
        addButton.setText(resourceMap.getString("addButton.text")); // NOI18N

        delButton.setAction(actionMap.get("deleletAction")); // NOI18N
        delButton.setIcon(resourceMap.getIcon("delButton.icon")); // NOI18N
        delButton.setText(resourceMap.getString("delButton.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delButton)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeGrupoField, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeGrupoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton delButton;
    private javax.swing.JTable itensTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField nomeGrupoField;
    // End of variables declaration//GEN-END:variables
}

class NomeGrupoComparator implements Comparator {

    public int compare(Object obj1, Object obj2) {
        SubGrupoProduto grupo1 = (SubGrupoProduto) obj1;
        SubGrupoProduto grupo2 = (SubGrupoProduto) obj2;
        return grupo1.getNomeGrupo().compareTo(grupo2.getNomeGrupo());

    }
}
