/*
 * GrupoClienteEditPanel.java
 *
 * Created on 9 de Julho de 2007, 22:45
 */

package vendas.swing.app.auxiliar;

import vendas.entity.GrupoCliente;
import vendas.swing.core.EditPanel;
import ritual.swing.BoundedPlainDocument;

/**
 *
 * @author  Sam
 */
public class GrupoClienteEditPanel extends EditPanel {
    
    /** Creates new form GrupoClienteEditPanel */
    public GrupoClienteEditPanel() {
        initComponents();
    }

    @Override
    public void object2Field(Object obj) {
        GrupoCliente grupo = (GrupoCliente) obj;
        nomeGrupoField.setText(grupo.getNomeGrupo());
    }
    
    @Override
    public void field2Object(Object obj) {
        GrupoCliente grupo = (GrupoCliente) obj;
        grupo.setNomeGrupo(nomeGrupoField.getText());
    }
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeGrupoField = new javax.swing.JFormattedTextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("nome")); // NOI18N

        nomeGrupoField.setDocument(new BoundedPlainDocument(40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeGrupoField, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeGrupoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField nomeGrupoField;
    // End of variables declaration//GEN-END:variables
    
}
