/*
 * SituacaoClienteEditPanel.java
 *
 * Created on 9 de Julho de 2007, 22:45
 */

package vendas.swing.app.auxiliar;

import vendas.entity.SituacaoCliente;
import vendas.swing.core.EditPanel;
import ritual.swing.BoundedPlainDocument;

/**
 *
 * @author  Sam
 */
public class SituacaoClienteEditPanel extends EditPanel {

    /** Creates new form SituacaoClienteEditPanel */
    public SituacaoClienteEditPanel() {
        initComponents();
    }
    
    @Override
    public void object2Field(Object obj) {
        SituacaoCliente situacao = (SituacaoCliente) obj;        
        nomeField.setText(situacao.getNome());
        permitePedidoCheckBox.setSelected(situacao.getPermitePedido().booleanValue());
    }
    
    @Override
    public void field2Object(Object obj) {
        SituacaoCliente situacao = (SituacaoCliente) obj;        
        situacao.setNome(nomeField.getText());
        situacao.setPermitePedido(new Boolean(permitePedidoCheckBox.isSelected()));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeField = new javax.swing.JFormattedTextField();
        permitePedidoCheckBox = new javax.swing.JCheckBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("nomeSituacao")); // NOI18N

        nomeField.setDocument(new BoundedPlainDocument(40));

        permitePedidoCheckBox.setText(bundle.getString("permitePedido")); // NOI18N
        permitePedidoCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        permitePedidoCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeField, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                    .addComponent(permitePedidoCheckBox))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(permitePedidoCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField nomeField;
    private javax.swing.JCheckBox permitePedidoCheckBox;
    // End of variables declaration//GEN-END:variables
    
}
