/*
 * TransportadorEditPanel.java
 *
 * Created on 7 de Setembro de 2007, 15:18
 */

package vendas.swing.app.auxiliar;

import vendas.entity.Transportador;
import vendas.swing.core.EditPanel;
import ritual.swing.BoundedPlainDocument;
import ritual.swing.ListComboBoxModel;
import ritual.swing.TApplication;
import ritual.util.DateVerifier;
import vendas.dao.FormaPgtoDao;
import vendas.entity.FormaPgto;

/**
 *
 * @author  Sam
 */
public class TransportadorEditPanel extends EditPanel {

    private FormaPgtoDao formaPgtoDao;
    private DateVerifier dateVerifier = new DateVerifier();
    
    /** Creates new form TransportadorEditPanel */
    public TransportadorEditPanel() {
        initComponents();
        formaPgtoDao = (FormaPgtoDao) TApplication.getInstance().lookupService("formaPgtoDao");
        pgtoComboBox.setModel(new ListComboBoxModel(formaPgtoDao.findAll()));
    }
    
    @Override
    public void object2Field(Object obj) {
        Transportador transportador = (Transportador) obj;
        codTransField.setText(transportador.getCodTrans());
        fone1Field.setText(transportador.getFone1());
        fone2Field.setText(transportador.getFone2());
        nomeField.setText(transportador.getNome());
        pgtoComboBox.setSelectedItem(transportador.getFormaPgto());
        contaField.setText(transportador.getNuContaCorrente());
    }
    
    @Override
    public void field2Object(Object obj) {
        Transportador transportador = (Transportador) obj;
        transportador.setCodTrans(codTransField.getText());
        transportador.setFone1(fone1Field.getText());
        transportador.setFone2(fone2Field.getText());
        transportador.setNome(nomeField.getText());
        transportador.setFormaPgto((FormaPgto) pgtoComboBox.getModel().getSelectedItem());
        transportador.setNuContaCorrente(contaField.getText());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codTransField = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        nomeField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        fone1Field = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        fone2Field = new javax.swing.JFormattedTextField();
        lblPgto = new javax.swing.JLabel();
        pgtoComboBox = new javax.swing.JComboBox();
        lblConta = new javax.swing.JLabel();
        contaField = new javax.swing.JTextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel1.setText(bundle.getString("codigo")); // NOI18N

        codTransField.setColumns(3);

        jLabel2.setText(bundle.getString("nome")); // NOI18N

        nomeField.setDocument(new BoundedPlainDocument(40));

        jLabel3.setText(bundle.getString("fone1")); // NOI18N

        fone1Field.setColumns(20);

        jLabel4.setText(bundle.getString("fone2")); // NOI18N

        fone2Field.setColumns(20);

        lblPgto.setText(bundle.getString("formaPgtoRepres")); // NOI18N

        pgtoComboBox.setInputVerifier(dateVerifier);

        lblConta.setText(bundle.getString("lblConta")); // NOI18N

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("vendas/swing/app/auxiliar/Bundle"); // NOI18N
        contaField.setText(bundle1.getString("TransportadorEditPanel.contaField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeField, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                    .addComponent(pgtoComboBox, 0, 396, Short.MAX_VALUE)
                    .addComponent(contaField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(fone1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(fone2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(lblPgto)
                            .addComponent(codTransField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblConta))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(codTransField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fone1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fone2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPgto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgtoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField codTransField;
    private javax.swing.JTextField contaField;
    private javax.swing.JFormattedTextField fone1Field;
    private javax.swing.JFormattedTextField fone2Field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblConta;
    private javax.swing.JLabel lblPgto;
    private javax.swing.JFormattedTextField nomeField;
    private javax.swing.JComboBox pgtoComboBox;
    // End of variables declaration//GEN-END:variables
    
}
