/**
 * UnidadeProdutoEditPanel.java
 *
 * Created on 10 de Julho de 2007, 16:58
 */

package vendas.swing.app.auxiliar;

import vendas.entity.UnidadeProduto;
import vendas.swing.core.EditPanel;
import ritual.swing.BoundedPlainDocument;

/**
 *
 * @author  p993702
 */
public class UnidadeProdutoEditPanel extends EditPanel {
    
    /** Creates new form UnidadeProdutoEditPanel */
    public UnidadeProdutoEditPanel() {
        initComponents();
    }

    @Override
    public void object2Field(Object obj) {
        UnidadeProduto unidade = (UnidadeProduto) obj;
        nomeField.setText(unidade.getNome());
        idUnidadeField.setText(unidade.getIdUnidade());
    }

    @Override
    public void field2Object(Object obj) {
        UnidadeProduto unidade = (UnidadeProduto) obj;
        unidade.setNome(nomeField.getText());
        unidade.setIdUnidade(idUnidadeField.getText());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        idUnidadeField = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        nomeField = new javax.swing.JFormattedTextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        jLabel3.setText(bundle.getString("sigla")); // NOI18N

        idUnidadeField.setDocument(new BoundedPlainDocument(5));

        jLabel2.setText(bundle.getString("nome")); // NOI18N

        nomeField.setDocument(new BoundedPlainDocument(40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idUnidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idUnidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField idUnidadeField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField nomeField;
    // End of variables declaration//GEN-END:variables
    
}
