/*
 * VendedorEditPanel.java
 *
 * Created on 23 de Junho de 2007, 13:03
 */

package vendas.swing.app.auxiliar;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import javax.swing.JFormattedTextField;
import ritual.swing.BoundedPlainDocument;
import vendas.entity.Vendedor;
import vendas.swing.core.EditPanel;
import ritual.swing.NumericPlainDocument;
import ritual.util.NumberUtils;
import vendas.swing.core.Formats;

/**
 *
 * @author  Sam
 */
public class VendedorEditPanel extends EditPanel {
    
    /** Creates new form VendedorEditPanel */
    public VendedorEditPanel() {
        initComponents();
        valComissaoField.setDocument(new NumericPlainDocument(new DecimalFormat("#0.00")));

    }
    
    @Override
    public void object2Field(Object obj) {
        Vendedor vendedor = (Vendedor) obj;
        bairroField.setText(vendedor.getBairro());
        cepField.setText(vendedor.getCep());
        cidadeField.setText(vendedor.getCidade());
        comissionadoCheckBox.setSelected(vendedor.getRecebeComissao().booleanValue());
        enderecoField.setText(vendedor.getEndereco());
        fone1Field.setText(vendedor.getFone1());
        fone2Field.setText(vendedor.getFone2());
        nomeField.setText(vendedor.getNome());
        ufField.setText(vendedor.getUf());
        valComissaoField.setValue(vendedor.getValorComissao());
        ativoCheckBox.setSelected(vendedor.isAtivo());
        if (vendedor.getDtAniver() != null) {
        jSpinner1.setValue(new Integer(vendedor.getMesAniversario()));
        jSpinner2.setValue(new Integer(vendedor.getAnoAniversario()));
        sigla.setText(vendedor.getSigla());
        }
    }

    @Override
    public void field2Object(Object obj) {
        Vendedor vendedor = (Vendedor) obj;
        DecimalFormat df = new DecimalFormat("00");

        vendedor.setBairro(bairroField.getText());
        vendedor.setCep(cepField.getText());
        vendedor.setCidade(cidadeField.getText());
        vendedor.setComissionado(comissionadoCheckBox.isSelected());
        vendedor.setEndereco(enderecoField.getText());
        vendedor.setFone1(fone1Field.getText());
        vendedor.setFone2(fone2Field.getText());
        vendedor.setNome(nomeField.getText());
        vendedor.setUf(ufField.getText());
        vendedor.setAtivo(ativoCheckBox.isSelected());
        vendedor.setSigla(sigla.getText());

        if (((Integer)jSpinner1.getValue()).intValue() == 0 || ((Integer)jSpinner2.getValue()).intValue() == 0)
            vendedor.setDtAniver(null);
        else
            vendedor.setDtAniver(df.format(jSpinner2.getValue()) + df.format(jSpinner1.getValue()));
        if (valComissaoField.getValue() != null)
            vendedor.setValorComissao(NumberUtils.getBigDecimal(valComissaoField.getValue()));
        else
            vendedor.setValorComissao(BigDecimal.ZERO);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeLabel = new javax.swing.JLabel();
        nomeField = new javax.swing.JFormattedTextField();
        enderecoLabel = new javax.swing.JLabel();
        enderecoField = new javax.swing.JFormattedTextField();
        bairroLabel = new javax.swing.JLabel();
        bairroField = new javax.swing.JFormattedTextField();
        cidadeLabel = new javax.swing.JLabel();
        cidadeField = new javax.swing.JFormattedTextField();
        cepLabel = new javax.swing.JLabel();
        cepField = new javax.swing.JFormattedTextField(Formats.createFormatter("########"));
        fone1Label = new javax.swing.JLabel();
        fone1Field = new javax.swing.JFormattedTextField();
        comissionadoCheckBox = new javax.swing.JCheckBox();
        ufLabel = new javax.swing.JLabel();
        ufField = new javax.swing.JFormattedTextField(Formats.createFormatter("UU"));
        fone2Label = new javax.swing.JLabel();
        fone2Field = new javax.swing.JFormattedTextField();
        valComissaoLabel = new javax.swing.JLabel();
        valComissaoField = new javax.swing.JFormattedTextField();
        ativoCheckBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        ufLabel1 = new javax.swing.JLabel();
        sigla = new javax.swing.JFormattedTextField(Formats.createFormatter("UU"));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vendas/resources/Vendas"); // NOI18N
        nomeLabel.setText(bundle.getString("nome")); // NOI18N

        nomeField.setColumns(40);
        nomeField.setDocument(new BoundedPlainDocument(40));

        enderecoLabel.setText(bundle.getString("endereco")); // NOI18N

        enderecoField.setColumns(40);
        enderecoField.setDocument(new BoundedPlainDocument(40));

        bairroLabel.setText(bundle.getString("bairro")); // NOI18N

        bairroField.setColumns(30);
        bairroField.setDocument(new BoundedPlainDocument(30));

        cidadeLabel.setText(bundle.getString("cidade")); // NOI18N

        cidadeField.setColumns(30);
        cidadeField.setDocument(new BoundedPlainDocument(30));

        cepLabel.setText(bundle.getString("cep")); // NOI18N

        cepField.setColumns(12);

        fone1Label.setText(bundle.getString("fone1")); // NOI18N

        fone1Field.setColumns(12);

        comissionadoCheckBox.setText(bundle.getString("recebeComissao")); // NOI18N
        comissionadoCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        ufLabel.setText(bundle.getString("uf")); // NOI18N

        ufField.setColumns(2);
        ufField.setDocument(new BoundedPlainDocument(2));

        fone2Label.setText(bundle.getString("fone2")); // NOI18N

        fone2Field.setColumns(12);

        valComissaoLabel.setText(bundle.getString("percComissao")); // NOI18N

        valComissaoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        valComissaoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                valComissaoFieldFocusLost(evt);
            }
        });

        ativoCheckBox.setText(bundle.getString("ativo")); // NOI18N

        jLabel2.setText(bundle.getString("aniversario")); // NOI18N

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 31, 1));

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("vendas/swing/app/auxiliar/Bundle"); // NOI18N
        ufLabel1.setText(bundle1.getString("VendedorEditPanel.ufLabel1.text")); // NOI18N

        sigla.setColumns(2);
        sigla.setDocument(new BoundedPlainDocument(2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enderecoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bairroLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cidadeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cepLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fone1Label, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(61, 61, 61)
                        .addComponent(ufLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bairroField)
                        .addComponent(enderecoField, 0, 1, Short.MAX_VALUE)
                        .addComponent(nomeField, 0, 1, Short.MAX_VALUE)
                        .addComponent(cidadeField)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ativoCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comissionadoCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fone1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fone2Label)
                                .addComponent(valComissaoLabel)
                                .addComponent(ufLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fone2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(valComissaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ufField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(38, 38, 38))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoLabel)
                    .addComponent(enderecoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bairroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidadeLabel)
                    .addComponent(cidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ufField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cepLabel)
                    .addComponent(ufLabel)
                    .addComponent(cepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fone1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fone2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fone1Label)
                    .addComponent(fone2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valComissaoLabel)
                    .addComponent(valComissaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comissionadoCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ufLabel1)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ativoCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void valComissaoFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valComissaoFieldFocusLost
        // TODO add your handling code here:
        JFormattedTextField f = (JFormattedTextField) evt.getComponent();
        if (f.getText() == null || f.getText().length() == 0)
            f.setValue(null);
    }//GEN-LAST:event_valComissaoFieldFocusLost
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ativoCheckBox;
    private javax.swing.JFormattedTextField bairroField;
    private javax.swing.JLabel bairroLabel;
    private javax.swing.JFormattedTextField cepField;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JFormattedTextField cidadeField;
    private javax.swing.JLabel cidadeLabel;
    private javax.swing.JCheckBox comissionadoCheckBox;
    private javax.swing.JFormattedTextField enderecoField;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JFormattedTextField fone1Field;
    private javax.swing.JLabel fone1Label;
    private javax.swing.JFormattedTextField fone2Field;
    private javax.swing.JLabel fone2Label;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JFormattedTextField nomeField;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JFormattedTextField sigla;
    private javax.swing.JFormattedTextField ufField;
    private javax.swing.JLabel ufLabel;
    private javax.swing.JLabel ufLabel1;
    private javax.swing.JFormattedTextField valComissaoField;
    private javax.swing.JLabel valComissaoLabel;
    // End of variables declaration//GEN-END:variables
    
}